/**
 * Example docs generation helpers.
 *
 * @module
 */

import { readdir, readFile } from 'node:fs/promises';
import { basename, extname, join, relative } from 'node:path';

import { collectRelatedGuides, type DocsLink } from './crosslinks.ts';
import { gitRef } from './paths.ts';
import { toSymbolPageRoute } from './symbol-pages.ts';

export interface ExampleRelatedSymbol {
  entrypoint: string;
  name: string;
  href: string;
}

export interface ExampleEntry {
  slug: string;
  title: string;
  summary: string;
  demonstrates: string | null;
  usage: readonly string[];
  sourcePath: string;
  routePath: string;
  sourceUrl: string;
  sourceCode: string;
  relatedGuides: readonly DocsLink[];
  relatedSymbols: readonly ExampleRelatedSymbol[];
  relatedLinks: readonly DocsLink[];
}

const GENERATED_HEADER =
  '<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->';

const REPO_BLOB_BASE_URL = `https://github.com/kjanat/dreamcli/blob/${gitRef}`;

export interface ExampleMeta {
  slug: string;
  title: string;
  routePath: string;
}

/**
 * Cheap metadata collection for sidebar generation.
 *
 * Reads only filenames and docblock summaries — no source code loading,
 * no symbol resolution, no TypeDoc. Safe to call in VitePress config.
 */
export async function collectExampleMeta(
  examplesRoot: string,
): Promise<readonly ExampleMeta[]> {
  const entries = await readdir(examplesRoot, { withFileTypes: true });
  const exampleFiles = entries
    .filter(
      (entry) =>
        entry.isFile() &&
        extname(entry.name) === '.ts' &&
        !entry.name.endsWith('.test.ts'),
    )
    .map((entry) => entry.name)
    .sort();

  return Promise.all(
    exampleFiles.map(async (fileName) => {
      const slug = basename(fileName, '.ts');
      const source = await readFile(join(examplesRoot, fileName), 'utf8');
      const docLines = extractDocLines(source);
      const title = firstNonEmpty(docLines) ?? titleFromSlug(slug);
      return { slug, title, routePath: `/examples/${slug}` };
    }),
  );
}

export async function collectExamples(
  examplesRoot: string,
  repoRoot: string,
): Promise<readonly ExampleEntry[]> {
  const entries = await readdir(examplesRoot, { withFileTypes: true });
  const exampleFiles = entries
    .filter(
      (entry) =>
        entry.isFile() &&
        extname(entry.name) === '.ts' &&
        !entry.name.endsWith('.test.ts'),
    )
    .map((entry) => entry.name)
    .sort();

  return Promise.all(
    exampleFiles.map(async (fileName) =>
      parseExample(join(examplesRoot, fileName), repoRoot),
    ),
  );
}

export function renderExamplesIndex(examples: readonly ExampleEntry[]): string {
  const rows = examples.map((example) => {
    const demonstrates = example.demonstrates ?? 'n/a';
    return `| [\`${example.slug}\`](${example.routePath}) | ${escapeTable(example.summary)} | ${escapeTable(demonstrates)} | \`${example.sourcePath}\` |`;
  });

  return [
    GENERATED_HEADER,
    '',
    '# Generated Examples Inventory',
    '',
    'This inventory is rebuilt by `bun run docs:prepare` from `examples/*.ts`.',
    '',
    '| Example | Summary | Demonstrates | Source |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

export function renderExamplePage(example: ExampleEntry): string {
  const usageSection =
    example.usage.length === 0
      ? ['No usage snippets declared in the example docblock.', '']
      : ['```bash', ...example.usage, '```', ''];
  const relatedGuides = example.relatedGuides.map(
    (link) => `- [${link.label}](${link.href})`,
  );
  const relatedLinks =
    example.relatedLinks.length === 0
      ? [
          '- [Examples overview](/examples/)',
          '- [API overview](/reference/api)',
        ]
      : example.relatedLinks.map((link) => `- [${link.label}](${link.href})`);

  return [
    `# ${example.title}`,
    '',
    example.summary,
    '',
    `- Source: [\`${example.sourcePath}\`](${example.sourceUrl})`,
    ...(example.demonstrates === null
      ? []
      : [`- Demonstrates: ${example.demonstrates}`]),
    '',
    '## Usage',
    '',
    ...usageSection,
    ...(relatedGuides.length === 0
      ? []
      : ['## Related Guides', '', ...relatedGuides, '']),
    '## Related Links',
    '',
    ...relatedLinks,
    '',
    '## Source',
    '',
    '```ts twoslash',
    example.sourceCode.trimEnd(),
    '```',
    '',
  ].join('\n');
}

async function parseExample(
  filePath: string,
  repoRoot: string,
): Promise<ExampleEntry> {
  const source = await readFile(filePath, 'utf8');
  const sourcePath = toRepoPath(filePath, repoRoot);
  const slug = basename(filePath, '.ts');
  const docLines = extractDocLines(source);
  const summary = firstNonEmpty(docLines) ?? titleFromSlug(slug);
  const demonstrates = extractLabeledValue(docLines, 'Demonstrates');
  const usage = extractUsage(docLines);

  return {
    slug,
    title: summary,
    summary,
    demonstrates,
    usage,
    sourcePath,
    routePath: `/examples/${slug}`,
    sourceUrl: `${REPO_BLOB_BASE_URL}/${sourcePath}`,
    sourceCode: source,
    relatedGuides: collectRelatedGuides(slug),
    ...collectRelatedLinks(source),
  };
}

function collectRelatedLinks(source: string): {
  relatedSymbols: readonly ExampleRelatedSymbol[];
  relatedLinks: readonly DocsLink[];
} {
  const symbolLinks = new Map<string, ExampleRelatedSymbol>();
  for (const match of source.matchAll(
    /import\s*\{([^}]+)\}\s*from\s*'([^']+)'/g,
  )) {
    const importList = match[1];
    const moduleName = match[2];
    if (
      importList === undefined ||
      moduleName === undefined ||
      !isDreamcliImport(moduleName)
    ) {
      continue;
    }

    for (const entry of importList.split(',')) {
      const importedName = normalizeImportedName(entry);
      if (importedName === null) {
        continue;
      }
      symbolLinks.set(`${moduleName}:${importedName}`, {
        entrypoint: moduleName,
        name: importedName,
        href: toSymbolPageRoute(moduleName, importedName),
      });
    }
  }

  const relatedSymbols = Array.from(symbolLinks.values()).sort((left, right) =>
    left.name.localeCompare(right.name),
  );

  return {
    relatedSymbols,
    relatedLinks: [
      { label: 'Examples overview', href: '/examples/' },
      { label: 'API overview', href: '/reference/api' },
      ...relatedSymbols.map((symbol) => ({
        label: `\`${symbol.name}\``,
        href: symbol.href,
      })),
    ],
  };
}

function normalizeImportedName(entry: string): string | null {
  const trimmed = entry.trim();
  if (trimmed === '') {
    return null;
  }
  const withoutType = trimmed.startsWith('type ')
    ? trimmed.slice(5).trim()
    : trimmed;
  const importedName = withoutType.split(' as ')[0]?.trim();
  return importedName === undefined || importedName === ''
    ? null
    : importedName;
}

function isDreamcliImport(moduleName: string): boolean {
  return (
    moduleName === '@kjanat/dreamcli' ||
    moduleName.startsWith('@kjanat/dreamcli/')
  );
}

function extractDocLines(source: string): readonly string[] {
  const match =
    /^#!.*\n\/\*\*([\s\S]*?)\*\//.exec(source) ??
    /^\/\*\*([\s\S]*?)\*\//.exec(source);
  if (match === null) {
    return [];
  }
  const docBlock = match[1];
  if (docBlock === undefined) {
    return [];
  }

  return docBlock
    .split('\n')
    .map((line) => line.replace(/^\s*\* ?/, '').trimEnd());
}

function extractUsage(lines: readonly string[]): readonly string[] {
  const usageIndex = lines.indexOf('Usage:');
  if (usageIndex === -1) {
    return [];
  }

  const usage: string[] = [];
  for (const line of lines.slice(usageIndex + 1)) {
    if (line.trim() === '') {
      if (usage.length > 0) {
        break;
      }
      continue;
    }

    usage.push(line.trim());
  }

  return usage;
}

function extractLabeledValue(
  lines: readonly string[],
  label: string,
): string | null {
  const prefix = `${label}:`;
  const startIndex = lines.findIndex((line) => line.startsWith(prefix));
  if (startIndex === -1) return null;

  const startLine = lines[startIndex];
  if (startLine === undefined) return null;
  const firstValue = startLine.slice(prefix.length).trim();
  if (firstValue === '') return null;

  const parts = [firstValue];
  for (let i = startIndex + 1; i < lines.length; i++) {
    const line = lines[i];
    if (line === undefined) break;
    const trimmed = line.trim();
    if (trimmed === '' || /^[A-Z]\w*:/.test(trimmed)) break;
    parts.push(trimmed);
  }

  return parts.join(' ');
}

function firstNonEmpty(lines: readonly string[]): string | null {
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed !== '') {
      return trimmed;
    }
  }

  return null;
}

function titleFromSlug(slug: string): string {
  return slug
    .split('-')
    .map((part) => {
      const [firstChar, ...rest] = part;
      if (firstChar === undefined) {
        return part;
      }

      return `${firstChar.toUpperCase()}${rest.join('')}`;
    })
    .join(' ');
}

function escapeTable(value: string): string {
  return value.replaceAll('|', '\\|');
}

function toRepoPath(filePath: string, repoRoot: string): string {
  return relative(repoRoot, filePath).replaceAll('\\', '/');
}
