name: bun-deno-runner
description: A GitHub Action to setup Bun and Deno environments for running scripts, with runner/run bins.
runs: {
  using: composite,
  steps: [
    uses: kjanat/runner@master,
    uses: denoland/setup-deno@v2,
    { uses: oven-sh/setup-bun@v2, with: { bun-version: latest } },
    { uses: actions/setup-node@v7, with: { node-version: latest } },
    uses: kjanat/install-dprint@v2,
  ],
}
