#:schema https://www.schemastore.org/bunfig.json

telemetry = false

[install]
auto          = "auto"
lockfile.save = true

[run]
silent = true

[test]
root           = "./src"
coverage       = true
reporter.dots  = true
reporter.junit = ".bucket/test-results.xml"
coverageDir    = ".bucket/coverage"
randomize      = true
rerunEach      = 3
