#:schema https://www.schemastore.org/bunfig.json

telemetry = false

[install]
exact = true
auto = "auto"
lockfile.save = true
# 7 days in seconds
# minimumReleaseAge = 604800
minimumReleaseAgeExcludes = [
  "@types/node",
  "@typescript/native-preview",
  "typescript",
  "tsdown",
]

[run]
silent = true
