#:schema https://kjanat.github.io/runner/schemas/runner.toml.schema.json

[pm]
node = "bun"

[github]
group_output = true

[install]
# pms     = ["bun"]
scripts = "allow"  # unsupported for bun at the moment as a bun limitation.
