/**
 * Fish completion script generator.
 *
 * Produces a self-contained fish script with:
 * - A command-path helper for nested command dispatch
 * - Per-path `complete` entries for visible commands and aliases
 * - Per-path flag definitions including propagated ancestor flags
 * - Enum value completions for option arguments
 * - Root-surface support for default-command completion policy
 *
 * @module dreamcli/core/completion/shells/fish
 * @internal
 */

import type { CLISchema } from '#internals/core/cli/index.ts';
import { getFlagAliasNames } from '#internals/core/schema/flag.ts';
import type { FlagSchema } from '#internals/core/schema/index.ts';
import type { CommandNode, CompletionOptions, RootCompletionSurface } from './shared.ts';
import {
	quoteShellArg,
	resolveRootCompletionSurface,
	sanitizeShellIdentifier,
	versionTag,
	walkCommandTree,
} from './shared.ts';

/**
 * Generate a fish completion script for the CLI.
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete fish completion script.
 *
 * @example
 * ```ts
 * const script = generateFishCompletion(app.schema);
 * // install with: mycli completions fish > ~/.config/fish/completions/mycli.fish
 * ```
 */
function generateFishCompletion(schema: CLISchema, options?: CompletionOptions): string {
	const prefix = options?.functionPrefix ?? schema.name;
	const helperPrefix = `__${sanitizeShellIdentifier(prefix)}_completions`;
	const pathFuncName = `${helperPrefix}_path`;
	const pathIsFuncName = `${helperPrefix}_path_is`;
	const rootSurface = resolveRootCompletionSurface(schema, options?.rootMode);
	const visibleCommands = rootSurface.visibleCommands;
	const nodes = walkCommandTree(visibleCommands);
	const commandName = quoteShellArg(schema.name);

	const lines: string[] = [];

	lines.push(`# Fish completion for ${schema.name}`);
	lines.push(`# Generated by ${versionTag()}`);
	lines.push('#');
	lines.push(`# Usage:  source (${schema.name} completions fish | psub)`);
	lines.push('#');
	lines.push('# Install permanently:');
	lines.push(
		`#   ${schema.name} completions fish > ~/.config/fish/completions/${schema.name}.fish`,
	);
	lines.push('');
	lines.push(`complete -c ${commandName} -f`);
	lines.push('');

	emitFishPathHelpers(lines, pathFuncName, pathIsFuncName, visibleCommands, nodes, rootSurface);

	appendFishCommandCompletions(lines, commandName, pathIsFuncName, '', visibleCommands);
	appendFishFlagCompletions(lines, commandName, pathIsFuncName, '', rootSurface.rootFlags);
	if (rootSurface.includeDefaultFlags) {
		appendFishFlagCompletions(lines, commandName, pathIsFuncName, '', rootSurface.defaultFlags);
	}

	for (const node of nodes) {
		const path = node.path.join(' ');
		appendFishCommandCompletions(lines, commandName, pathIsFuncName, path, node.children);
		appendFishFlagCompletions(lines, commandName, pathIsFuncName, path, node.mergedFlags);
	}

	return lines.join('\n');
}

function emitFishPathHelpers(
	lines: string[],
	pathFuncName: string,
	pathIsFuncName: string,
	visibleCommands: readonly {
		readonly name: string;
		readonly aliases: readonly string[];
	}[],
	nodes: readonly CommandNode[],
	rootSurface: RootCompletionSurface,
): void {
	const valueFlags = collectFishValueFlagPatterns(nodes, rootSurface);

	lines.push(`function ${pathFuncName}`);
	lines.push('\tset -l words (commandline -opc)');
	lines.push('\tif test (count $words) -gt 0');
	lines.push('\t\tset -e words[1]');
	lines.push('\tend');
	lines.push("\tset -l subcmd_path ''");
	lines.push('\tset -l expect_value 0');
	lines.push('\tfor word in $words');
	lines.push('\t\tif test $expect_value -eq 1');
	lines.push('\t\t\tset expect_value 0');
	lines.push('\t\t\tcontinue');
	lines.push('\t\tend');
	lines.push('\t\tswitch $word');
	lines.push("\t\t\tcase '--'");
	lines.push('\t\t\t\tbreak');
	if (valueFlags.exact.length > 0) {
		lines.push(`\t\t\tcase ${valueFlags.exact.map(quoteShellArg).join(' ')}`);
		lines.push('\t\t\t\tset expect_value 1');
		lines.push('\t\t\t\tcontinue');
	}
	if (valueFlags.prefix.length > 0) {
		lines.push(`\t\t\tcase ${valueFlags.prefix.map(quoteShellArg).join(' ')}`);
		lines.push('\t\t\t\tcontinue');
	}
	lines.push("\t\t\tcase '-*'");
	lines.push('\t\t\t\tcontinue');
	lines.push('\t\tend');
	lines.push('\t\tswitch "$subcmd_path|$word"');

	for (const command of visibleCommands) {
		for (const name of [command.name, ...command.aliases]) {
			lines.push(`\t\t\tcase ${quoteShellArg(`|${name}`)}`);
			lines.push(`\t\t\t\tset subcmd_path ${quoteShellArg(command.name)}`);
		}
	}

	for (const node of nodes) {
		for (const child of node.children) {
			for (const name of [child.name, ...child.aliases]) {
				lines.push(`\t\t\tcase ${quoteShellArg(`${node.path.join(' ')}|${name}`)}`);
				lines.push(
					`\t\t\t\tset subcmd_path ${quoteShellArg(`${node.path.join(' ')} ${child.name}`)}`,
				);
			}
		}
	}

	lines.push("\t\t\tcase '*'");
	lines.push('\t\t\t\tbreak');
	lines.push('\t\tend');
	lines.push('\tend');
	lines.push('\tprintf \'%s\\n\' "$subcmd_path"');
	lines.push('end');
	lines.push('');
	lines.push(`function ${pathIsFuncName}`);
	lines.push('\tset -l expected "$argv[1]"');
	lines.push(`\ttest (${pathFuncName}) = "$expected"`);
	lines.push('end');
	lines.push('');
}

function appendFishCommandCompletions(
	lines: string[],
	commandName: string,
	pathIsFuncName: string,
	path: string,
	commands: ReadonlyArray<{
		readonly name: string;
		readonly aliases: readonly string[];
		readonly description: string | undefined;
	}>,
): void {
	const condition = buildFishCondition(pathIsFuncName, path);
	for (const command of commands) {
		const description = quoteShellArg(command.description ?? command.name);
		for (const name of [command.name, ...command.aliases]) {
			lines.push(
				`complete -c ${commandName} -n "${condition}" -a ${quoteShellArg(name)} -d ${description}`,
			);
		}
	}
	if (commands.length > 0) {
		lines.push('');
	}
}

function appendFishFlagCompletions(
	lines: string[],
	commandName: string,
	pathIsFuncName: string,
	path: string,
	flags: Readonly<Record<string, FlagSchema>>,
): void {
	const condition = buildFishCondition(pathIsFuncName, path);
	for (const [name, schema] of Object.entries(flags)) {
		const parts = [`complete -c ${commandName}`, `-n "${condition}"`];
		for (const alias of getFlagAliasNames(schema, { kind: 'short' })) {
			parts.push(`-s ${quoteShellArg(alias)}`);
		}
		parts.push(`-l ${quoteShellArg(name)}`);
		for (const alias of getFlagAliasNames(schema, { kind: 'long' })) {
			parts.push(`-l ${quoteShellArg(alias)}`);
		}
		parts.push(`-d ${quoteShellArg(schema.description ?? name)}`);

		if (schema.kind !== 'boolean') {
			parts.push('-r', '-f');
		}
		if (schema.kind === 'enum' && schema.enumValues !== undefined) {
			parts.push(`-a "${schema.enumValues.join(' ')}"`);
		}

		lines.push(parts.join(' '));
	}
	if (Object.keys(flags).length > 0) {
		lines.push('');
	}
}

function collectFishValueFlagPatterns(
	nodes: readonly CommandNode[],
	rootSurface: RootCompletionSurface,
): {
	readonly exact: readonly string[];
	readonly prefix: readonly string[];
} {
	const exact = new Set<string>();
	const prefix = new Set<string>();
	const flagSets: ReadonlyArray<Readonly<Record<string, FlagSchema>>> = [
		rootSurface.rootFlags,
		rootSurface.defaultFlags,
		...nodes.map((node) => node.mergedFlags),
	];

	for (const flags of flagSets) {
		for (const [name, schema] of Object.entries(flags)) {
			if (schema.kind === 'boolean') continue;

			exact.add(`--${name}`);
			prefix.add(`--${name}=*`);
			for (const alias of getFlagAliasNames(schema, { kind: 'short' })) {
				exact.add(`-${alias}`);
				prefix.add(`-${alias}*`);
			}
			for (const alias of getFlagAliasNames(schema, { kind: 'long' })) {
				exact.add(`--${alias}`);
				prefix.add(`--${alias}=*`);
			}
		}
	}

	return {
		exact: [...exact],
		prefix: [...prefix],
	};
}

function buildFishCondition(pathIsFuncName: string, path: string): string {
	return `${pathIsFuncName} ${quoteShellArg(path)}`;
}

export { generateFishCompletion };
