/**
 * PowerShell completion script generator.
 *
 * Produces a self-contained PowerShell script with:
 * - A native `Register-ArgumentCompleter` registration
 * - Precomputed command-path metadata for nested dispatch
 * - Per-path command and flag entries including propagated ancestor flags
 * - Enum value completions for option arguments
 * - Root-surface support for default-command completion policy
 *
 * @module dreamcli/core/completion/shells/powershell
 * @internal
 */

import type { CLISchema } from '#internals/core/cli/index.ts';
import { getFlagAliasNames } from '#internals/core/schema/flag.ts';
import type { FlagSchema } from '#internals/core/schema/index.ts';
import type { CommandNode, CompletionOptions, RootCompletionSurface } from './shared.ts';
import {
	resolveRootCompletionSurface,
	sanitizeShellIdentifier,
	versionTag,
	walkCommandTree,
} from './shared.ts';

/**
 * Generate a PowerShell completion script for the CLI.
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete PowerShell completion script.
 */
function generatePowerShellCompletion(schema: CLISchema, options?: CompletionOptions): string {
	const prefix = options?.functionPrefix ?? schema.name;
	const helperPrefix = `__${sanitizeShellIdentifier(prefix)}_completions`;
	const dataVarName = `${helperPrefix}_paths`;
	const rootSurface = resolveRootCompletionSurface(schema, options?.rootMode);
	const visibleCommands = rootSurface.visibleCommands;
	const nodes = walkCommandTree(visibleCommands);

	const lines: string[] = [];

	lines.push(`# PowerShell completion for ${schema.name}`);
	lines.push(`# Generated by ${versionTag()}`);
	lines.push('#');
	lines.push('# Install for the current session:');
	lines.push(`#   ${schema.name} completions powershell | Out-String | Invoke-Expression`);
	lines.push('#');
	lines.push('# Install permanently:');
	lines.push(`#   ${schema.name} completions powershell > $PROFILE.CurrentUserCurrentHost`);
	lines.push('');
	lines.push('using namespace System.Management.Automation');
	lines.push('using namespace System.Management.Automation.Language');
	lines.push('');

	emitPowerShellPathTable(lines, dataVarName, rootSurface, nodes);
	lines.push('');
	emitPowerShellHelpers(lines, helperPrefix, dataVarName);
	lines.push('');
	lines.push(
		`Register-ArgumentCompleter -Native -CommandName ${quotePowerShellString(schema.name)} -ScriptBlock {`,
	);
	lines.push('\tparam($wordToComplete, $commandAst, $cursorPosition)');
	lines.push(
		`\t$state = ${helperPrefix}_GetState -CommandAst $commandAst -CursorPosition $cursorPosition`,
	);
	lines.push('\tif ($null -eq $state.PathData) {');
	lines.push('\t\treturn');
	lines.push('\t}');
	lines.push('');
	lines.push('\t$results = [System.Collections.Generic.List[CompletionResult]]::new()');
	lines.push(
		`\t$wordPrefix = if ([string]::IsNullOrEmpty($wordToComplete)) { '' } else { $wordToComplete }`,
	);
	lines.push('');
	lines.push('\tif ($state.ExpectingValue) {');
	lines.push(
		`\t\t${helperPrefix}_AddEnumResults -Results $results -Flag $state.ValueFlag -WordToComplete $wordPrefix`,
	);
	lines.push('\t\treturn $results');
	lines.push('\t}');
	lines.push('');
	lines.push(
		`\t$inlineValue = ${helperPrefix}_ResolveInlineValueCompletion -PathData $state.PathData -WordToComplete $wordPrefix`,
	);
	lines.push('\tif ($null -ne $inlineValue) {');
	lines.push(
		`\t\t${helperPrefix}_AddInlineEnumResults -Results $results -InlineValue $inlineValue -WordToComplete $wordPrefix`,
	);
	lines.push('\t\treturn $results');
	lines.push('\t}');
	lines.push('');
	lines.push("\tif ($wordPrefix.StartsWith('-')) {");
	lines.push(
		`\t\t${helperPrefix}_AddFlagResults -Results $results -PathData $state.PathData -WordToComplete $wordPrefix`,
	);
	lines.push('\t\treturn $results');
	lines.push('\t}');
	lines.push('');
	lines.push(
		`\t${helperPrefix}_AddCommandResults -Results $results -PathData $state.PathData -WordToComplete $wordPrefix`,
	);
	lines.push(
		`\t${helperPrefix}_AddFlagResults -Results $results -PathData $state.PathData -WordToComplete $wordPrefix`,
	);
	lines.push('\treturn $results');
	lines.push('}');

	return lines.join('\n');
}

function emitPowerShellPathTable(
	lines: string[],
	dataVarName: string,
	rootSurface: RootCompletionSurface,
	nodes: readonly CommandNode[],
): void {
	lines.push(`$script:${dataVarName} = @{`);
	appendPowerShellPathEntry(lines, '', rootSurface.visibleCommands, {
		...rootSurface.rootFlags,
		...(rootSurface.includeDefaultFlags ? rootSurface.defaultFlags : {}),
	});

	for (const node of nodes) {
		appendPowerShellPathEntry(lines, node.path.join(' '), node.children, node.mergedFlags);
	}

	lines.push('}');
}

function appendPowerShellPathEntry(
	lines: string[],
	path: string,
	commands: ReadonlyArray<{
		readonly name: string;
		readonly aliases: readonly string[];
		readonly description: string | undefined;
	}>,
	flags: Readonly<Record<string, FlagSchema>>,
): void {
	lines.push(`\t${quotePowerShellString(path)} = @{`);
	lines.push('\t\tCommands = @(');
	for (const command of commands) {
		lines.push('\t\t\t@{');
		lines.push(`\t\t\t\tCanonicalName = ${quotePowerShellString(command.name)}`);
		lines.push(`\t\t\t\tNames = ${formatPowerShellArray([command.name, ...command.aliases])}`);
		lines.push(
			`\t\t\t\tDescription = ${quotePowerShellString(command.description ?? command.name)}`,
		);
		lines.push('\t\t\t}');
	}
	lines.push('\t\t)');
	lines.push('\t\tFlags = @(');
	for (const [name, schema] of Object.entries(flags)) {
		const forms = dedupeValues([
			`--${name}`,
			...getFlagAliasNames(schema, { kind: 'short' }).map((alias) => `-${alias}`),
			...getFlagAliasNames(schema, { kind: 'long' }).map((alias) => `--${alias}`),
		]);
		const parseForms = dedupeValues([
			`--${name}`,
			...getFlagAliasNames(schema, { kind: 'short', includeHidden: true }).map(
				(alias) => `-${alias}`,
			),
			...getFlagAliasNames(schema, { kind: 'long', includeHidden: true }).map(
				(alias) => `--${alias}`,
			),
		]);
		lines.push('\t\t\t@{');
		lines.push(`\t\t\t\tCanonicalName = ${quotePowerShellString(name)}`);
		lines.push(`\t\t\t\tForms = ${formatPowerShellArray(forms)}`);
		lines.push(`\t\t\t\tParseForms = ${formatPowerShellArray(parseForms)}`);
		lines.push(`\t\t\t\tRequiresValue = ${schema.kind === 'boolean' ? '$false' : '$true'}`);
		lines.push(`\t\t\t\tDescription = ${quotePowerShellString(schema.description ?? name)}`);
		lines.push(`\t\t\t\tEnumValues = ${formatPowerShellArray(schema.enumValues ?? [])}`);
		lines.push('\t\t\t}');
	}
	lines.push('\t\t)');
	lines.push('\t}');
}

function emitPowerShellHelpers(lines: string[], helperPrefix: string, dataVarName: string): void {
	lines.push(`function ${helperPrefix}_UnquoteToken {`);
	lines.push('\tparam([string]$TokenText)');
	lines.push('\tif ($TokenText.Length -lt 2) {');
	lines.push('\t\treturn $TokenText');
	lines.push('\t}');
	lines.push('');
	lines.push('\tif (($TokenText.StartsWith("\'") -and $TokenText.EndsWith("\'")) -or');
	lines.push("\t\t($TokenText.StartsWith('\"') -and $TokenText.EndsWith('\"'))) {");
	lines.push('\t\treturn $TokenText.Substring(1, $TokenText.Length - 2)');
	lines.push('\t}');
	lines.push('');
	lines.push('\treturn $TokenText');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_FindCommand {`);
	lines.push('\tparam($PathData, [string]$Token)');
	lines.push('\tforeach ($command in $PathData.Commands) {');
	lines.push('\t\tforeach ($name in $command.Names) {');
	lines.push('\t\t\tif ($name -eq $Token) {');
	lines.push('\t\t\t\treturn $command');
	lines.push('\t\t\t}');
	lines.push('\t\t}');
	lines.push('\t}');
	lines.push('\treturn $null');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_ResolveFlagToken {`);
	lines.push('\tparam($PathData, [string]$Token)');
	lines.push('\tforeach ($flag in $PathData.Flags) {');
	lines.push('\t\tforeach ($form in $flag.ParseForms) {');
	lines.push('\t\t\tif ($Token -eq $form) {');
	lines.push('\t\t\t\treturn @{ Flag = $flag; InlinePrefix = $null }');
	lines.push('\t\t\t}');
	lines.push('');
	lines.push('\t\t\tif (-not $flag.RequiresValue) {');
	lines.push('\t\t\t\tcontinue');
	lines.push('\t\t\t}');
	lines.push('');
	lines.push('\t\t\tif ($form.StartsWith(\'--\') -and $Token.StartsWith("$form=")) {');
	lines.push('\t\t\t\treturn @{ Flag = $flag; InlinePrefix = "$form=" }');
	lines.push('\t\t\t}');
	lines.push('');
	lines.push(
		"\t\t\tif ($form.StartsWith('-') -and -not $form.StartsWith('--') -and $Token.StartsWith($form) -and $Token.Length -gt $form.Length) {",
	);
	lines.push('\t\t\t\treturn @{ Flag = $flag; InlinePrefix = $form }');
	lines.push('\t\t\t}');
	lines.push('\t\t}');
	lines.push('\t}');
	lines.push('\treturn $null');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_GetState {`);
	lines.push('\tparam([CommandAst]$CommandAst, [int]$CursorPosition)');
	lines.push(`\t$pathData = $script:${dataVarName}[${quotePowerShellString('')}]`);
	lines.push('\t$path = ""');
	lines.push('\t$expectingValue = $false');
	lines.push('\t$valueFlag = $null');
	lines.push('\t$tokens = [System.Collections.Generic.List[string]]::new()');
	lines.push('');
	lines.push('\tforeach ($element in $CommandAst.CommandElements | Select-Object -Skip 1) {');
	lines.push('\t\tif ($element.Extent.EndOffset -gt $CursorPosition) {');
	lines.push('\t\t\tbreak');
	lines.push('\t\t}');
	lines.push(`\t\t$tokenText = ${helperPrefix}_UnquoteToken $element.Extent.Text`);
	lines.push('\t\t[void]$tokens.Add($tokenText)');
	lines.push('\t}');
	lines.push('');
	lines.push('\tforeach ($token in $tokens) {');
	lines.push('\t\tif ($expectingValue) {');
	lines.push('\t\t\t$expectingValue = $false');
	lines.push('\t\t\t$valueFlag = $null');
	lines.push('\t\t\tcontinue');
	lines.push('\t\t}');
	lines.push('');
	lines.push("\t\tif ($token -eq '--') {");
	lines.push('\t\t\tbreak');
	lines.push('\t\t}');
	lines.push('');
	lines.push(`\t\t$flagMatch = ${helperPrefix}_ResolveFlagToken -PathData $pathData -Token $token`);
	lines.push('\t\tif ($null -ne $flagMatch) {');
	lines.push('\t\t\tif ($flagMatch.InlinePrefix -eq $null -and $flagMatch.Flag.RequiresValue) {');
	lines.push('\t\t\t\t$expectingValue = $true');
	lines.push('\t\t\t\t$valueFlag = $flagMatch.Flag');
	lines.push('\t\t\t}');
	lines.push('\t\t\tcontinue');
	lines.push('\t\t}');
	lines.push('');
	lines.push("\t\tif ($token.StartsWith('-')) {");
	lines.push('\t\t\tcontinue');
	lines.push('\t\t}');
	lines.push('');
	lines.push(`\t\t$command = ${helperPrefix}_FindCommand -PathData $pathData -Token $token`);
	lines.push('\t\tif ($null -eq $command) {');
	lines.push('\t\t\tbreak');
	lines.push('\t\t}');
	lines.push('');
	lines.push('\t\t$path = if ([string]::IsNullOrEmpty($path)) {');
	lines.push('\t\t\t$command.CanonicalName');
	lines.push('\t\t} else {');
	lines.push('\t\t\t"$path $($command.CanonicalName)"');
	lines.push('\t\t}');
	lines.push(`\t\t$nextPathData = $script:${dataVarName}[$path]`);
	lines.push('\t\tif ($null -eq $nextPathData) {');
	lines.push('\t\t\tbreak');
	lines.push('\t\t}');
	lines.push('\t\t$pathData = $nextPathData');
	lines.push('\t}');
	lines.push('');
	lines.push('\treturn @{');
	lines.push('\t\tPath = $path');
	lines.push('\t\tPathData = $pathData');
	lines.push('\t\tExpectingValue = $expectingValue');
	lines.push('\t\tValueFlag = $valueFlag');
	lines.push('\t}');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_ResolveInlineValueCompletion {`);
	lines.push('\tparam($PathData, [string]$WordToComplete)');
	lines.push(
		`\t$flagMatch = ${helperPrefix}_ResolveFlagToken -PathData $PathData -Token $WordToComplete`,
	);
	lines.push('\tif ($null -eq $flagMatch -or $flagMatch.InlinePrefix -eq $null) {');
	lines.push('\t\treturn $null');
	lines.push('\t}');
	lines.push('\treturn $flagMatch');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_AddCommandResults {`);
	lines.push('\tparam($Results, $PathData, [string]$WordToComplete)');
	lines.push('\tforeach ($command in $PathData.Commands) {');
	lines.push('\t\tforeach ($name in $command.Names) {');
	lines.push(
		'\t\t\tif (-not [string]::IsNullOrEmpty($WordToComplete) -and -not $name.StartsWith($WordToComplete, [System.StringComparison]::OrdinalIgnoreCase)) {',
	);
	lines.push('\t\t\t\tcontinue');
	lines.push('\t\t\t}');
	lines.push('');
	lines.push('\t\t\t$Results.Add([CompletionResult]::new(');
	lines.push('\t\t\t\t$name,');
	lines.push('\t\t\t\t$name,');
	lines.push('\t\t\t\t[CompletionResultType]::Command,');
	lines.push('\t\t\t\t$command.Description');
	lines.push('\t\t\t))');
	lines.push('\t\t}');
	lines.push('\t}');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_AddFlagResults {`);
	lines.push('\tparam($Results, $PathData, [string]$WordToComplete)');
	lines.push('\tforeach ($flag in $PathData.Flags) {');
	lines.push('\t\tforeach ($form in $flag.Forms) {');
	lines.push(
		'\t\t\tif (-not [string]::IsNullOrEmpty($WordToComplete) -and -not $form.StartsWith($WordToComplete, [System.StringComparison]::OrdinalIgnoreCase)) {',
	);
	lines.push('\t\t\t\tcontinue');
	lines.push('\t\t\t}');
	lines.push('');
	lines.push('\t\t\t$Results.Add([CompletionResult]::new(');
	lines.push('\t\t\t\t$form,');
	lines.push('\t\t\t\t$form,');
	lines.push('\t\t\t\t[CompletionResultType]::ParameterName,');
	lines.push('\t\t\t\t$flag.Description');
	lines.push('\t\t\t))');
	lines.push('\t\t}');
	lines.push('\t}');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_AddEnumResults {`);
	lines.push('\tparam($Results, $Flag, [string]$WordToComplete)');
	lines.push('\tforeach ($value in $Flag.EnumValues) {');
	lines.push(
		'\t\tif (-not [string]::IsNullOrEmpty($WordToComplete) -and -not $value.StartsWith($WordToComplete, [System.StringComparison]::OrdinalIgnoreCase)) {',
	);
	lines.push('\t\t\tcontinue');
	lines.push('\t\t}');
	lines.push('');
	lines.push('\t\t$Results.Add([CompletionResult]::new(');
	lines.push('\t\t\t$value,');
	lines.push('\t\t\t$value,');
	lines.push('\t\t\t[CompletionResultType]::ParameterValue,');
	lines.push('\t\t\t$Flag.Description');
	lines.push('\t\t))');
	lines.push('\t}');
	lines.push('}');
	lines.push('');
	lines.push(`function ${helperPrefix}_AddInlineEnumResults {`);
	lines.push('\tparam($Results, $InlineValue, [string]$WordToComplete)');
	lines.push('\tforeach ($value in $InlineValue.Flag.EnumValues) {');
	lines.push('\t\t$completion = "$($InlineValue.InlinePrefix)$value"');
	lines.push(
		'\t\tif (-not [string]::IsNullOrEmpty($WordToComplete) -and -not $completion.StartsWith($WordToComplete, [System.StringComparison]::OrdinalIgnoreCase)) {',
	);
	lines.push('\t\t\tcontinue');
	lines.push('\t\t}');
	lines.push('');
	lines.push('\t\t$Results.Add([CompletionResult]::new(');
	lines.push('\t\t\t$completion,');
	lines.push('\t\t\t$value,');
	lines.push('\t\t\t[CompletionResultType]::ParameterValue,');
	lines.push('\t\t\t$InlineValue.Flag.Description');
	lines.push('\t\t))');
	lines.push('\t}');
	lines.push('}');
}

function quotePowerShellString(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

function formatPowerShellArray(values: readonly string[]): string {
	if (values.length === 0) {
		return '@()';
	}

	return `@(${values.map(quotePowerShellString).join(', ')})`;
}

function dedupeValues(values: readonly string[]): readonly string[] {
	return [...new Set(values)];
}

export { generatePowerShellCompletion };
