#!/usr/bin/env bun

/**
 * Rebuild generated docs foundation artifacts.
 *
 * @module
 */

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, extname, join, relative } from 'node:path';

import {
	collectPublicApiIndex,
	countPublicApiSymbols,
	type PublicApiEntrypoint,
	renderPublicApiIndex,
} from './shared/api-index.ts';
import {
	changelogPath,
	docsRoot,
	examplesRoot,
	generatedApiDir,
	generatedApiIndexPath,
	generatedApiPagePath,
	generatedChangelogPath,
	generatedDocsHealthPath,
	generatedExamplesDir,
	generatedExamplesIndexPath,
	generatedNormalizedTypeDocPath,
	generatedReferenceDir,
	generatedRoot,
	generatedSiteDataPath,
	generatedTypeDocJsonPath,
	packageJsonPath,
	symbolPagesRoot,
} from './shared/paths.ts';
import { collectSymbolPages } from './shared/symbol-pages.ts';
import { collectTypeDocModel } from './shared/typedoc.ts';

interface ExampleEntry {
	slug: string;
	title: string;
	summary: string;
	demonstrates: string | null;
	usage: readonly string[];
	sourcePath: string;
}

interface GeneratedReferenceSurface {
	id: string;
	title: string;
	artifactPath: string;
	sourceInputs: readonly string[];
	status: 'prepared';
	notes: string;
}

interface DocsHealthSnapshot {
	authoredPageCount: number;
	generatedArtifactCount: number;
	exampleCount: number;
	publicEntrypointCount: number;
	publicSymbolCount: number;
	symbolPageCount: number;
}

const GENERATED_HEADER =
	'<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->';

await rebuildDocsArtifacts();

async function rebuildDocsArtifacts(): Promise<void> {
	await rm(generatedRoot, { recursive: true, force: true });
	await rm(symbolPagesRoot, { recursive: true, force: true });
	await mkdir(generatedExamplesDir, { recursive: true });
	await mkdir(generatedReferenceDir, { recursive: true });
	await mkdir(generatedApiDir, { recursive: true });
	await mkdir(symbolPagesRoot, { recursive: true });

	const [examples, publicApi, changelog] = await Promise.all([
		collectExamples(),
		collectPublicApiIndex(packageJsonPath),
		readFile(changelogPath, 'utf8'),
	]);
	const typeDoc = await collectTypeDocModel(packageJsonPath, publicApi);
	const symbolPages = collectSymbolPages(typeDoc.normalized, symbolPagesRoot);

	const docsHealth = await collectDocsHealth(examples.length, publicApi, symbolPages.length);
	const generatedReferenceSurfaces = buildReferenceSurfaces(symbolPages.length);

	await Promise.all([
		writeFile(
			generatedSiteDataPath,
			renderSiteData(examples, publicApi, generatedReferenceSurfaces, docsHealth, symbolPages),
		),
		writeFile(generatedExamplesIndexPath, renderExamplesIndex(examples)),
		writeFile(generatedChangelogPath, renderChangelog(changelog)),
		writeFile(generatedDocsHealthPath, renderDocsHealth(docsHealth)),
		writeFile(generatedApiIndexPath, `${JSON.stringify(publicApi, null, '\t')}\n`),
		writeFile(generatedApiPagePath, renderPublicApiIndex(publicApi)),
		writeFile(generatedTypeDocJsonPath, `${JSON.stringify(typeDoc.rawProject, null, '\t')}\n`),
		writeFile(
			generatedNormalizedTypeDocPath,
			`${JSON.stringify(typeDoc.normalized, null, '\t')}\n`,
		),
		...symbolPages.map(async (page) => {
			await mkdir(dirname(page.filePath), { recursive: true });
			await writeFile(page.filePath, page.content);
		}),
	]);
}

async function collectExamples(): Promise<readonly ExampleEntry[]> {
	const entries = await readdir(examplesRoot, { withFileTypes: true });
	const exampleFiles = entries
		.filter(
			(entry) =>
				entry.isFile() && extname(entry.name) === '.ts' && !entry.name.endsWith('.test.ts'),
		)
		.map((entry) => entry.name)
		.sort();

	const examples = await Promise.all(
		exampleFiles.map(async (fileName) => parseExample(join(examplesRoot, fileName))),
	);

	return examples;
}

async function parseExample(filePath: string): Promise<ExampleEntry> {
	const source = await readFile(filePath, 'utf8');
	const sourcePath = toRepoPath(filePath);
	const slug = basename(filePath, '.ts');
	const docLines = extractDocLines(source);
	const summary = firstNonEmpty(docLines) ?? titleFromSlug(slug);
	const demonstrates = extractLabeledValue(docLines, 'Demonstrates');
	const usage = extractUsage(docLines);

	return {
		slug,
		title: summary,
		summary,
		demonstrates,
		usage,
		sourcePath,
	};
}

function extractDocLines(source: string): readonly string[] {
	const match = /^#!.*\n\/\*\*([\s\S]*?)\*\//.exec(source) ?? /^\/\*\*([\s\S]*?)\*\//.exec(source);
	if (match === null) {
		return [];
	}
	const docBlock = match[1];
	if (docBlock === undefined) {
		return [];
	}

	return docBlock.split('\n').map((line) => line.replace(/^\s*\* ?/, '').trimEnd());
}

function extractUsage(lines: readonly string[]): readonly string[] {
	const usageIndex = lines.indexOf('Usage:');
	if (usageIndex === -1) {
		return [];
	}

	const usage: string[] = [];
	for (const line of lines.slice(usageIndex + 1)) {
		if (line.trim() === '') {
			if (usage.length > 0) {
				break;
			}
			continue;
		}

		usage.push(line.trim());
	}

	return usage;
}

function extractLabeledValue(lines: readonly string[], label: string): string | null {
	const prefix = `${label}:`;
	for (const line of lines) {
		if (line.startsWith(prefix)) {
			const value = line.slice(prefix.length).trim();
			return value === '' ? null : value;
		}
	}

	return null;
}

function firstNonEmpty(lines: readonly string[]): string | null {
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed !== '') {
			return trimmed;
		}
	}

	return null;
}

function titleFromSlug(slug: string): string {
	return slug
		.split('-')
		.map((part) => {
			const [firstChar, ...rest] = part;
			if (firstChar === undefined) {
				return part;
			}

			return `${firstChar.toUpperCase()}${rest.join('')}`;
		})
		.join(' ');
}

async function collectDocsHealth(
	exampleCount: number,
	publicApi: readonly PublicApiEntrypoint[],
	symbolPageCount: number,
): Promise<DocsHealthSnapshot> {
	const authoredPageCount = await countMarkdownFiles(
		docsRoot,
		(relativePath) =>
			!relativePath.startsWith('.generated/') && !relativePath.startsWith('.vitepress/'),
	);
	const generatedArtifactCount = 7 + symbolPageCount;

	return {
		authoredPageCount,
		generatedArtifactCount,
		exampleCount,
		publicEntrypointCount: publicApi.length,
		publicSymbolCount: countPublicApiSymbols(publicApi),
		symbolPageCount,
	};
}

async function countMarkdownFiles(
	dirPath: string,
	include: (relativePath: string) => boolean,
): Promise<number> {
	const entries = await readdir(dirPath, { withFileTypes: true });
	let count = 0;

	for (const entry of entries) {
		const fullPath = join(dirPath, entry.name);
		const repoPath = toRepoPath(fullPath);
		const docsRelativePath = relative(docsRoot, fullPath).replaceAll('\\', '/');

		if (entry.isDirectory()) {
			count += await countMarkdownFiles(fullPath, include);
			continue;
		}

		if (
			extname(entry.name) === '.md' &&
			include(docsRelativePath) &&
			repoPath !== 'docs/.generated/examples/index.md' &&
			repoPath !== 'docs/.generated/reference/changelog.md' &&
			repoPath !== 'docs/.generated/reference/docs-health.md' &&
			!repoPath.startsWith('docs/reference/symbols/')
		) {
			count += 1;
		}
	}

	return count;
}

function buildReferenceSurfaces(symbolPageCount: number): readonly GeneratedReferenceSurface[] {
	return [
		{
			id: 'generated-changelog',
			title: 'Generated Changelog Mirror',
			artifactPath: 'docs/.generated/reference/changelog.md',
			sourceInputs: ['CHANGELOG.md'],
			status: 'prepared',
			notes:
				'Foundation mirror only. Public navigation still lands on the authored wrapper until later tasks render the final surface.',
		},
		{
			id: 'generated-docs-health',
			title: 'Generated Docs Health Snapshot',
			artifactPath: 'docs/.generated/reference/docs-health.md',
			sourceInputs: ['docs/**/*.md', 'docs/.generated/**/*'],
			status: 'prepared',
			notes:
				'Current output is factual counts only so later health work can extend the same artifact path.',
		},
		{
			id: 'generated-api-index',
			title: 'Generated API Index',
			artifactPath: 'docs/.generated/api/index.md',
			sourceInputs: ['package.json', 'src/index.ts', 'src/runtime.ts', 'src/testkit.ts'],
			status: 'prepared',
			notes:
				'The generated markdown index is backed by `docs/.generated/api/public-exports.json`; full signature work now flows through the raw `typedoc.json` artifact and the normalized `typedoc-normalized.json` model beside it.',
		},
		{
			id: 'generated-typedoc-model',
			title: 'Normalized TypeDoc Model',
			artifactPath: 'docs/.generated/api/typedoc-normalized.json',
			sourceInputs: [
				'package.json',
				'tsconfig.json',
				'src/index.ts',
				'src/runtime.ts',
				'src/testkit.ts',
			],
			status: 'prepared',
			notes:
				'This DreamCLI-owned JSON model is derived from TypeDoc output so later symbol pages and schema-description enrichment do not depend on raw TypeDoc shape.',
		},
		{
			id: 'generated-symbol-pages',
			title: 'Rendered Symbol Pages',
			artifactPath: 'docs/reference/symbols/**/*.md',
			sourceInputs: ['docs/.generated/api/typedoc-normalized.json'],
			status: 'prepared',
			notes: `Public symbol reference pages rendered from the normalized model. Current count: ${symbolPageCount}.`,
		},
	];
}

function renderSiteData(
	examples: readonly ExampleEntry[],
	publicApi: readonly PublicApiEntrypoint[],
	referenceSurfaces: readonly GeneratedReferenceSurface[],
	docsHealth: DocsHealthSnapshot,
	symbolPages: readonly {
		id: string;
		routePath: string;
		entrypoint: string;
		name: string;
		summary: string | null;
	}[],
): string {
	const symbolPageIndex = symbolPages.map((page) => ({
		id: page.id,
		name: page.name,
		entrypoint: page.entrypoint,
		routePath: page.routePath,
		summary: page.summary,
	}));

	return [
		'/**',
		' * Generated docs metadata consumed by VitePress config and wrapper pages.',
		' *',
		' * @module',
		' */',
		'',
		`export const generatedExamples = ${JSON.stringify(examples, null, '\t')};`,
		'',
		`export const generatedReferenceSurfaces = ${JSON.stringify(referenceSurfaces, null, '\t')};`,
		'',
		`export const generatedPublicApi = ${JSON.stringify(publicApi, null, '\t')};`,
		'',
		`export const generatedSymbolPages = ${JSON.stringify(symbolPageIndex, null, '\t')};`,
		'',
		`export const docsHealthSnapshot = ${JSON.stringify(docsHealth, null, '\t')};`,
		'',
	].join('\n');
}

function renderExamplesIndex(examples: readonly ExampleEntry[]): string {
	const rows = examples.map((example) => {
		const demonstrates = example.demonstrates ?? 'n/a';
		return `| \`${example.slug}\` | ${escapeTable(example.summary)} | ${escapeTable(demonstrates)} | \`${example.sourcePath}\` |`;
	});

	return [
		GENERATED_HEADER,
		'',
		'# Generated Examples Inventory',
		'',
		'This inventory is rebuilt by `bun run docs:prepare` from `examples/*.ts`.',
		'',
		'| Example | Summary | Demonstrates | Source |',
		'| --- | --- | --- | --- |',
		...rows,
		'',
	].join('\n');
}

function renderChangelog(changelog: string): string {
	return [
		GENERATED_HEADER,
		'',
		'# Generated Changelog Mirror',
		'',
		'This file mirrors the repository changelog so later docs work can surface it without reading project-root files directly at render time.',
		'',
		changelog.trimEnd(),
		'',
	].join('\n');
}

function renderDocsHealth(docsHealth: DocsHealthSnapshot): string {
	return [
		GENERATED_HEADER,
		'',
		'# Generated Docs Health Snapshot',
		'',
		'This file is rebuilt by `bun run docs:prepare` and keeps the first factual metrics under a stable generated path.',
		'',
		'| Metric | Value |',
		'| --- | --- |',
		`| Authored markdown pages | ${docsHealth.authoredPageCount} |`,
		`| Generated artifacts | ${docsHealth.generatedArtifactCount} |`,
		`| Source-backed examples | ${docsHealth.exampleCount} |`,
		`| Public API entrypoints | ${docsHealth.publicEntrypointCount} |`,
		`| Public API symbols | ${docsHealth.publicSymbolCount} |`,
		`| Symbol reference pages | ${docsHealth.symbolPageCount} |`,
		'',
	].join('\n');
}

function escapeTable(value: string): string {
	return value.replaceAll('|', '\\|');
}

function toRepoPath(filePath: string): string {
	return relative(join(docsRoot, '..'), filePath).replaceAll('\\', '/');
}
