#!/usr/bin/env bun

/**
 * Rebuild generated docs foundation artifacts.
 *
 * @module
 */

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { basename, extname, join, relative } from 'node:path';

import {
	changelogPath,
	docsRoot,
	examplesRoot,
	generatedApiDir,
	generatedApiIndexPath,
	generatedChangelogPath,
	generatedDocsHealthPath,
	generatedExamplesDir,
	generatedExamplesIndexPath,
	generatedReferenceDir,
	generatedRoot,
	generatedSiteDataPath,
	packageJsonPath,
} from './shared/paths.ts';

interface ExampleEntry {
	slug: string;
	title: string;
	summary: string;
	demonstrates: string | null;
	usage: readonly string[];
	sourcePath: string;
}

interface PublicExportEntry {
	subpath: string;
	entrypoint: string;
}

interface GeneratedReferenceSurface {
	id: string;
	title: string;
	artifactPath: string;
	sourceInputs: readonly string[];
	status: 'prepared';
	notes: string;
}

interface DocsHealthSnapshot {
	authoredPageCount: number;
	generatedArtifactCount: number;
	exampleCount: number;
	publicExportCount: number;
}

const GENERATED_HEADER =
	'<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->';

await rebuildDocsArtifacts();

async function rebuildDocsArtifacts(): Promise<void> {
	await rm(generatedRoot, { recursive: true, force: true });
	await mkdir(generatedExamplesDir, { recursive: true });
	await mkdir(generatedReferenceDir, { recursive: true });
	await mkdir(generatedApiDir, { recursive: true });

	const [examples, publicExports, changelog] = await Promise.all([
		collectExamples(),
		collectPublicExports(),
		readFile(changelogPath, 'utf8'),
	]);

	const docsHealth = await collectDocsHealth(examples.length, publicExports.length);
	const generatedReferenceSurfaces = buildReferenceSurfaces();

	await Promise.all([
		writeFile(
			generatedSiteDataPath,
			renderSiteData(examples, publicExports, generatedReferenceSurfaces, docsHealth),
		),
		writeFile(generatedExamplesIndexPath, renderExamplesIndex(examples)),
		writeFile(generatedChangelogPath, renderChangelog(changelog)),
		writeFile(generatedDocsHealthPath, renderDocsHealth(docsHealth)),
		writeFile(generatedApiIndexPath, `${JSON.stringify(publicExports, null, '\t')}\n`),
	]);
}

async function collectExamples(): Promise<readonly ExampleEntry[]> {
	const entries = await readdir(examplesRoot, { withFileTypes: true });
	const exampleFiles = entries
		.filter(
			(entry) =>
				entry.isFile() && extname(entry.name) === '.ts' && !entry.name.endsWith('.test.ts'),
		)
		.map((entry) => entry.name)
		.sort();

	const examples = await Promise.all(
		exampleFiles.map(async (fileName) => parseExample(join(examplesRoot, fileName))),
	);

	return examples;
}

async function parseExample(filePath: string): Promise<ExampleEntry> {
	const source = await readFile(filePath, 'utf8');
	const sourcePath = toRepoPath(filePath);
	const slug = basename(filePath, '.ts');
	const docLines = extractDocLines(source);
	const summary = firstNonEmpty(docLines) ?? titleFromSlug(slug);
	const demonstrates = extractLabeledValue(docLines, 'Demonstrates');
	const usage = extractUsage(docLines);

	return {
		slug,
		title: summary,
		summary,
		demonstrates,
		usage,
		sourcePath,
	};
}

function extractDocLines(source: string): readonly string[] {
	const match = /^#!.*\n\/\*\*([\s\S]*?)\*\//.exec(source) ?? /^\/\*\*([\s\S]*?)\*\//.exec(source);
	if (match === null) {
		return [];
	}
	const docBlock = match[1];
	if (docBlock === undefined) {
		return [];
	}

	return docBlock.split('\n').map((line) => line.replace(/^\s*\* ?/, '').trimEnd());
}

function extractUsage(lines: readonly string[]): readonly string[] {
	const usageIndex = lines.indexOf('Usage:');
	if (usageIndex === -1) {
		return [];
	}

	const usage: string[] = [];
	for (const line of lines.slice(usageIndex + 1)) {
		if (line.trim() === '') {
			if (usage.length > 0) {
				break;
			}
			continue;
		}

		usage.push(line.trim());
	}

	return usage;
}

function extractLabeledValue(lines: readonly string[], label: string): string | null {
	const prefix = `${label}:`;
	for (const line of lines) {
		if (line.startsWith(prefix)) {
			const value = line.slice(prefix.length).trim();
			return value === '' ? null : value;
		}
	}

	return null;
}

function firstNonEmpty(lines: readonly string[]): string | null {
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed !== '') {
			return trimmed;
		}
	}

	return null;
}

function titleFromSlug(slug: string): string {
	return slug
		.split('-')
		.map((part) => {
			const [firstChar, ...rest] = part;
			if (firstChar === undefined) {
				return part;
			}

			return `${firstChar.toUpperCase()}${rest.join('')}`;
		})
		.join(' ');
}

async function collectPublicExports(): Promise<readonly PublicExportEntry[]> {
	const packageJson = await readJsonFile(packageJsonPath);
	const exportsField = packageJson.exports;
	if (!isRecord(exportsField)) {
		return [];
	}

	return Object.keys(exportsField)
		.filter((subpath) => subpath !== './package.json')
		.map((subpath) => ({
			subpath,
			entrypoint: subpath === '.' ? 'dreamcli' : `dreamcli/${subpath.slice(2)}`,
		}))
		.sort((left, right) => left.entrypoint.localeCompare(right.entrypoint));
}

async function collectDocsHealth(
	exampleCount: number,
	publicExportCount: number,
): Promise<DocsHealthSnapshot> {
	const authoredPageCount = await countMarkdownFiles(
		docsRoot,
		(relativePath) =>
			!relativePath.startsWith('.generated/') && !relativePath.startsWith('.vitepress/'),
	);
	const generatedArtifactCount = 4;

	return {
		authoredPageCount,
		generatedArtifactCount,
		exampleCount,
		publicExportCount,
	};
}

async function countMarkdownFiles(
	dirPath: string,
	include: (relativePath: string) => boolean,
): Promise<number> {
	const entries = await readdir(dirPath, { withFileTypes: true });
	let count = 0;

	for (const entry of entries) {
		const fullPath = join(dirPath, entry.name);
		const repoPath = toRepoPath(fullPath);
		const docsRelativePath = relative(docsRoot, fullPath).replaceAll('\\', '/');

		if (entry.isDirectory()) {
			count += await countMarkdownFiles(fullPath, include);
			continue;
		}

		if (
			extname(entry.name) === '.md' &&
			include(docsRelativePath) &&
			repoPath !== 'docs/.generated/examples/index.md' &&
			repoPath !== 'docs/.generated/reference/changelog.md' &&
			repoPath !== 'docs/.generated/reference/docs-health.md'
		) {
			count += 1;
		}
	}

	return count;
}

function buildReferenceSurfaces(): readonly GeneratedReferenceSurface[] {
	return [
		{
			id: 'generated-changelog',
			title: 'Generated Changelog Mirror',
			artifactPath: 'docs/.generated/reference/changelog.md',
			sourceInputs: ['CHANGELOG.md'],
			status: 'prepared',
			notes:
				'Foundation mirror only. Public navigation still lands on the authored wrapper until later tasks render the final surface.',
		},
		{
			id: 'generated-docs-health',
			title: 'Generated Docs Health Snapshot',
			artifactPath: 'docs/.generated/reference/docs-health.md',
			sourceInputs: ['docs/**/*.md', 'docs/.generated/**/*'],
			status: 'prepared',
			notes:
				'Current output is factual counts only so later health work can extend the same artifact path.',
		},
		{
			id: 'generated-api-index',
			title: 'Generated Public Export Inventory',
			artifactPath: 'docs/.generated/api/public-exports.json',
			sourceInputs: ['package.json'],
			status: 'prepared',
			notes:
				'The foundation emits a stable export manifest before later API-index and TypeDoc normalization tasks add richer rendering.',
		},
	];
}

function renderSiteData(
	examples: readonly ExampleEntry[],
	publicExports: readonly PublicExportEntry[],
	referenceSurfaces: readonly GeneratedReferenceSurface[],
	docsHealth: DocsHealthSnapshot,
): string {
	return [
		'/**',
		' * Generated docs metadata consumed by VitePress config and wrapper pages.',
		' *',
		' * @module',
		' */',
		'',
		`export const generatedExamples = ${JSON.stringify(examples, null, '\t')};`,
		'',
		`export const generatedReferenceSurfaces = ${JSON.stringify(referenceSurfaces, null, '\t')};`,
		'',
		`export const generatedPublicExports = ${JSON.stringify(publicExports, null, '\t')};`,
		'',
		`export const docsHealthSnapshot = ${JSON.stringify(docsHealth, null, '\t')};`,
		'',
	].join('\n');
}

function renderExamplesIndex(examples: readonly ExampleEntry[]): string {
	const rows = examples.map((example) => {
		const demonstrates = example.demonstrates ?? 'n/a';
		return `| \`${example.slug}\` | ${escapeTable(example.summary)} | ${escapeTable(demonstrates)} | \`${example.sourcePath}\` |`;
	});

	return [
		GENERATED_HEADER,
		'',
		'# Generated Examples Inventory',
		'',
		'This inventory is rebuilt by `bun run docs:prepare` from `examples/*.ts`.',
		'',
		'| Example | Summary | Demonstrates | Source |',
		'| --- | --- | --- | --- |',
		...rows,
		'',
	].join('\n');
}

function renderChangelog(changelog: string): string {
	return [
		GENERATED_HEADER,
		'',
		'# Generated Changelog Mirror',
		'',
		'This file mirrors the repository changelog so later docs work can surface it without reading project-root files directly at render time.',
		'',
		changelog.trimEnd(),
		'',
	].join('\n');
}

function renderDocsHealth(docsHealth: DocsHealthSnapshot): string {
	return [
		GENERATED_HEADER,
		'',
		'# Generated Docs Health Snapshot',
		'',
		'This file is rebuilt by `bun run docs:prepare` and keeps the first factual metrics under a stable generated path.',
		'',
		'| Metric | Value |',
		'| --- | --- |',
		`| Authored markdown pages | ${docsHealth.authoredPageCount} |`,
		`| Generated artifacts | ${docsHealth.generatedArtifactCount} |`,
		`| Source-backed examples | ${docsHealth.exampleCount} |`,
		`| Public export entrypoints | ${docsHealth.publicExportCount} |`,
		'',
	].join('\n');
}

function escapeTable(value: string): string {
	return value.replaceAll('|', '\\|');
}

async function readJsonFile(filePath: string): Promise<Record<string, unknown>> {
	const raw = JSON.parse(await readFile(filePath, 'utf8'));
	if (!isRecord(raw)) {
		throw new Error(`Expected object JSON at ${toRepoPath(filePath)}`);
	}

	return raw;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null;
}

function toRepoPath(filePath: string): string {
	return relative(join(docsRoot, '..'), filePath).replaceAll('\\', '/');
}
