// Shared ambient symbols for docs Twoslash snippets.
// Keep this permissive: reference pages contain isolated signatures, not runnable programs.

type DocsMain = typeof import('@kjanat/dreamcli');
type DocsRuntime = typeof import('@kjanat/dreamcli/runtime');
type DocsTestkit = typeof import('@kjanat/dreamcli/testkit');

type DocsCommand = ReturnType<DocsMain['command']>;
type DocsCli = ReturnType<DocsMain['cli']>;
type DocsMiddleware = import('@kjanat/dreamcli').Middleware<
  Record<string, unknown>
>;

interface DocsUser {
  id: string;
  name: string;
}

type ActionHandler = any;
type ActionParams = any;
type ActivityEvent = any;
type AnyCommandBuilder = any;
type ArgBuilder = any;
type ArgConfig = any;
type ArgFactory = any;
type ArgKind = any;
type ArgParseFn = any;
type ArgPresence = any;
type ArgSchema = any;
type BeforeParseParams = any;
type CapturedOutput = any;
type CLIBuilder = any;
type CLIError = any;
type CLIErrorJSON = any;
type CLIErrorOptions = any;
type CLIOptions = any;
type CLIPlugin = any;
type CLIPluginHooks = any;
type CLIRunOptions = any;
type CLISchema = any;
type CommandArgEntry = any;
type CommandBuilder = any;
type CommandConfig = any;
type CommandExample = any;
type CommandMeta = any;
type CommandSchema = any;
type CompletionOptions = any;
type ConfigAdapter = any;
type ConfigDiscoveryOptions = any;
type ConfigDiscoveryResult = any;
type ConfigFound = any;
type ConfigNotFound = any;
type ConfigSettings = any;
type ConfirmPromptConfig = any;
type DeprecationWarning = any;
type DeriveHandler = any;
type DeriveParams = any;
type ErrorCode = any;
type ExitError = any;
type Fallback = any;
type FlagBuilder = any;
type FlagConfig = any;
type FlagFactory = any;
type FlagKind = any;
type FlagParseFn = any;
type FlagPresence = any;
type FlagSchema = any;
type FormatLoader = any;
type HelpOptions = any;
type InferArg = any;
type InferArgs = any;
type InferFlag = any;
type InferFlags = any;
type InputPromptConfig = any;
type InteractiveParams = any;
type InteractiveResolver = any;
type InteractiveResult = any;
type JsonSchemaOptions = any;
type Middleware = any;
type MiddlewareHandler = any;
type MiddlewareImpl = any;
type MiddlewareParams = any;
type MultiselectPromptConfig = any;
type Out = any;
type OutputOptions = any;
type PackageJsonAdapter = any;
type PackageJsonData = any;
type PackageJsonSettings = any;
type ParseError = any;
type ParseErrorCode = any;
type ParseErrorOptions = any;
type ParseResult = any;
type PluginCommandContext = any;
type ProgressHandle = any;
type ProgressOptions = any;
type PromptConfig = any;
type PromptConfigBase = any;
type PromptEngine = any;
type PromptKind = any;
type PromptResult = any;
type ReadFn = any;
type ResolveOptions = any;
type ResolveResult = any;
type ResolvedArgValue = any;
type ResolvedCommandParams = any;
type ResolvedMultiselectPromptConfig = any;
type ResolvedPromptConfig = any;
type ResolvedSelectPromptConfig = any;
type ResolvedValue = any;
type RunOptions = any;
type RunResult = any;
type Runtime = any;
type RuntimeAdapter = any;
type SelectChoice = any;
type SelectPromptConfig = any;
type Shell = any;
type SpinnerHandle = any;
type SpinnerOptions = any;
type TableColumn = any;
type TableFormat = any;
type TableOptions = any;
type TableStream = any;
type TestAdapterOptions = any;
type TestAnswer = any;
type TestPrompterOptions = any;
type Token = any;
type ValidationError = any;
type ValidationErrorCode = any;
type ValidationErrorOptions = any;
type Verbosity = any;
type WithArgPresence = any;
type WithPresence = any;
type WithVariadic = any;
type WriteFn = any;

declare const ArgBuilder: DocsMain['ArgBuilder'];
declare const CLIBuilder: DocsMain['CLIBuilder'];
declare const CLIError: DocsMain['CLIError'];
declare const CommandBuilder: DocsMain['CommandBuilder'];
declare const FlagBuilder: DocsMain['FlagBuilder'];
declare const ParseError: DocsMain['ParseError'];
declare const ValidationError: DocsMain['ValidationError'];
declare const arg: DocsMain['arg'];
declare const buildConfigSearchPaths: DocsMain['buildConfigSearchPaths'];
declare const cli: DocsMain['cli'];
declare const command: DocsMain['command'];
declare const configFormat: DocsMain['configFormat'];
declare const createArgSchema: DocsMain['createArgSchema'];
declare const createOutput: DocsMain['createOutput'];
declare const createSchema: DocsMain['createSchema'];
declare const createTerminalPrompter: DocsMain['createTerminalPrompter'];
declare const definitionMetaSchema: DocsMain['definitionMetaSchema'];
declare const discoverConfig: DocsMain['discoverConfig'];
declare const discoverPackageJson: DocsMain['discoverPackageJson'];
declare const flag: DocsMain['flag'];
declare const formatHelp: DocsMain['formatHelp'];
declare const generateBashCompletion: DocsMain['generateBashCompletion'];
declare const generateCompletion: DocsMain['generateCompletion'];
declare const generateInputSchema: DocsMain['generateInputSchema'];
declare const generateSchema: DocsMain['generateSchema'];
declare const generateZshCompletion: DocsMain['generateZshCompletion'];
declare const group: DocsMain['group'];
declare const inferCliName: DocsMain['inferCliName'];
declare const isCLIError: DocsMain['isCLIError'];
declare const isParseError: DocsMain['isParseError'];
declare const isValidationError: DocsMain['isValidationError'];
declare const middleware: DocsMain['middleware'];
declare const parse: DocsMain['parse'];
declare const plugin: DocsMain['plugin'];
declare const resolve: DocsMain['resolve'];
declare const resolvePromptConfig: DocsMain['resolvePromptConfig'];
declare const SHELLS: DocsMain['SHELLS'];
declare const tokenize: DocsMain['tokenize'];
declare const createAdapter: DocsRuntime['createAdapter'];
declare const createBunAdapter: DocsRuntime['createBunAdapter'];
declare const createDenoAdapter: DocsRuntime['createDenoAdapter'];
declare const createNodeAdapter: DocsRuntime['createNodeAdapter'];
declare const detectRuntime: DocsRuntime['detectRuntime'];
declare const ExitError: DocsRuntime['ExitError'];
declare const RUNTIMES: DocsRuntime['RUNTIMES'];
declare const createCaptureOutput: DocsTestkit['createCaptureOutput'];
declare const createTestAdapter: DocsTestkit['createTestAdapter'];
declare const createTestPrompter: DocsTestkit['createTestPrompter'];
declare const PROMPT_CANCEL: DocsTestkit['PROMPT_CANCEL'];
declare const runCommand: DocsTestkit['runCommand'];

declare const auth: DocsCommand;
declare const authLogin: DocsCommand;
declare const authStatus: DocsCommand;
declare const authedCommand: DocsMain['command'];
declare const cmd: DocsCommand;
declare const deploy: DocsCommand &
  ((target?: string, flags?: unknown) => Promise<unknown>);
declare const errorBoundary: DocsMiddleware;
declare const getAuthenticatedUser: () => Promise<DocsUser | undefined>;
declare const getUser: () => Promise<DocsUser | undefined>;
declare const greet: DocsCommand;
declare const issue: DocsCommand;
declare const issueLabelChoices: readonly { value: string; label?: string }[];
declare const issueList: DocsCommand;
declare const issueTriage: DocsCommand;
declare const mainCmd: DocsCommand;
declare const mainCommand: DocsCommand;
declare const migrate: DocsCommand;
declare const migrateCmd: DocsCommand;
declare const myCli: DocsCli & { run(): Promise<void> };
declare const noAuth: DocsCommand;
declare const other: DocsCommand;
declare const out: import('@kjanat/dreamcli').Out;
declare const pr: DocsCommand;
declare const prCreate: DocsCommand;
declare const prList: DocsCommand;
declare const prView: DocsCommand;
declare const region: string;
declare const requireAuth: (token: string | undefined) => { token: string };
declare const result: { error: { code: string } };
declare const rows: readonly { name: string; status: string; uptime: number }[];
declare const seed: DocsCommand;
declare const seedCmd: DocsCommand;
declare const serve: DocsCommand;
declare const status: DocsCommand;
declare const target: string;
declare const tick: () => Promise<void>;
declare const timing: DocsMiddleware;
declare const tokenFlag: (
  description?: string,
) => ReturnType<DocsMain['flag']['string']>;
declare const trace: DocsMiddleware;
declare const tracePlugin: import('@kjanat/dreamcli').CLIPlugin;
declare const withAuth: DocsCommand;
declare const writeFileSync: (path: string, data: string) => void;

// Internal types surfaced in reference/contract pages
type CommandExecutionPlan = any;
type ErasedCommand = any;
type OutputPolicy = any;
type DispatchResult = any;

// Test assertion ambient — vitest's expect() for docs snippets
declare function expect(value: unknown): {
  toBe(expected: unknown): void;
  toEqual(expected: unknown): void;
  toContain(expected: unknown): void;
  toContainEqual(expected: unknown): void;
  toBeInstanceOf(expected: unknown): void;
  toBeUndefined(): void;
  not: {
    toBe(expected: unknown): void;
    toEqual(expected: unknown): void;
    toContain(expected: unknown): void;
    toContainEqual(expected: unknown): void;
    toBeInstanceOf(expected: unknown): void;
    toBeUndefined(): void;
  };
};
declare namespace expect {
  function objectContaining(expected: Record<string, unknown>): unknown;
}
