/**
 * Public API inventory helpers for docs generation.
 *
 * @module
 */

import { readFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve } from 'node:path';

import ts from 'typescript';

import { toSymbolPageRoute } from './symbol-pages.ts';

export type PublicApiSymbolKind =
	| 'asset'
	| 'class'
	| 'constant'
	| 'enum'
	| 'function'
	| 'interface'
	| 'type'
	| 'unknown';

export interface PublicApiSymbol {
	name: string;
	kind: PublicApiSymbolKind;
	sourcePath: string;
}

export interface PublicApiKindGroup {
	kind: PublicApiSymbolKind;
	title: string;
	symbols: readonly PublicApiSymbol[];
}

export interface PublicApiEntrypoint {
	subpath: string;
	entrypoint: string;
	sourcePath: string;
	symbolCount: number;
	kindGroups: readonly PublicApiKindGroup[];
}

const KIND_ORDER: readonly PublicApiSymbolKind[] = [
	'function',
	'class',
	'constant',
	'interface',
	'type',
	'enum',
	'asset',
	'unknown',
];

const KIND_TITLES: Readonly<Record<PublicApiSymbolKind, string>> = {
	asset: 'Assets',
	class: 'Classes',
	constant: 'Constants',
	enum: 'Enums',
	function: 'Functions',
	interface: 'Interfaces',
	type: 'Types',
	unknown: 'Other Exports',
};

export async function collectPublicApiIndex(
	packageJsonFilePath: string,
): Promise<readonly PublicApiEntrypoint[]> {
	const rootDir = dirname(packageJsonFilePath);
	const packageJson = await readJsonFile(packageJsonFilePath);
	const exportsField = packageJson.exports;
	if (!isRecord(exportsField)) {
		return [];
	}

	const resolvedEntrypoints = Object.entries(exportsField)
		.filter(([subpath]) => subpath !== './package.json')
		.map(([subpath, value]) => {
			const targetPath = resolvePublicEntrypointTarget(rootDir, value);
			if (targetPath === null) {
				return null;
			}

			return {
				subpath,
				targetPath,
			};
		})
		.filter((entrypoint) => entrypoint !== null);
	const program = createApiProgram(
		resolvedEntrypoints
			.map((entrypoint) => entrypoint.targetPath)
			.filter((entrypoint) => extname(entrypoint) === '.ts'),
	);
	const checker = program.getTypeChecker();

	return resolvedEntrypoints
		.map(({ subpath, targetPath }) => {
			const entrypoint = toEntrypointName(subpath);
			const sourcePath = toRepoPath(rootDir, targetPath);
			const symbols =
				extname(targetPath) === '.json'
					? [
							{
								name: subpath === '.' ? entrypoint : subpath.slice(2),
								kind: 'asset' as const,
								sourcePath,
							},
						]
					: collectEntrypointSymbols(targetPath, rootDir, checker, program);

			return {
				subpath,
				entrypoint,
				sourcePath,
				symbolCount: symbols.length,
				kindGroups: buildKindGroups(symbols),
			} satisfies PublicApiEntrypoint;
		})
		.sort((left, right) => left.entrypoint.localeCompare(right.entrypoint));
}

export function countPublicApiSymbols(entrypoints: readonly PublicApiEntrypoint[]): number {
	return entrypoints.reduce((count, entrypoint) => count + entrypoint.symbolCount, 0);
}

export function renderPublicApiIndex(entrypoints: readonly PublicApiEntrypoint[]): string {
	const sections = entrypoints.flatMap((entrypoint) => {
		const caseInsensitiveCollisions = collectEntrypointCaseInsensitiveCollisions(entrypoint);
		const groupSections = entrypoint.kindGroups.flatMap((group) => [
			`### ${group.title} (${group.symbols.length})`,
			'',
			'| Symbol | Source |',
			'| --- | --- |',
			...group.symbols.map(
				(symbol) =>
					`| ${renderSymbolCell(entrypoint.entrypoint, symbol, caseInsensitiveCollisions)} | \`${escapeTable(symbol.sourcePath)}\` |`,
			),
			'',
		]);

		return [
			`## \`${entrypoint.entrypoint}\``,
			'',
			`- Subpath: \`${entrypoint.subpath}\``,
			`- Source entrypoint: \`${entrypoint.sourcePath}\``,
			`- Public symbols: ${entrypoint.symbolCount}`,
			'',
			...groupSections,
		];
	});

	return [
		'<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->',
		'',
		'# Generated API Index',
		'',
		'This inventory is rebuilt by `bun run docs:prepare` from the public entrypoints declared in `package.json`.',
		'',
		`- Public entrypoints: ${entrypoints.length}`,
		`- Public symbols: ${countPublicApiSymbols(entrypoints)}`,
		'',
		...sections,
	].join('\n');
}

function collectEntrypointSymbols(
	filePath: string,
	rootDir: string,
	checker: ts.TypeChecker,
	program: ts.Program,
): readonly PublicApiSymbol[] {
	const sourceFile = program.getSourceFile(filePath);
	if (sourceFile === undefined) {
		throw new Error(`Missing source file for API inventory: ${filePath}`);
	}

	const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
	if (moduleSymbol === undefined) {
		throw new Error(`Missing module symbol for API inventory: ${filePath}`);
	}

	return checker
		.getExportsOfModule(moduleSymbol)
		.map((symbol) => {
			const resolvedSymbol = resolveExportSymbol(symbol, checker);
			const declaration = pickDeclaration(resolvedSymbol);
			return {
				name: symbol.name,
				kind: classifyExportKind(resolvedSymbol, declaration),
				sourcePath:
					declaration === undefined
						? toRepoPath(rootDir, filePath)
						: toRepoPath(rootDir, declaration.getSourceFile().fileName),
			};
		})
		.sort(comparePublicApiSymbols);
}

function buildKindGroups(symbols: readonly PublicApiSymbol[]): readonly PublicApiKindGroup[] {
	return KIND_ORDER.flatMap((kind) => {
		const entries = symbols.filter((symbol) => symbol.kind === kind);
		if (entries.length === 0) {
			return [];
		}

		return [
			{
				kind,
				title: KIND_TITLES[kind],
				symbols: entries,
			} satisfies PublicApiKindGroup,
		];
	});
}

function comparePublicApiSymbols(left: PublicApiSymbol, right: PublicApiSymbol): number {
	const kindDelta = KIND_ORDER.indexOf(left.kind) - KIND_ORDER.indexOf(right.kind);
	if (kindDelta !== 0) {
		return kindDelta;
	}

	return left.name.localeCompare(right.name);
}

function resolvePublicEntrypointTarget(rootDir: string, value: unknown): string | null {
	if (typeof value === 'string') {
		return resolve(rootDir, value);
	}

	if (!isRecord(value)) {
		return null;
	}

	for (const key of ['bun', 'deno', 'default', 'import']) {
		const candidate = value[key];
		if (
			typeof candidate === 'string' &&
			(candidate.endsWith('.ts') || candidate.endsWith('.json'))
		) {
			return resolve(rootDir, candidate);
		}
	}

	return null;
}

function createApiProgram(entrypoints: readonly string[]): ts.Program {
	return ts.createProgram({
		rootNames: entrypoints,
		options: {
			allowImportingTsExtensions: true,
			esModuleInterop: true,
			module: ts.ModuleKind.Preserve,
			moduleResolution: ts.ModuleResolutionKind.Bundler,
			target: ts.ScriptTarget.ESNext,
		},
	});
}

function resolveExportSymbol(symbol: ts.Symbol, checker: ts.TypeChecker): ts.Symbol {
	return symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
}

function pickDeclaration(symbol: ts.Symbol): ts.Declaration | undefined {
	const declarations = symbol.getDeclarations();
	if (declarations === undefined) {
		return undefined;
	}

	for (const declaration of declarations) {
		if (!ts.isImportSpecifier(declaration) && !ts.isExportSpecifier(declaration)) {
			return declaration;
		}
	}

	return declarations[0];
}

function classifyExportKind(
	symbol: ts.Symbol,
	declaration: ts.Declaration | undefined,
): PublicApiSymbolKind {
	if (declaration !== undefined) {
		if (ts.isFunctionDeclaration(declaration)) {
			return 'function';
		}

		if (ts.isClassDeclaration(declaration)) {
			return 'class';
		}

		if (ts.isInterfaceDeclaration(declaration)) {
			return 'interface';
		}

		if (ts.isTypeAliasDeclaration(declaration)) {
			return 'type';
		}

		if (ts.isEnumDeclaration(declaration)) {
			return 'enum';
		}

		if (
			ts.isVariableDeclaration(declaration) ||
			ts.isVariableStatement(declaration) ||
			ts.isPropertyDeclaration(declaration)
		) {
			return 'constant';
		}
	}

	if (symbol.flags & ts.SymbolFlags.Function) {
		return 'function';
	}

	if (symbol.flags & ts.SymbolFlags.Class) {
		return 'class';
	}

	if (symbol.flags & ts.SymbolFlags.Interface) {
		return 'interface';
	}

	if (symbol.flags & ts.SymbolFlags.TypeAlias) {
		return 'type';
	}

	if (symbol.flags & ts.SymbolFlags.Enum) {
		return 'enum';
	}

	if (
		symbol.flags & ts.SymbolFlags.BlockScopedVariable ||
		symbol.flags & ts.SymbolFlags.Variable ||
		symbol.flags & ts.SymbolFlags.ConstEnum
	) {
		return 'constant';
	}

	return 'unknown';
}

function toEntrypointName(subpath: string): string {
	return subpath === '.' ? 'dreamcli' : `dreamcli/${subpath.slice(2)}`;
}

function escapeTable(value: string): string {
	return value.replaceAll('|', '\\|');
}

function renderSymbolCell(
	entrypoint: string,
	symbol: PublicApiSymbol,
	caseInsensitiveCollisions: ReadonlySet<string>,
): string {
	if (symbol.kind === 'asset') {
		return `\`${symbol.name}\``;
	}

	const href = toSymbolPageRoute(entrypoint, symbol.name, {
		publicKind: symbol.kind,
		hasCaseInsensitiveCollision: caseInsensitiveCollisions.has(
			`${entrypoint}:${symbol.name.toLowerCase()}`,
		),
	});
	return `[\`${symbol.name}\`](${href})`;
}

function collectEntrypointCaseInsensitiveCollisions(
	entrypoint: PublicApiEntrypoint,
): ReadonlySet<string> {
	const counts = new Map<string, number>();
	for (const group of entrypoint.kindGroups) {
		for (const symbol of group.symbols) {
			const key = `${entrypoint.entrypoint}:${symbol.name.toLowerCase()}`;
			counts.set(key, (counts.get(key) ?? 0) + 1);
		}
	}

	return new Set(
		Array.from(counts.entries())
			.filter(([, count]) => count > 1)
			.map(([key]) => key),
	);
}

async function readJsonFile(filePath: string): Promise<Record<string, unknown>> {
	const raw = JSON.parse(await readFile(filePath, 'utf8'));
	if (!isRecord(raw)) {
		throw new Error(`Expected object JSON at ${filePath}`);
	}

	return raw;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null;
}

function toRepoPath(rootDir: string, filePath: string): string {
	return relative(rootDir, filePath).replaceAll('\\', '/');
}
