/**
 * Example docs generation helpers.
 *
 * @module
 */

import { readdir, readFile } from 'node:fs/promises';
import { basename, extname, join, relative } from 'node:path';

import { toSymbolPageRoute } from './symbol-pages.ts';

export interface ExampleRelatedLink {
	label: string;
	href: string;
}

export interface ExampleEntry {
	slug: string;
	title: string;
	summary: string;
	demonstrates: string | null;
	usage: readonly string[];
	sourcePath: string;
	routePath: string;
	sourceUrl: string;
	sourceCode: string;
	relatedLinks: readonly ExampleRelatedLink[];
}

const GENERATED_HEADER =
	'<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->';

const REPO_BLOB_BASE_URL = 'https://github.com/kjanat/dreamcli/blob/master';

export async function collectExamples(
	examplesRoot: string,
	repoRoot: string,
): Promise<readonly ExampleEntry[]> {
	const entries = await readdir(examplesRoot, { withFileTypes: true });
	const exampleFiles = entries
		.filter(
			(entry) =>
				entry.isFile() && extname(entry.name) === '.ts' && !entry.name.endsWith('.test.ts'),
		)
		.map((entry) => entry.name)
		.sort();

	return Promise.all(
		exampleFiles.map(async (fileName) => parseExample(join(examplesRoot, fileName), repoRoot)),
	);
}

export function renderExamplesIndex(examples: readonly ExampleEntry[]): string {
	const rows = examples.map((example) => {
		const demonstrates = example.demonstrates ?? 'n/a';
		return `| [\`${example.slug}\`](${example.routePath}) | ${escapeTable(example.summary)} | ${escapeTable(demonstrates)} | \`${example.sourcePath}\` |`;
	});

	return [
		GENERATED_HEADER,
		'',
		'# Generated Examples Inventory',
		'',
		'This inventory is rebuilt by `bun run docs:prepare` from `examples/*.ts`.',
		'',
		'| Example | Summary | Demonstrates | Source |',
		'| --- | --- | --- | --- |',
		...rows,
		'',
	].join('\n');
}

export function renderExamplePage(example: ExampleEntry): string {
	const usageSection =
		example.usage.length === 0
			? ['No usage snippets declared in the example docblock.', '']
			: ['```bash', ...example.usage, '```', ''];
	const relatedLinks =
		example.relatedLinks.length === 0
			? ['- [Examples overview](/examples/)', '- [API overview](/reference/api)']
			: example.relatedLinks.map((link) => `- [${link.label}](${link.href})`);

	return [
		GENERATED_HEADER,
		'',
		`# ${example.title}`,
		'',
		example.summary,
		'',
		`- Source: [\`${example.sourcePath}\`](${example.sourceUrl})`,
		...(example.demonstrates === null ? [] : [`- Demonstrates: ${example.demonstrates}`]),
		'',
		'## Usage',
		'',
		...usageSection,
		'## Related Links',
		'',
		...relatedLinks,
		'',
		'## Source',
		'',
		'```ts',
		example.sourceCode.trimEnd(),
		'```',
		'',
	].join('\n');
}

async function parseExample(filePath: string, repoRoot: string): Promise<ExampleEntry> {
	const source = await readFile(filePath, 'utf8');
	const sourcePath = toRepoPath(filePath, repoRoot);
	const slug = basename(filePath, '.ts');
	const docLines = extractDocLines(source);
	const summary = firstNonEmpty(docLines) ?? titleFromSlug(slug);
	const demonstrates = extractLabeledValue(docLines, 'Demonstrates');
	const usage = extractUsage(docLines);

	return {
		slug,
		title: summary,
		summary,
		demonstrates,
		usage,
		sourcePath,
		routePath: `/examples/${slug}`,
		sourceUrl: `${REPO_BLOB_BASE_URL}/${sourcePath}`,
		sourceCode: source,
		relatedLinks: collectRelatedLinks(source),
	};
}

function collectRelatedLinks(source: string): readonly ExampleRelatedLink[] {
	const symbolLinks = new Map<string, ExampleRelatedLink>();
	for (const match of source.matchAll(/import\s*\{([^}]+)\}\s*from\s*'([^']+)'/g)) {
		const importList = match[1];
		const moduleName = match[2];
		if (
			importList === undefined ||
			moduleName === undefined ||
			!moduleName.startsWith('dreamcli')
		) {
			continue;
		}

		for (const entry of importList.split(',')) {
			const importedName = normalizeImportedName(entry);
			if (importedName === null) {
				continue;
			}
			symbolLinks.set(`${moduleName}:${importedName}`, {
				label: `\`${importedName}\``,
				href: toSymbolPageRoute(moduleName, importedName),
			});
		}
	}

	return [
		{ label: 'Examples overview', href: '/examples/' },
		{ label: 'API overview', href: '/reference/api' },
		...Array.from(symbolLinks.values()).sort((left, right) =>
			left.label.localeCompare(right.label),
		),
	];
}

function normalizeImportedName(entry: string): string | null {
	const trimmed = entry.trim();
	if (trimmed === '') {
		return null;
	}
	const withoutType = trimmed.startsWith('type ') ? trimmed.slice(5).trim() : trimmed;
	const importedName = withoutType.split(' as ')[0]?.trim();
	return importedName === undefined || importedName === '' ? null : importedName;
}

function extractDocLines(source: string): readonly string[] {
	const match = /^#!.*\n\/\*\*([\s\S]*?)\*\//.exec(source) ?? /^\/\*\*([\s\S]*?)\*\//.exec(source);
	if (match === null) {
		return [];
	}
	const docBlock = match[1];
	if (docBlock === undefined) {
		return [];
	}

	return docBlock.split('\n').map((line) => line.replace(/^\s*\* ?/, '').trimEnd());
}

function extractUsage(lines: readonly string[]): readonly string[] {
	const usageIndex = lines.indexOf('Usage:');
	if (usageIndex === -1) {
		return [];
	}

	const usage: string[] = [];
	for (const line of lines.slice(usageIndex + 1)) {
		if (line.trim() === '') {
			if (usage.length > 0) {
				break;
			}
			continue;
		}

		usage.push(line.trim());
	}

	return usage;
}

function extractLabeledValue(lines: readonly string[], label: string): string | null {
	const prefix = `${label}:`;
	for (const line of lines) {
		if (line.startsWith(prefix)) {
			const value = line.slice(prefix.length).trim();
			return value === '' ? null : value;
		}
	}

	return null;
}

function firstNonEmpty(lines: readonly string[]): string | null {
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed !== '') {
			return trimmed;
		}
	}

	return null;
}

function titleFromSlug(slug: string): string {
	return slug
		.split('-')
		.map((part) => {
			const [firstChar, ...rest] = part;
			if (firstChar === undefined) {
				return part;
			}

			return `${firstChar.toUpperCase()}${rest.join('')}`;
		})
		.join(' ');
}

function escapeTable(value: string): string {
	return value.replaceAll('|', '\\|');
}

function toRepoPath(filePath: string, repoRoot: string): string {
	return relative(repoRoot, filePath).replaceAll('\\', '/');
}
