/**
 * Symbol page rendering helpers for generated API docs.
 *
 * @module
 */

import { join } from 'node:path';

import type {
	NormalizedApiComment,
	NormalizedApiCommentTag,
	NormalizedApiExport,
	NormalizedApiModel,
	NormalizedApiNode,
	NormalizedApiType,
} from './typedoc.ts';

export interface GeneratedSymbolPage {
	id: string;
	name: string;
	entrypoint: string;
	publicKind: string;
	routePath: string;
	filePath: string;
	content: string;
	summary: string | null;
}

const GENERATED_HEADER =
	'<!-- Generated by scripts/docs/build-docs-data.ts. Do not edit by hand. -->';

export function collectSymbolPages(
	model: NormalizedApiModel,
	symbolPagesRoot: string,
): readonly GeneratedSymbolPage[] {
	const caseInsensitiveCollisions = collectCaseInsensitiveCollisions(model.exports);

	return model.exports
		.map((entry) => {
			const hasCaseInsensitiveCollision = caseInsensitiveCollisions.has(
				toCollisionKey(entry.entrypoint, entry.name),
			);
			const routePath = toSymbolPageRoute(entry.entrypoint, entry.name, {
				publicKind: entry.publicKind,
				hasCaseInsensitiveCollision,
			});
			return {
				id: entry.id,
				name: entry.name,
				entrypoint: entry.entrypoint,
				publicKind: entry.publicKind,
				routePath,
				filePath: toSymbolPageFilePath(symbolPagesRoot, entry.entrypoint, entry.name, {
					publicKind: entry.publicKind,
					hasCaseInsensitiveCollision,
				}),
				content: renderSymbolPage(entry),
				summary: summarizeComment(entry.reflection.comment),
			} satisfies GeneratedSymbolPage;
		})
		.sort((left, right) => left.id.localeCompare(right.id));
}

export function toSymbolPageRoute(
	entrypoint: string,
	symbolName: string,
	options?: {
		publicKind?: string;
		hasCaseInsensitiveCollision?: boolean;
	},
): string {
	return `/reference/symbols/${toSymbolPageSection(entrypoint)}/${toSymbolPageSlug(symbolName, options)}`;
}

export function toSymbolPageFilePath(
	symbolPagesRoot: string,
	entrypoint: string,
	symbolName: string,
	options?: {
		publicKind?: string;
		hasCaseInsensitiveCollision?: boolean;
	},
): string {
	return join(
		symbolPagesRoot,
		toSymbolPageSection(entrypoint),
		`${toSymbolPageSlug(symbolName, options)}.md`,
	);
}

function collectCaseInsensitiveCollisions(
	entries: readonly { entrypoint: string; name: string }[],
): ReadonlySet<string> {
	const counts = new Map<string, number>();
	for (const entry of entries) {
		const key = toCollisionKey(entry.entrypoint, entry.name);
		counts.set(key, (counts.get(key) ?? 0) + 1);
	}

	return new Set(
		Array.from(counts.entries())
			.filter(([, count]) => count > 1)
			.map(([key]) => key),
	);
}

function toCollisionKey(entrypoint: string, symbolName: string): string {
	return `${entrypoint}:${symbolName.toLowerCase()}`;
}

function toSymbolPageSlug(
	symbolName: string,
	options?: {
		publicKind?: string;
		hasCaseInsensitiveCollision?: boolean;
	},
): string {
	if (options?.hasCaseInsensitiveCollision !== true || symbolName === symbolName.toLowerCase()) {
		return symbolName;
	}

	return `${symbolName.toLowerCase()}-${options.publicKind ?? 'symbol'}`;
}

function toSymbolPageSection(entrypoint: string): string {
	if (entrypoint === 'dreamcli') {
		return 'main';
	}

	const [, section] = entrypoint.split('/');
	return section ?? 'main';
}

function renderSymbolPage(entry: NormalizedApiExport): string {
	const summary = summarizeComment(entry.reflection.comment);
	const source = entry.reflection.sources[0] ?? null;
	const deprecatedNote = renderDeprecatedNote(entry.reflection.comment);
	const exampleTags = collectExampleTags(entry.reflection);
	const sections = [
		renderSignatureSection(entry),
		renderMembersSection(entry.reflection),
		renderExamplesSection(exampleTags),
		renderSeeAlsoSection(entry),
	].flatMap((section) => (section === null ? [] : [section]));

	return [
		GENERATED_HEADER,
		'',
		`# \`${entry.name}\``,
		'',
		summary ?? `Generated reference page for the \`${entry.name}\` ${entry.publicKind} export.`,
		'',
		`- Import: \`${entry.entrypoint}\``,
		`- Export kind: ${entry.publicKind}`,
		`- Declared in: \`${entry.sourcePath}\``,
		...(source?.url !== null && source?.url !== undefined
			? [`- Source link: [\`${source.path}:${source.line}\`](${source.url})`]
			: []),
		'',
		...(deprecatedNote === null ? [] : [deprecatedNote, '']),
		...sections.flatMap((section) => [section, '']),
	].join('\n');
}

function renderSignatureSection(entry: NormalizedApiExport): string | null {
	const reflection = entry.reflection;
	const declarations = renderDeclarations(entry.name, reflection);
	if (declarations.length === 0) {
		return null;
	}

	return ['## Signatures', '', ...declarations].join('\n');
}

function renderDeclarations(name: string, reflection: NormalizedApiNode): readonly string[] {
	switch (reflection.kind) {
		case 'function':
			return renderFunctionDeclarations(name, reflection);
		case 'class':
			return [renderCodeBlock(renderClassDeclaration(name, reflection))];
		case 'interface':
			return [renderCodeBlock(renderInterfaceDeclaration(name, reflection))];
		case 'typeAlias':
			return [renderCodeBlock(renderTypeAliasDeclaration(name, reflection))];
		case 'enum':
			return [renderCodeBlock(renderEnumDeclaration(name, reflection))];
		case 'variable':
			return [renderCodeBlock(renderVariableDeclaration(name, reflection))];
		default:
			if (reflection.signatures.length > 0) {
				return renderFunctionDeclarations(name, reflection);
			}

			if (reflection.type !== null) {
				return [renderCodeBlock(`const ${name}: ${renderType(reflection.type)};`)];
			}

			return [];
	}
}

function renderFunctionDeclarations(
	name: string,
	reflection: NormalizedApiNode,
): readonly string[] {
	const signatures = reflection.signatures.length === 0 ? [reflection] : reflection.signatures;
	return signatures.map((signature, index) => {
		const lines = signatures.length === 1 ? [] : [`### Overload ${index + 1}`, ''];
		return [
			...lines,
			renderCodeBlock(renderCallableSignature(name, signature, 'function')),
			...renderParameterDetails(signature),
		].join('\n');
	});
}

function renderClassDeclaration(name: string, reflection: NormalizedApiNode): string {
	const heritage = [
		...renderHeritageClause('extends', reflection.extendedTypes),
		...renderHeritageClause('implements', reflection.implementedTypes),
	].join(' ');
	const suffix = heritage === '' ? '' : ` ${heritage}`;
	return `class ${name}${renderTypeParameterList(reflection.typeParameters)}${suffix} {}`;
}

function renderInterfaceDeclaration(name: string, reflection: NormalizedApiNode): string {
	const heritage = renderHeritageClause('extends', reflection.extendedTypes).join(' ');
	const suffix = heritage === '' ? '' : ` ${heritage}`;
	return `interface ${name}${renderTypeParameterList(reflection.typeParameters)}${suffix} {}`;
}

function renderTypeAliasDeclaration(name: string, reflection: NormalizedApiNode): string {
	const value = reflection.type === null ? 'unknown' : renderType(reflection.type);
	return `type ${name}${renderTypeParameterList(reflection.typeParameters)} = ${value};`;
}

function renderEnumDeclaration(name: string, reflection: NormalizedApiNode): string {
	const members = reflection.children.map((child) => child.name).join(', ');
	return members === '' ? `enum ${name} {}` : `enum ${name} { ${members} }`;
}

function renderVariableDeclaration(name: string, reflection: NormalizedApiNode): string {
	const value = reflection.type === null ? 'unknown' : renderType(reflection.type);
	return `const ${name}: ${value};`;
}

function renderParameterDetails(signature: NormalizedApiNode): readonly string[] {
	if (signature.parameters.length === 0) {
		return [];
	}

	const rows = signature.parameters.flatMap((parameter) => {
		const summary = summarizeComment(parameter.comment);
		return summary === null
			? []
			: [
					`| \`${parameter.name}\` | \`${escapeTable(renderParameter(parameter))}\` | ${escapeTable(summary)} |`,
				];
	});
	if (rows.length === 0) {
		return [];
	}

	return ['', '| Parameter | Type | Description |', '| --- | --- | --- |', ...rows];
}

function renderMembersSection(reflection: NormalizedApiNode): string | null {
	if (reflection.children.length === 0) {
		return null;
	}

	const groups =
		reflection.groups.length === 0 ? buildFallbackGroups(reflection) : reflection.groups;
	const sections = groups.flatMap((group) => {
		const children = group.childNames.flatMap((name) => {
			const child = reflection.children.find((entry) => entry.name === name);
			return child === undefined ? [] : [child];
		});
		if (children.length === 0) {
			return [];
		}

		return [`### ${group.title}`, '', ...children.flatMap((child) => renderMember(child))];
	});
	if (sections.length === 0) {
		return null;
	}

	return ['## Members', '', ...sections].join('\n');
}

function buildFallbackGroups(
	reflection: NormalizedApiNode,
): readonly { title: string; childNames: readonly string[] }[] {
	return [
		{
			title: 'Members',
			childNames: reflection.children.map((child) => child.name),
		},
	];
}

function renderMember(member: NormalizedApiNode): readonly string[] {
	const summary = summarizeComment(member.comment);
	const declaration = renderMemberDeclaration(member);
	return [
		`#### \`${member.name}\``,
		'',
		...(summary === null ? [] : [summary, '']),
		renderCodeBlock(declaration),
		'',
	];
}

function renderMemberDeclaration(member: NormalizedApiNode): string {
	switch (member.kind) {
		case 'property':
			return `${member.name}${isOptionalNode(member) ? '?' : ''}: ${renderNodeType(member)};`;
		case 'method':
			return renderMethodDeclaration(member);
		case 'accessor':
		case 'getSignature':
		case 'setSignature':
			return renderAccessorDeclaration(member);
		case 'constructor':
			return renderCallableSignature('constructor', member, 'constructor');
		case 'callSignature':
			return renderCallableSignature('', member, 'call');
		case 'indexSignature':
			return renderIndexSignature(member);
		default:
			if (member.signatures.length > 0) {
				return renderMethodDeclaration(member);
			}

			return `${member.name}: ${renderNodeType(member)};`;
	}
}

function renderMethodDeclaration(member: NormalizedApiNode): string {
	const signature = member.signatures[0] ?? member;
	return renderCallableSignature(member.name, signature, 'method');
}

function renderAccessorDeclaration(member: NormalizedApiNode): string {
	const getter = member.getSignature ?? member;
	const setter = member.setSignature;
	if (setter === null) {
		return `get ${member.name}(): ${renderNodeType(getter)};`;
	}

	const valueParameter = setter.parameters[0];
	const setterType = valueParameter === undefined ? 'unknown' : renderParameter(valueParameter);
	return [
		`get ${member.name}(): ${renderNodeType(getter)};`,
		`set ${member.name}(${setterType});`,
	].join('\n');
}

function renderIndexSignature(member: NormalizedApiNode): string {
	const parameter = member.parameters[0];
	if (parameter === undefined) {
		return `[key: string]: ${renderNodeType(member)};`;
	}

	return `[${parameter.name}: ${renderNodeType(parameter)}]: ${renderNodeType(member)};`;
}

function renderCallableSignature(
	name: string,
	signature: NormalizedApiNode,
	kind: 'function' | 'method' | 'constructor' | 'call',
): string {
	const typeParameters = renderTypeParameterList(signature.typeParameters);
	const parameters = signature.parameters.map(renderParameter).join(', ');
	const returnType = signature.type === null ? 'void' : renderType(signature.type);

	if (kind === 'constructor') {
		return `constructor${typeParameters}(${parameters});`;
	}

	if (kind === 'call') {
		return `(${parameters}): ${returnType};`;
	}

	const prefix = kind === 'function' ? 'function ' : '';
	return `${prefix}${name}${typeParameters}(${parameters}): ${returnType};`;
}

function renderParameter(parameter: NormalizedApiNode): string {
	const optional = isOptionalNode(parameter);
	const type = parameter.type === null ? 'unknown' : renderType(parameter.type);
	const defaultValue = parameter.defaultValue === null ? '' : ` = ${parameter.defaultValue}`;
	if (parameter.type?.kind === 'rest') {
		return `...${parameter.name}: ${renderType(parameter.type.elementType)}`;
	}

	return `${parameter.name}${optional ? '?' : ''}: ${type}${defaultValue}`;
}

function renderNodeType(node: NormalizedApiNode): string {
	return node.type === null ? 'unknown' : renderType(node.type);
}

function renderType(type: NormalizedApiType): string {
	switch (type.kind) {
		case 'array':
			return `${wrapIfNeeded(type.elementType)}[]`;
		case 'conditional':
			return `${renderType(type.checkType)} extends ${renderType(type.extendsType)} ? ${renderType(type.trueType)} : ${renderType(type.falseType)}`;
		case 'indexedAccess':
			return `${renderType(type.objectType)}[${renderType(type.indexType)}]`;
		case 'inferred':
			return type.constraint === null
				? `infer ${type.name}`
				: `infer ${type.name} extends ${renderType(type.constraint)}`;
		case 'intersection':
			return type.types.map(wrapUnionishType).join(' & ');
		case 'intrinsic':
			return type.name;
		case 'literal':
			return JSON.stringify(type.value);
		case 'mapped':
			return renderMappedType(type);
		case 'namedTupleMember':
			return `${type.name}${type.isOptional ? '?' : ''}: ${renderType(type.element)}`;
		case 'optional':
			return `${renderType(type.elementType)} | undefined`;
		case 'predicate':
			return `${type.asserts ? 'asserts ' : ''}${type.name}${type.targetType === null ? '' : ` is ${renderType(type.targetType)}`}`;
		case 'query':
			return `typeof ${renderType(type.queryType)}`;
		case 'reference':
			return renderReferenceType(type);
		case 'reflection':
			return renderReflectionType(type.declaration);
		case 'rest':
			return `...${renderType(type.elementType)}[]`;
		case 'templateLiteral':
			return `\`${type.head}${type.tail.map((entry) => `\${${renderType(entry.type)}}${entry.text}`).join('')}\``;
		case 'tuple':
			return `[${type.elements.map(renderType).join(', ')}]`;
		case 'typeOperator':
			return `${type.operator} ${wrapIfNeeded(type.target)}`;
		case 'union':
			return type.types.map(renderType).join(' | ');
		case 'unknown':
			return type.name;
	}
}

function renderMappedType(type: Extract<NormalizedApiType, { kind: 'mapped' }>): string {
	const readonlyModifier = type.readonlyModifier === null ? '' : `${type.readonlyModifier} `;
	const optionalModifier = type.optionalModifier === null ? '' : type.optionalModifier;
	const parameterType = type.parameterType === null ? 'unknown' : renderType(type.parameterType);
	const nameType = type.nameType === null ? '' : ` as ${renderType(type.nameType)}`;
	const templateType = type.templateType === null ? 'unknown' : renderType(type.templateType);
	return `{ ${readonlyModifier}[${type.parameter} in ${parameterType}${nameType}]${optionalModifier}: ${templateType} }`;
}

function renderReferenceType(type: Extract<NormalizedApiType, { kind: 'reference' }>): string {
	const targetName = type.qualifiedName ?? type.name;
	const typeArguments =
		type.typeArguments.length === 0 ? '' : `<${type.typeArguments.map(renderType).join(', ')}>`;
	return `${targetName}${typeArguments}`;
}

function renderReflectionType(reflection: NormalizedApiNode): string {
	if (reflection.kind !== 'typeLiteral') {
		return reflection.name;
	}

	if (reflection.children.length === 0 && reflection.signatures.length === 0) {
		return '{}';
	}

	const members = [
		...reflection.signatures.map((signature) => renderCallableSignature('', signature, 'call')),
		...reflection.children.map((child) => renderMemberDeclaration(child)),
	];

	return `{ ${members.join(' ')} }`;
}

function wrapIfNeeded(type: NormalizedApiType): string {
	const rendered = renderType(type);
	return type.kind === 'union' || type.kind === 'intersection' ? `(${rendered})` : rendered;
}

function wrapUnionishType(type: NormalizedApiType): string {
	const rendered = renderType(type);
	return type.kind === 'union' ? `(${rendered})` : rendered;
}

function renderHeritageClause(
	keyword: string,
	types: readonly NormalizedApiType[],
): readonly string[] {
	if (types.length === 0) {
		return [];
	}

	return [`${keyword} ${types.map(renderType).join(', ')}`];
}

function renderExamplesSection(tags: readonly NormalizedApiCommentTag[]): string | null {
	if (tags.length === 0) {
		return null;
	}

	return [
		'## Examples',
		'',
		...tags.flatMap((tag) => [renderExampleBlock(tag.content.trimEnd()), '']),
	].join('\n');
}

function renderSeeAlsoSection(entry: NormalizedApiExport): string {
	return [
		'## See Also',
		'',
		'- [API overview](/reference/api)',
		`- [${entry.entrypoint}](${toEntrypointReference(entry.entrypoint)})`,
	].join('\n');
}

function toEntrypointReference(entrypoint: string): string {
	switch (entrypoint) {
		case 'dreamcli':
			return '/reference/main';
		case 'dreamcli/runtime':
			return '/reference/runtime';
		case 'dreamcli/testkit':
			return '/reference/testkit';
		default:
			return '/reference/api';
	}
}

function collectExampleTags(reflection: NormalizedApiNode): readonly NormalizedApiCommentTag[] {
	return [
		...extractExampleTags(reflection.comment),
		...reflection.signatures.flatMap((signature) => extractExampleTags(signature.comment)),
	];
}

function extractExampleTags(
	comment: NormalizedApiComment | null,
): readonly NormalizedApiCommentTag[] {
	if (comment === null) {
		return [];
	}

	return comment.blockTags.filter((tag) => tag.tag === '@example' && tag.content.trim() !== '');
}

function renderDeprecatedNote(comment: NormalizedApiComment | null): string | null {
	if (comment === null) {
		return null;
	}

	const deprecatedTag = comment.blockTags.find((tag) => tag.tag === '@deprecated');
	if (deprecatedTag !== undefined) {
		const content = deprecatedTag.content.trim();
		return content === '' ? '> Deprecated.' : `> Deprecated: ${content}`;
	}

	return comment.modifierTags.includes('@deprecated') ? '> Deprecated.' : null;
}

function summarizeComment(comment: NormalizedApiComment | null): string | null {
	if (comment === null) {
		return null;
	}

	const summary = comment.summary.trim();
	return summary === '' ? null : summary;
}

function renderTypeParameterList(typeParameters: readonly NormalizedApiNode[]): string {
	if (typeParameters.length === 0) {
		return '';
	}

	return `<${typeParameters.map(renderTypeParameter).join(', ')}>`;
}

function renderTypeParameter(parameter: NormalizedApiNode): string {
	const constraint = parameter.type === null ? '' : ` extends ${renderType(parameter.type)}`;
	return `${parameter.name}${constraint}`;
}

function isOptionalNode(node: NormalizedApiNode): boolean {
	return node.flags.includes('isOptional');
}

function renderCodeBlock(content: string): string {
	return ['```ts', content, '```'].join('\n');
}

function renderExampleBlock(content: string): string {
	return content.startsWith('```') ? content : renderCodeBlock(content);
}

function escapeTable(value: string): string {
	return value.replaceAll('|', '\\|');
}
