/**
 * Tests for completion types, Shell enum, and generators.
 */

import { describe, expect, it } from 'vitest';
import type { CLISchema } from '../cli/index.js';
import { isCLIError } from '../errors/index.js';
import type { CommandSchema, FlagSchema } from '../schema/index.js';
import type { CompletionOptions } from './index.js';
import {
	generateBashCompletion,
	generateCompletion,
	generateZshCompletion,
	SHELLS,
} from './index.js';

// ===================================================================
// Test helpers
// ===================================================================

/** Minimal FlagSchema with all required fields. */
function flagSchema(overrides: Partial<FlagSchema> = {}): FlagSchema {
	return {
		kind: 'string',
		presence: 'optional',
		defaultValue: undefined,
		aliases: [],
		envVar: undefined,
		configPath: undefined,
		description: undefined,
		enumValues: undefined,
		elementSchema: undefined,
		prompt: undefined,
		...overrides,
	};
}

/** Minimal CommandSchema with all required fields. */
function commandSchema(overrides: Partial<CommandSchema> = {}): CommandSchema {
	return {
		name: 'test',
		description: undefined,
		aliases: [],
		hidden: false,
		examples: [],
		flags: {},
		args: [],
		hasAction: true,
		interactive: undefined,
		middleware: [],
		...overrides,
	};
}

/** Wrap CommandSchema into an ErasedCommand for CLISchema.commands. */
function erased(schema: CommandSchema) {
	return {
		schema,
		async _execute() {
			return { stdout: [] as string[], stderr: [] as string[], exitCode: 0, error: undefined };
		},
	};
}

/** Minimal CLISchema for completion tests. */
function minimalSchema(overrides: Partial<CLISchema> = {}): CLISchema {
	return {
		name: 'testcli',
		version: '1.0.0',
		description: 'A test CLI',
		commands: [],
		...overrides,
	};
}

// ===================================================================
// Shell type — SHELLS constant
// ===================================================================

describe('Shell type — SHELLS constant', () => {
	it('contains all four shell targets', () => {
		expect(SHELLS).toEqual(['bash', 'zsh', 'fish', 'powershell']);
	});

	it('is readonly (frozen at type level)', () => {
		expect(SHELLS).toHaveLength(4);
	});
});

// ===================================================================
// CompletionOptions — type contract
// ===================================================================

describe('CompletionOptions — type contract', () => {
	it('accepts empty options', () => {
		const options: CompletionOptions = {};
		expect(options).toEqual({});
	});

	it('accepts functionPrefix', () => {
		const options: CompletionOptions = { functionPrefix: '_myapp' };
		expect(options.functionPrefix).toBe('_myapp');
	});
});

// ===================================================================
// generateBashCompletion — script structure
// ===================================================================

describe('generateBashCompletion — script structure', () => {
	it('generates shebang and header comment', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('#!/usr/bin/env bash');
		expect(script).toContain('# Bash completion for testcli');
		expect(script).toContain('# Generated by dreamcli');
	});

	it('generates function named _<name>_completions', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('_testcli_completions() {');
	});

	it('uses _init_completion for variable setup', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('local cur prev words cword');
		expect(script).toContain('_init_completion || return');
	});

	it('registers with complete -F', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('complete -F _testcli_completions testcli');
	});

	it('includes --help and --version as root completions', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('--help');
		expect(script).toContain('--version');
	});
});

// ===================================================================
// generateBashCompletion — functionPrefix option
// ===================================================================

describe('generateBashCompletion — functionPrefix option', () => {
	it('uses functionPrefix instead of schema name for function', () => {
		const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'myapp' });

		expect(script).toContain('_myapp_completions() {');
		expect(script).toContain('complete -F _myapp_completions testcli');
	});

	it('sanitizes non-identifier characters in prefix', () => {
		const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'my-app.v2' });

		expect(script).toContain('_my_app_v2_completions() {');
	});
});

// ===================================================================
// generateBashCompletion — subcommand completions
// ===================================================================

describe('generateBashCompletion — subcommand completions', () => {
	it('lists subcommand names at root level', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy' })),
				erased(commandSchema({ name: 'build' })),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("'deploy build --help --version'");
	});

	it('excludes hidden commands from completions', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy' })),
				erased(commandSchema({ name: 'secret', hidden: true })),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('deploy');
		expect(script).not.toContain('secret');
	});

	it('includes command aliases in subcommand detection', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy', aliases: ['d', 'ship'] }))],
		});
		const script = generateBashCompletion(schema);

		// Aliases should appear in the case pattern for subcommand detection
		expect(script).toContain('deploy|d|ship)');
	});
});

// ===================================================================
// generateBashCompletion — flag completions
// ===================================================================

describe('generateBashCompletion — flag completions', () => {
	it('includes --flagname for each registered flag', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({ kind: 'string', description: 'AWS region' }),
							force: flagSchema({ kind: 'boolean' }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--region');
		expect(script).toContain('--force');
	});

	it('includes short aliases as -<alias>', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', aliases: ['f'] }),
							verbose: flagSchema({ kind: 'boolean', aliases: ['v'] }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('-f');
		expect(script).toContain('-v');
	});

	it('includes long aliases as --<alias>', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', aliases: ['no-confirm'] }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--no-confirm');
	});
});

// ===================================================================
// generateBashCompletion — enum value completions
// ===================================================================

describe('generateBashCompletion — enum value completions', () => {
	it('generates case branch for enum flag values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								enumValues: ['us-east-1', 'eu-west-1', 'ap-south-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('case "$prev" in');
		expect(script).toContain('--region)');
		expect(script).toContain("'us-east-1 eu-west-1 ap-south-1'");
	});

	it('includes enum flag aliases in case pattern', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								aliases: ['r'],
								enumValues: ['us-east-1', 'eu-west-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--region|-r)');
	});

	it('omits enum case section when no enum flags exist', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean' }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).not.toContain('case "$prev" in');
	});
});

// ===================================================================
// generateBashCompletion — no commands (flags-only CLI)
// ===================================================================

describe('generateBashCompletion — no commands', () => {
	it('generates script with only --help and --version', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain("'--help --version'");
		expect(script).not.toContain('subcmd');
	});
});

// ===================================================================
// generateBashCompletion — CLI name sanitization
// ===================================================================

describe('generateBashCompletion — name sanitization', () => {
	it('replaces hyphens in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'my-cli-tool' });
		const script = generateBashCompletion(schema);

		expect(script).toContain('_my_cli_tool_completions() {');
		// complete line still uses original name
		expect(script).toContain('complete -F _my_cli_tool_completions my-cli-tool');
	});

	it('replaces dots in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'app.cli' });
		const script = generateBashCompletion(schema);

		expect(script).toContain('_app_cli_completions() {');
	});
});

// ===================================================================
// generateZshCompletion — stub
// ===================================================================

describe('generateZshCompletion — stub throws CLIError', () => {
	it('throws CLIError with UNSUPPORTED_OPERATION code', () => {
		const schema = minimalSchema();

		expect(() => generateZshCompletion(schema)).toThrow();

		try {
			generateZshCompletion(schema);
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.code).toBe('UNSUPPORTED_OPERATION');
				expect(e.message).toContain('Zsh');
				expect(e.message).toContain('not yet implemented');
			}
		}
	});
});

// ===================================================================
// generateCompletion — unified dispatcher
// ===================================================================

describe('generateCompletion — dispatcher', () => {
	it('delegates bash to generateBashCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'bash');

		expect(script).toContain('_testcli_completions() {');
		expect(script).toContain('complete -F _testcli_completions testcli');
	});

	it('delegates zsh to generateZshCompletion (stub throws)', () => {
		const schema = minimalSchema();

		expect(() => generateCompletion(schema, 'zsh')).toThrow();

		try {
			generateCompletion(schema, 'zsh');
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.message).toContain('Zsh');
			}
		}
	});

	it('throws CLIError for fish (unsupported)', () => {
		const schema = minimalSchema();

		expect(() => generateCompletion(schema, 'fish')).toThrow();

		try {
			generateCompletion(schema, 'fish');
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.code).toBe('UNSUPPORTED_OPERATION');
				expect(e.message).toContain('fish');
				expect(e.message).toContain('not yet supported');
			}
		}
	});

	it('throws CLIError for powershell (unsupported)', () => {
		const schema = minimalSchema();

		expect(() => generateCompletion(schema, 'powershell')).toThrow();

		try {
			generateCompletion(schema, 'powershell');
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.code).toBe('UNSUPPORTED_OPERATION');
				expect(e.message).toContain('powershell');
				expect(e.message).toContain('not yet supported');
			}
		}
	});

	it('passes options through to bash generator', () => {
		const schema = minimalSchema();
		const options: CompletionOptions = { functionPrefix: '_custom' };
		const script = generateCompletion(schema, 'bash', options);

		expect(script).toContain('__custom_completions() {');
	});
});
