/**
 * Tests for completion types, Shell enum, and generators.
 */

import { describe, expect, it } from 'vitest';
import type { CLISchema } from '../cli/index.js';
import { isCLIError } from '../errors/index.js';
import type { CommandSchema, FlagSchema } from '../schema/index.js';
import type { CompletionOptions } from './index.js';
import {
	generateBashCompletion,
	generateCompletion,
	generateZshCompletion,
	SHELLS,
} from './index.js';

// ===================================================================
// Test helpers
// ===================================================================

/** Minimal FlagSchema with all required fields. */
function flagSchema(overrides: Partial<FlagSchema> = {}): FlagSchema {
	return {
		kind: 'string',
		presence: 'optional',
		defaultValue: undefined,
		aliases: [],
		envVar: undefined,
		configPath: undefined,
		description: undefined,
		enumValues: undefined,
		elementSchema: undefined,
		prompt: undefined,
		...overrides,
	};
}

/** Minimal CommandSchema with all required fields. */
function commandSchema(overrides: Partial<CommandSchema> = {}): CommandSchema {
	return {
		name: 'test',
		description: undefined,
		aliases: [],
		hidden: false,
		examples: [],
		flags: {},
		args: [],
		hasAction: true,
		interactive: undefined,
		middleware: [],
		...overrides,
	};
}

/** Wrap CommandSchema into an ErasedCommand for CLISchema.commands. */
function erased(schema: CommandSchema) {
	return {
		schema,
		async _execute() {
			return { stdout: [] as string[], stderr: [] as string[], exitCode: 0, error: undefined };
		},
	};
}

/** Minimal CLISchema for completion tests. */
function minimalSchema(overrides: Partial<CLISchema> = {}): CLISchema {
	return {
		name: 'testcli',
		version: '1.0.0',
		description: 'A test CLI',
		commands: [],
		configSettings: undefined,
		...overrides,
	};
}

// ===================================================================
// Shell type — SHELLS constant
// ===================================================================

describe('Shell type — SHELLS constant', () => {
	it('contains all four shell targets', () => {
		expect(SHELLS).toEqual(['bash', 'zsh', 'fish', 'powershell']);
	});

	it('is readonly (frozen at type level)', () => {
		expect(SHELLS).toHaveLength(4);
	});
});

// ===================================================================
// CompletionOptions — type contract
// ===================================================================

describe('CompletionOptions — type contract', () => {
	it('accepts empty options', () => {
		const options: CompletionOptions = {};
		expect(options).toEqual({});
	});

	it('accepts functionPrefix', () => {
		const options: CompletionOptions = { functionPrefix: '_myapp' };
		expect(options.functionPrefix).toBe('_myapp');
	});
});

// ===================================================================
// generateBashCompletion — script structure
// ===================================================================

describe('generateBashCompletion — script structure', () => {
	it('generates shebang and header comment', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('#!/usr/bin/env bash');
		expect(script).toContain('# Bash completion for testcli');
		expect(script).toContain('# Generated by dreamcli');
	});

	it('generates function named _<name>_completions', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('_testcli_completions() {');
	});

	it('uses _init_completion for variable setup', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('local cur prev words cword');
		expect(script).toContain('_init_completion || return');
	});

	it('registers with complete -F', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('complete -F _testcli_completions testcli');
	});

	it('includes --help and --version as root completions', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain('--help');
		expect(script).toContain('--version');
	});

	it('includes --version when schema has version', () => {
		const script = generateBashCompletion(
			minimalSchema({
				version: '1.0.0',
				commands: [erased(commandSchema({ name: 'deploy' }))],
			}),
		);

		expect(script).toContain('--version');
	});

	it('omits --version when schema has no version', () => {
		const script = generateBashCompletion(
			minimalSchema({
				version: undefined,
				commands: [erased(commandSchema({ name: 'deploy' }))],
			}),
		);

		expect(script).toContain('--help');
		expect(script).not.toContain('--version');
	});
});

// ===================================================================
// generateBashCompletion — functionPrefix option
// ===================================================================

describe('generateBashCompletion — functionPrefix option', () => {
	it('uses functionPrefix instead of schema name for function', () => {
		const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'myapp' });

		expect(script).toContain('_myapp_completions() {');
		expect(script).toContain('complete -F _myapp_completions testcli');
	});

	it('sanitizes non-identifier characters in prefix', () => {
		const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'my-app.v2' });

		expect(script).toContain('_my_app_v2_completions() {');
	});
});

// ===================================================================
// generateBashCompletion — subcommand completions
// ===================================================================

describe('generateBashCompletion — subcommand completions', () => {
	it('lists subcommand names at root level', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy' })),
				erased(commandSchema({ name: 'build' })),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("'deploy build --help --version'");
	});

	it('excludes hidden commands from completions', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy' })),
				erased(commandSchema({ name: 'secret', hidden: true })),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('deploy');
		expect(script).not.toContain('secret');
	});

	it('includes command aliases in subcommand detection', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy', aliases: ['d', 'ship'] }))],
		});
		const script = generateBashCompletion(schema);

		// Aliases should appear in the case pattern for subcommand detection
		expect(script).toContain('deploy|d|ship)');
	});
});

// ===================================================================
// generateBashCompletion — flag completions
// ===================================================================

describe('generateBashCompletion — flag completions', () => {
	it('includes --flagname for each registered flag', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({ kind: 'string', description: 'AWS region' }),
							force: flagSchema({ kind: 'boolean' }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--region');
		expect(script).toContain('--force');
	});

	it('includes short aliases as -<alias>', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', aliases: ['f'] }),
							verbose: flagSchema({ kind: 'boolean', aliases: ['v'] }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('-f');
		expect(script).toContain('-v');
	});

	it('includes long aliases as --<alias>', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', aliases: ['no-confirm'] }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--no-confirm');
	});
});

// ===================================================================
// generateBashCompletion — enum value completions
// ===================================================================

describe('generateBashCompletion — enum value completions', () => {
	it('generates case branch for enum flag values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								enumValues: ['us-east-1', 'eu-west-1', 'ap-south-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('case "$prev" in');
		expect(script).toContain('--region)');
		expect(script).toContain("'us-east-1 eu-west-1 ap-south-1'");
	});

	it('includes enum flag aliases in case pattern', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								aliases: ['r'],
								enumValues: ['us-east-1', 'eu-west-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain('--region|-r)');
	});

	it('omits enum case section when no enum flags exist', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean' }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).not.toContain('case "$prev" in');
	});

	// --- Cross-command enum isolation ---

	it('completes correct enum values per command when same-named flag has different values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							env: flagSchema({
								kind: 'enum',
								enumValues: ['prod', 'staging'],
							}),
						},
					}),
				),
				erased(
					commandSchema({
						name: 'test',
						flags: {
							env: flagSchema({
								kind: 'enum',
								enumValues: ['unit', 'e2e'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);
		const lines = script.split('\n');

		// Find per-command case branches (inside "Complete flags" section)
		const flagSectionStart = lines.findIndex((l) => l.includes('Complete flags'));
		const flagSection = lines.slice(flagSectionStart);

		const deployIdx = flagSection.findIndex((l) => l.trim().startsWith('deploy)'));
		const testIdx = flagSection.findIndex((l) => l.trim().startsWith('test)'));

		const deployBlock = flagSection.slice(deployIdx, testIdx).join('\n');
		const testBlock = flagSection.slice(testIdx).join('\n');

		expect(deployBlock).toContain("'prod staging'");
		expect(deployBlock).not.toContain('unit');
		expect(deployBlock).not.toContain('e2e');

		expect(testBlock).toContain("'unit e2e'");
		expect(testBlock).not.toContain('prod');
		expect(testBlock).not.toContain('staging');
	});

	it('handles mixed enum and non-enum flags across commands', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							env: flagSchema({
								kind: 'enum',
								enumValues: ['prod', 'staging'],
							}),
							force: flagSchema({ kind: 'boolean' }),
						},
					}),
				),
				erased(
					commandSchema({
						name: 'build',
						flags: {
							target: flagSchema({ kind: 'string' }),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);
		const lines = script.split('\n');

		const flagSectionStart = lines.findIndex((l) => l.includes('Complete flags'));
		const flagSection = lines.slice(flagSectionStart);

		const deployIdx = flagSection.findIndex((l) => l.trim().startsWith('deploy)'));
		const buildIdx = flagSection.findIndex((l) => l.trim().startsWith('build)'));

		const deployBlock = flagSection.slice(deployIdx, buildIdx).join('\n');
		const buildBlock = flagSection.slice(buildIdx).join('\n');

		// Deploy should have enum case block
		expect(deployBlock).toContain('case "$prev" in');
		expect(deployBlock).toContain("'prod staging'");

		// Build should NOT have enum case block (no enum flags)
		expect(buildBlock).not.toContain('case "$prev" in');
	});
});

// ===================================================================
// generateBashCompletion — enum value escaping
// ===================================================================

describe('generateBashCompletion — enum value escaping', () => {
	it('passes simple values through unescaped', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								enumValues: ['us-east-1', 'eu-west-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("compgen -W 'us-east-1 eu-west-1'");
		expect(script).not.toContain('IFS');
	});

	it('uses $-quoting with IFS for values containing spaces', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							env: flagSchema({
								kind: 'enum',
								enumValues: ['hello world', 'foo'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("local IFS=$'\\n'");
		expect(script).toContain("compgen -W $'hello world\\nfoo'");
	});

	it('escapes single quotes in enum values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							msg: flagSchema({
								kind: 'enum',
								enumValues: ["it's", 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("local IFS=$'\\n'");
		expect(script).toContain("it\\'s");
	});

	it('escapes backslashes in enum values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							path: flagSchema({
								kind: 'enum',
								enumValues: ['C:\\Users', 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		expect(script).toContain("local IFS=$'\\n'");
		expect(script).toContain('C:\\\\Users');
	});

	it('handles mixed pathological values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							weird: flagSchema({
								kind: 'enum',
								enumValues: ["it's here", 'C:\\path', 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateBashCompletion(schema);

		// All values use $'...' quoting because at least one needs it
		expect(script).toContain("local IFS=$'\\n'");
		expect(script).toContain("compgen -W $'");
		expect(script).toContain("it\\'s here");
		expect(script).toContain('C:\\\\path');
		expect(script).toContain('normal');
	});
});

// ===================================================================
// generateBashCompletion — no commands (flags-only CLI)
// ===================================================================

describe('generateBashCompletion — no commands', () => {
	it('generates script with --help and --version when version defined', () => {
		const script = generateBashCompletion(minimalSchema());

		expect(script).toContain("'--help --version'");
		expect(script).not.toContain('subcmd');
	});

	it('generates script with only --help when no version', () => {
		const script = generateBashCompletion(minimalSchema({ version: undefined }));

		expect(script).toContain("'--help'");
		expect(script).not.toContain('--version');
		expect(script).not.toContain('subcmd');
	});
});

// ===================================================================
// generateBashCompletion — CLI name sanitization
// ===================================================================

describe('generateBashCompletion — name sanitization', () => {
	it('replaces hyphens in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'my-cli-tool' });
		const script = generateBashCompletion(schema);

		expect(script).toContain('_my_cli_tool_completions() {');
		// complete line still uses original name
		expect(script).toContain('complete -F _my_cli_tool_completions my-cli-tool');
	});

	it('replaces dots in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'app.cli' });
		const script = generateBashCompletion(schema);

		expect(script).toContain('_app_cli_completions() {');
	});
});

// ===================================================================
// generateBashCompletion — name escaping (shell injection prevention)
// ===================================================================

describe('generateBashCompletion — name escaping', () => {
	it('leaves shell-safe names unquoted in complete line', () => {
		const script = generateBashCompletion(minimalSchema({ name: 'my-cli' }));

		expect(script).toContain('complete -F _my_cli_completions my-cli');
	});

	it('leaves dotted names unquoted in complete line', () => {
		const script = generateBashCompletion(minimalSchema({ name: 'app.v2' }));

		expect(script).toContain('complete -F _app_v2_completions app.v2');
	});

	it('single-quotes names with spaces in complete line', () => {
		const script = generateBashCompletion(minimalSchema({ name: 'my cli' }));

		expect(script).toContain("complete -F _my_cli_completions 'my cli'");
	});

	it('escapes single quotes in CLI name', () => {
		const script = generateBashCompletion(minimalSchema({ name: "it's" }));

		expect(script).toContain("complete -F _it_s_completions 'it'\\''s'");
	});

	it('single-quotes names with backticks', () => {
		const script = generateBashCompletion(minimalSchema({ name: 'cli`whoami`' }));

		expect(script).toContain("complete -F _cli_whoami__completions 'cli`whoami`'");
	});

	it('single-quotes names with semicolons', () => {
		const script = generateBashCompletion(minimalSchema({ name: 'cli;rm -rf /' }));

		expect(script).toContain("'cli;rm -rf /'");
	});

	it('single-quotes names with dollar signs', () => {
		const script = generateBashCompletion(minimalSchema({ name: '$HOME' }));

		expect(script).toContain("complete -F __HOME_completions '$HOME'");
	});
});

// ===================================================================
// generateZshCompletion — script structure
// ===================================================================

describe('generateZshCompletion — script structure', () => {
	it('generates #compdef directive with CLI name', () => {
		const script = generateZshCompletion(minimalSchema());

		expect(script).toContain('#compdef testcli');
	});

	it('generates header comment', () => {
		const script = generateZshCompletion(minimalSchema());

		expect(script).toContain('# Zsh completion for testcli');
		expect(script).toContain('# Generated by dreamcli');
	});

	it('generates function named _<name>', () => {
		const script = generateZshCompletion(minimalSchema());

		expect(script).toContain('_testcli() {');
	});

	it('declares local variables for state tracking', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy' }))],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain('local -a subcmds');
		expect(script).toContain('local line state');
	});

	it('ends with function invocation _<name> "$@"', () => {
		const script = generateZshCompletion(minimalSchema());

		expect(script).toContain('_testcli "$@"');
	});

	it('includes --help in root _arguments', () => {
		const script = generateZshCompletion(minimalSchema());

		expect(script).toContain('--help[Show help text]');
	});

	it('includes --version when schema has version', () => {
		const script = generateZshCompletion(
			minimalSchema({
				version: '1.0.0',
				commands: [erased(commandSchema({ name: 'test' }))],
			}),
		);

		expect(script).toContain('--version[Show version]');
	});

	it('omits --version when schema has no version', () => {
		const script = generateZshCompletion(
			minimalSchema({
				version: undefined,
				commands: [erased(commandSchema({ name: 'test' }))],
			}),
		);

		expect(script).not.toContain('--version');
	});

	it('includes --version in no-commands path when version defined', () => {
		const script = generateZshCompletion(minimalSchema({ version: '2.0.0', commands: [] }));

		expect(script).toContain('--version[Show version]');
	});
});

// ===================================================================
// generateZshCompletion — functionPrefix option
// ===================================================================

describe('generateZshCompletion — functionPrefix option', () => {
	it('uses functionPrefix instead of schema name for function', () => {
		const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'myapp' });

		expect(script).toContain('_myapp() {');
		expect(script).toContain('_myapp "$@"');
	});

	it('sanitizes non-identifier characters in prefix', () => {
		const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'my-app.v2' });

		expect(script).toContain('_my_app_v2() {');
	});

	it('keeps #compdef using original CLI name, not prefix', () => {
		const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'myapp' });

		expect(script).toContain('#compdef testcli');
	});
});

// ===================================================================
// generateZshCompletion — subcommand completions
// ===================================================================

describe('generateZshCompletion — subcommand completions', () => {
	it('lists subcommands with _describe', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
				erased(commandSchema({ name: 'build', description: 'Build project' })),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("_describe 'command' subcmds");
		expect(script).toContain("'deploy:Deploy app'");
		expect(script).toContain("'build:Build project'");
	});

	it('excludes hidden commands from completions', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
				erased(commandSchema({ name: 'secret', hidden: true })),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain('deploy');
		expect(script).not.toContain('secret');
	});

	it('includes command aliases in case pattern', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy', aliases: ['d', 'ship'] }))],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain('deploy|d|ship)');
	});

	it('uses command name as description when description is undefined', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy', description: undefined }))],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("'deploy:deploy'");
	});

	it('escapes colons in descriptions', () => {
		const schema = minimalSchema({
			commands: [erased(commandSchema({ name: 'deploy', description: 'Deploy: now' }))],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("'deploy:Deploy\\: now'");
	});
});

// ===================================================================
// generateZshCompletion — flag completions
// ===================================================================

describe('generateZshCompletion — flag completions', () => {
	it('generates _arguments specs for command flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({ kind: 'string', description: 'AWS region' }),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain('_arguments');
		expect(script).toContain('--region[AWS region]');
	});

	it('generates mutual exclusion group for short aliases', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', aliases: ['f'], description: 'Force' }),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("(-f --force)'{-f,--force}'[Force]");
	});

	it('omits value part for boolean flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							force: flagSchema({ kind: 'boolean', description: 'Force deploy' }),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		// Boolean flag should end at the description, no :value: part
		expect(script).toContain("'--force[Force deploy]'");
	});

	it('adds :value: for string flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							name: flagSchema({ kind: 'string', description: 'Name' }),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("'--name[Name]:value:'");
	});

	it('adds enum values for enum flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								description: 'Region',
								enumValues: ['us-east-1', 'eu-west-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain('--region[Region]:value:(us-east-1 eu-west-1)');
	});

	it('uses flag name as description when description is undefined', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							verbose: flagSchema({ kind: 'boolean', description: undefined }),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("'--verbose[verbose]'");
	});
});

// ===================================================================
// generateZshCompletion — enum value escaping
// ===================================================================

describe('generateZshCompletion — enum value escaping', () => {
	it('passes simple values through unescaped', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							region: flagSchema({
								kind: 'enum',
								description: 'Region',
								enumValues: ['us-east-1', 'eu-west-1'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain(':value:(us-east-1 eu-west-1)');
	});

	it('escapes spaces in enum values with backslash', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							env: flagSchema({
								kind: 'enum',
								description: 'Environment',
								enumValues: ['hello world', 'foo'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain(':value:(hello\\ world foo)');
	});

	it('escapes single quotes in enum values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							msg: flagSchema({
								kind: 'enum',
								description: 'Message',
								enumValues: ["it's", 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain(":value:(it\\'s normal)");
	});

	it('escapes backslashes in enum values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							path: flagSchema({
								kind: 'enum',
								description: 'Path',
								enumValues: ['C:\\Users', 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain(':value:(C:\\\\Users normal)');
	});

	it('escapes parentheses in enum values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							expr: flagSchema({
								kind: 'enum',
								description: 'Expr',
								enumValues: ['(a)', 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain(':value:(\\(a\\) normal)');
	});

	it('handles mixed pathological values', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							weird: flagSchema({
								kind: 'enum',
								description: 'Weird',
								enumValues: ["it's here", 'C:\\path', 'normal'],
							}),
						},
					}),
				),
			],
		});
		const script = generateZshCompletion(schema);

		expect(script).toContain("it\\'s\\ here");
		expect(script).toContain('C:\\\\path');
		expect(script).toContain('normal');
	});
});

// ===================================================================
// generateZshCompletion — no commands (flags-only CLI)
// ===================================================================

describe('generateZshCompletion — no commands', () => {
	it('generates script with only --help when no commands', () => {
		const script = generateZshCompletion(minimalSchema({ version: undefined }));

		expect(script).toContain('_arguments');
		expect(script).toContain("'--help[Show help text]'");
		expect(script).not.toContain('subcmds');
		expect(script).not.toContain('_describe');
	});
});

// ===================================================================
// generateZshCompletion — name sanitization
// ===================================================================

describe('generateZshCompletion — name sanitization', () => {
	it('replaces hyphens in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'my-cli-tool' });
		const script = generateZshCompletion(schema);

		expect(script).toContain('_my_cli_tool() {');
		// compdef still uses original name
		expect(script).toContain('#compdef my-cli-tool');
	});

	it('replaces dots in CLI name for function identifier', () => {
		const schema = minimalSchema({ name: 'app.cli' });
		const script = generateZshCompletion(schema);

		expect(script).toContain('_app_cli() {');
	});
});

// ===================================================================
// generateZshCompletion — name escaping (shell injection prevention)
// ===================================================================

describe('generateZshCompletion — name escaping', () => {
	it('leaves shell-safe names unquoted in #compdef', () => {
		const script = generateZshCompletion(minimalSchema({ name: 'my-cli' }));

		expect(script).toContain('#compdef my-cli');
	});

	it('single-quotes names with spaces in #compdef', () => {
		const script = generateZshCompletion(minimalSchema({ name: 'my cli' }));

		expect(script).toContain("#compdef 'my cli'");
	});

	it('escapes single quotes in CLI name for #compdef', () => {
		const script = generateZshCompletion(minimalSchema({ name: "it's" }));

		expect(script).toContain("#compdef 'it'\\''s'");
	});

	it('single-quotes names with backticks in #compdef', () => {
		const script = generateZshCompletion(minimalSchema({ name: 'cli`whoami`' }));

		expect(script).toContain("#compdef 'cli`whoami`'");
	});

	it('single-quotes names with dollar signs in #compdef', () => {
		const script = generateZshCompletion(minimalSchema({ name: '$HOME' }));

		expect(script).toContain("#compdef '$HOME'");
	});
});

// ===================================================================
// generateCompletion — unified dispatcher
// ===================================================================

describe('generateCompletion — dispatcher', () => {
	it('delegates bash to generateBashCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'bash');

		expect(script).toContain('_testcli_completions() {');
		expect(script).toContain('complete -F _testcli_completions testcli');
	});

	it('delegates zsh to generateZshCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'zsh');

		expect(script).toContain('#compdef testcli');
		expect(script).toContain('_testcli() {');
	});

	it('throws CLIError for fish (unsupported)', () => {
		const schema = minimalSchema();

		expect(() => generateCompletion(schema, 'fish')).toThrow();

		try {
			generateCompletion(schema, 'fish');
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.code).toBe('UNSUPPORTED_OPERATION');
				expect(e.message).toContain('fish');
				expect(e.message).toContain('not yet supported');
			}
		}
	});

	it('throws CLIError for powershell (unsupported)', () => {
		const schema = minimalSchema();

		expect(() => generateCompletion(schema, 'powershell')).toThrow();

		try {
			generateCompletion(schema, 'powershell');
		} catch (e: unknown) {
			expect(isCLIError(e)).toBe(true);
			if (isCLIError(e)) {
				expect(e.code).toBe('UNSUPPORTED_OPERATION');
				expect(e.message).toContain('powershell');
				expect(e.message).toContain('not yet supported');
			}
		}
	});

	it('passes options through to bash generator', () => {
		const schema = minimalSchema();
		const options: CompletionOptions = { functionPrefix: '_custom' };
		const script = generateCompletion(schema, 'bash', options);

		expect(script).toContain('__custom_completions() {');
	});
});
