/**
 * Tests for completion types, Shell enum, and generators.
 */

import { describe, expect, it } from 'vitest';
import type { CLISchema } from '#internals/core/cli/index.ts';
import { createSchema } from '#internals/core/schema/flag.ts';
import type {
	ActivityEvent,
	CommandSchema,
	FlagSchema,
	FlagSchemaOverrides,
} from '#internals/core/schema/index.ts';
import type { CompletionOptions } from './index.ts';
import {
	generateBashCompletion,
	generateCompletion,
	generateFishCompletion,
	generatePowerShellCompletion,
	generateZshCompletion,
	SHELLS,
} from './index.ts';

// === Test helpers

/** Minimal FlagSchema with all required fields. */
function flagSchema(overrides: FlagSchemaOverrides = {}): FlagSchema {
	return createSchema(overrides.kind ?? 'string', overrides);
}

/** Minimal CommandSchema with all required fields. */
function commandSchema(overrides: Partial<CommandSchema> = {}): CommandSchema {
	return {
		name: 'test',
		description: undefined,
		aliases: [],
		hidden: false,
		examples: [],
		flags: {},
		args: [],
		hasAction: true,
		interactive: undefined,
		middleware: [],
		commands: [],
		...overrides,
	};
}

/** Wrap CommandSchema into an ErasedCommand for CLISchema.commands. */
function erased(schema: CommandSchema) {
	return {
		schema,
		subcommands: new Map(),
		_execute() {
			return Promise.resolve({
				stdout: [] as string[],
				stderr: [] as string[],
				activity: [] as ActivityEvent[],
				exitCode: 0,
				error: undefined,
			});
		},
	};
}

/** Options for `minimalSchema()` — all fields optional, allows explicit `undefined`. */
interface MinimalSchemaOverrides {
	readonly name?: string;
	readonly version?: string | undefined;
	readonly description?: string | undefined;
	readonly commands?: CLISchema['commands'];
	readonly defaultCommand?: CLISchema['defaultCommand'];
	readonly configSettings?: CLISchema['configSettings'];
	readonly packageJsonSettings?: CLISchema['packageJsonSettings'];
	readonly plugins?: CLISchema['plugins'];
}

/** Minimal CLISchema for completion tests. */
function minimalSchema(overrides: MinimalSchemaOverrides = {}): CLISchema {
	return {
		name: overrides.name ?? 'testcli',
		inheritName: false,
		version: 'version' in overrides ? overrides.version : '1.0.0',
		description: 'description' in overrides ? overrides.description : 'A test CLI',
		commands: overrides.commands ?? [],
		...('defaultCommand' in overrides
			? { defaultCommand: overrides.defaultCommand }
			: { defaultCommand: undefined }),
		...(overrides.configSettings !== undefined
			? { configSettings: overrides.configSettings }
			: { configSettings: undefined }),
		...(overrides.packageJsonSettings !== undefined
			? { packageJsonSettings: overrides.packageJsonSettings }
			: { packageJsonSettings: undefined }),
		plugins: overrides.plugins ?? [],
	};
}

import {
	extractBashRootWords,
	extractFishCompletionLines,
	extractZshRootFunction,
} from './completion-test-helpers.ts';

// === Shell type — SHELLS constant

describe('Shell type — SHELLS constant', () => {
	it('contains only implemented shell targets', () => {
		expect(SHELLS).toEqual(['bash', 'zsh', 'fish', 'powershell']);
	});

	it('is a frozen readonly tuple', () => {
		expect(Object.isFrozen(SHELLS)).toBe(true);
	});
});

// === CompletionOptions — type contract

describe('CompletionOptions — type contract', () => {
	it('accepts empty options', () => {
		const options: CompletionOptions = {};
		expect(options).toEqual({});
	});

	it('accepts functionPrefix', () => {
		const options: CompletionOptions = { functionPrefix: '_myapp' };
		expect(options.functionPrefix).toBe('_myapp');
	});

	it('accepts rootMode', () => {
		const options: CompletionOptions = { rootMode: 'surface' };
		expect(options.rootMode).toBe('surface');
	});
});

// === generateBashCompletion

describe('generateBashCompletion', () => {
	// --- script structure

	describe('script structure', () => {
		it('generates shebang and header comment', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain('#!/usr/bin/env bash');
			expect(script).toContain('# Bash completion for testcli');
			expect(script).toContain('# Generated by @kjanat/dreamcli');
		});

		it('generates function named _<name>_completions', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain('_testcli_completions() {');
		});

		it('uses _init_completion for variable setup', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain('local cur prev words cword');
			expect(script).toContain('_init_completion || return');
		});

		it('registers with complete -F', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain('complete -F _testcli_completions testcli');
		});

		it('includes --help and --version as root completions', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain('--help');
			expect(script).toContain('--version');
		});

		it('includes --version when schema has version', () => {
			const script = generateBashCompletion(
				minimalSchema({
					version: '1.0.0',
					commands: [erased(commandSchema({ name: 'deploy' }))],
				}),
			);

			expect(script).toContain('--version');
		});

		it('omits --version when schema has no version', () => {
			const script = generateBashCompletion(
				minimalSchema({
					version: undefined,
					commands: [erased(commandSchema({ name: 'deploy' }))],
				}),
			);

			expect(script).toContain('--help');
			expect(script).not.toContain('--version');
		});
	});

	// --- functionPrefix option

	describe('functionPrefix option', () => {
		it('uses functionPrefix instead of schema name for function', () => {
			const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'myapp' });

			expect(script).toContain('_myapp_completions() {');
			expect(script).toContain('complete -F _myapp_completions testcli');
		});

		it('sanitizes non-identifier characters in prefix', () => {
			const script = generateBashCompletion(minimalSchema(), { functionPrefix: 'my-app.v2' });

			expect(script).toMatch(/_my_app_v2_[0-9a-f]{8}_completions\(\) \{/);
		});
	});

	// --- subcommand completions

	describe('subcommand completions', () => {
		it('lists subcommand names at root level', () => {
			const schema = minimalSchema({
				commands: [
					erased(commandSchema({ name: 'deploy' })),
					erased(commandSchema({ name: 'build' })),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("'deploy build --help --version'");
		});

		it('excludes hidden commands from completions', () => {
			const schema = minimalSchema({
				commands: [
					erased(commandSchema({ name: 'deploy' })),
					erased(commandSchema({ name: 'secret', hidden: true })),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('deploy');
			expect(script).not.toContain('secret');
		});

		it('includes command aliases in subcommand detection', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'deploy', aliases: ['d', 'ship'] }))],
			});
			const script = generateBashCompletion(schema);

			// Aliases should appear in the case pattern for subcommand detection
			expect(script).toContain('deploy|d|ship)');
		});

		it('escapes quotes in subcommand detection', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: "it's", aliases: ['quo"te'] }))],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('it\\\'s|quo\\"te)');
		});

		it('escapes metacharacters in top-level command aliases', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'depl*oy', aliases: ['d?', 'ship|it'] }))],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('depl\\*oy|d\\?|ship\\|it)');
		});

		it('preserves metacharacters in double-quoted nested command paths', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'db*',
							commands: [commandSchema({ name: 'migr?te' })],
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('"db* migr?te"');
		});
	});

	// --- root completion policy

	describe('root completion policy', () => {
		it('keeps hybrid CLIs command-centric by default', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
					},
				}),
			);
			const status = erased(commandSchema({ name: 'status' }));
			const schema = minimalSchema({
				commands: [serve, status],
				defaultCommand: serve,
			});

			const rootWords = extractBashRootWords(generateBashCompletion(schema));

			expect(rootWords).toEqual(['serve', 'status', '--help', '--version']);
		});

		it('exposes default-command flags at the root in surface mode', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
						verbose: flagSchema({ kind: 'boolean', propagate: true, description: 'Verbose' }),
					},
					commands: [
						commandSchema({
							name: 'inspect',
							flags: {
								childOnly: flagSchema({ kind: 'boolean', description: 'Child only' }),
							},
						}),
					],
				}),
			);
			const status = erased(commandSchema({ name: 'status' }));
			const schema = minimalSchema({
				commands: [serve, status],
				defaultCommand: serve,
			});

			const rootWords = extractBashRootWords(
				generateBashCompletion(schema, { rootMode: 'surface' }),
			);

			expect(rootWords).toContain('serve');
			expect(rootWords).toContain('status');
			expect(rootWords).toContain('--help');
			expect(rootWords).toContain('--version');
			expect(rootWords).toContain('--port');
			expect(rootWords).toContain('-p');
			expect(rootWords).toContain('--verbose');
			expect(rootWords).not.toContain('--childOnly');
		});

		it('exposes default-command flags for a single visible default even in subcommands mode', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
					},
				}),
			);
			const schema = minimalSchema({
				commands: [serve],
				defaultCommand: serve,
			});

			const rootWords = extractBashRootWords(generateBashCompletion(schema));

			expect(rootWords).toEqual(['serve', '--help', '--version', '--port', '-p']);
		});
	});

	// --- flag completions

	describe('flag completions', () => {
		it('includes --flagname for each registered flag', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({ kind: 'string', description: 'AWS region' }),
								force: flagSchema({ kind: 'boolean' }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--region');
			expect(script).toContain('--force');
		});

		it('includes short aliases as -<alias>', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({ kind: 'boolean', aliases: ['f'] }),
								verbose: flagSchema({ kind: 'boolean', aliases: ['v'] }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('-f');
			expect(script).toContain('-v');
		});

		it('includes long aliases as --<alias>', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({ kind: 'boolean', aliases: ['no-confirm'] }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--no-confirm');
		});

		it('excludes hidden aliases from bash completion candidates', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								'skip-pass': flagSchema({
									kind: 'boolean',
									aliases: [
										{ name: 'skipPass', hidden: true },
										{ name: 'x', hidden: false },
									],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--skip-pass');
			expect(script).toContain('-x');
			expect(script).not.toContain('--skipPass');
		});
	});

	// --- enum value completions

	describe('enum value completions', () => {
		it('generates case branch for enum flag values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({
									kind: 'enum',
									enumValues: ['us-east-1', 'eu-west-1', 'ap-south-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain(`case "\${enum_flag:-$prev}" in`);
			expect(script).toContain('--region)');
			expect(script).toContain("'us-east-1 eu-west-1 ap-south-1'");
		});

		it('includes enum flag aliases in case pattern', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({
									kind: 'enum',
									aliases: ['r'],
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--region|-r)');
		});

		it('escapes metacharacters in enum flag case patterns', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								're*gion': flagSchema({
									kind: 'enum',
									aliases: ['r?'],
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--re\\*gion|--r\\?)');
		});

		it('escapes quotes in enum flag case patterns', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								"we'ird": flagSchema({
									kind: 'enum',
									aliases: ["quo'te"],
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("--we\\'ird|--quo\\'te)");
		});

		it('keeps hidden long aliases in enum case patterns', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								'skip-pass': flagSchema({
									kind: 'enum',
									aliases: [{ name: 'skipPass', hidden: true }],
									enumValues: ['yes', 'no'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('--skip-pass|--skipPass)');
		});

		it('omits enum case section when no enum flags exist', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({ kind: 'boolean' }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).not.toContain(`case "\${enum_flag:-$prev}" in`);
		});

		// --- Cross-command enum isolation ---

		it('completes correct enum values per command when same-named flag has different values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								env: flagSchema({
									kind: 'enum',
									enumValues: ['prod', 'staging'],
								}),
							},
						}),
					),
					erased(
						commandSchema({
							name: 'test',
							flags: {
								env: flagSchema({
									kind: 'enum',
									enumValues: ['unit', 'e2e'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);
			const lines = script.split('\n');

			// Find per-command case branches (inside "Complete flags" section)
			const flagSectionStart = lines.findIndex((l) => l.includes('Complete flags'));
			const flagSection = lines.slice(flagSectionStart);

			const deployIdx = flagSection.findIndex((l) => l.trim().startsWith('deploy)'));
			const testIdx = flagSection.findIndex((l) => l.trim().startsWith('test)'));

			const deployBlock = flagSection.slice(deployIdx, testIdx).join('\n');
			const testBlock = flagSection.slice(testIdx).join('\n');

			expect(deployBlock).toContain("'prod staging'");
			expect(deployBlock).not.toContain('unit');
			expect(deployBlock).not.toContain('e2e');

			expect(testBlock).toContain("'unit e2e'");
			expect(testBlock).not.toContain('prod');
			expect(testBlock).not.toContain('staging');
		});

		it('handles mixed enum and non-enum flags across commands', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								env: flagSchema({
									kind: 'enum',
									enumValues: ['prod', 'staging'],
								}),
								force: flagSchema({ kind: 'boolean' }),
							},
						}),
					),
					erased(
						commandSchema({
							name: 'build',
							flags: {
								target: flagSchema({ kind: 'string' }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);
			const lines = script.split('\n');

			const flagSectionStart = lines.findIndex((l) => l.includes('Complete flags'));
			const flagSection = lines.slice(flagSectionStart);

			const deployIdx = flagSection.findIndex((l) => l.trim().startsWith('deploy)'));
			const buildIdx = flagSection.findIndex((l) => l.trim().startsWith('build)'));

			const deployBlock = flagSection.slice(deployIdx, buildIdx).join('\n');
			const buildBlock = flagSection.slice(buildIdx).join('\n');

			// Deploy should have enum case block
			expect(deployBlock).toContain(`case "\${enum_flag:-$prev}" in`);
			expect(deployBlock).toContain("'prod staging'");

			// Build should NOT have enum case block (no enum flags)
			expect(buildBlock).not.toContain(`case "\${enum_flag:-$prev}" in`);
		});
	});

	// --- enum value escaping

	describe('enum value escaping', () => {
		it('passes simple values through unescaped', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({
									kind: 'enum',
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("compgen -W 'us-east-1 eu-west-1'");
			expect(script).not.toContain('IFS');
		});

		it('uses $-quoting with IFS for values containing spaces', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								env: flagSchema({
									kind: 'enum',
									enumValues: ['hello world', 'foo'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("local IFS=$'\\n'");
			expect(script).toContain("compgen -W $'hello world\\nfoo'");
		});

		it('escapes single quotes in enum values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								msg: flagSchema({
									kind: 'enum',
									enumValues: ["it's", 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("local IFS=$'\\n'");
			expect(script).toContain("it\\'s");
		});

		it('escapes backslashes in enum values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								path: flagSchema({
									kind: 'enum',
									enumValues: ['C:\\Users', 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("local IFS=$'\\n'");
			expect(script).toContain('C:\\\\Users');
		});

		it('handles mixed pathological values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								weird: flagSchema({
									kind: 'enum',
									enumValues: ["it's here", 'C:\\path', 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			// All values use $'...' quoting because at least one needs it
			expect(script).toContain("local IFS=$'\\n'");
			expect(script).toContain("compgen -W $'");
			expect(script).toContain("it\\'s here");
			expect(script).toContain('C:\\\\path');
			expect(script).toContain('normal');
		});
	});

	// --- no commands

	describe('no commands', () => {
		it('generates script with --help and --version when version defined', () => {
			const script = generateBashCompletion(minimalSchema());

			expect(script).toContain("'--help --version'");
			expect(script).not.toContain('subcmd');
		});

		it('generates script with only --help when no version', () => {
			const script = generateBashCompletion(minimalSchema({ version: undefined }));

			expect(script).toContain("'--help'");
			expect(script).not.toContain('--version');
			expect(script).not.toContain('subcmd');
		});
	});

	// --- name sanitization

	describe('name sanitization', () => {
		it('replaces hyphens in CLI name for function identifier', () => {
			const schema = minimalSchema({ name: 'my-cli-tool' });
			const script = generateBashCompletion(schema);

			expect(script).toMatch(/_my_cli_tool_[0-9a-f]{8}_completions\(\) \{/);
			// complete line still uses original name
			expect(script).toMatch(/complete -F _my_cli_tool_[0-9a-f]{8}_completions my-cli-tool/);
		});

		it('replaces dots in CLI name for function identifier', () => {
			const schema = minimalSchema({ name: 'app.cli' });
			const script = generateBashCompletion(schema);

			expect(script).toMatch(/_app_cli_[0-9a-f]{8}_completions\(\) \{/);
		});
	});

	// --- name escaping

	describe('name escaping', () => {
		it('leaves shell-safe names unquoted in complete line', () => {
			const script = generateBashCompletion(minimalSchema({ name: 'my-cli' }));

			expect(script).toMatch(/complete -F _my_cli_[0-9a-f]{8}_completions my-cli/);
		});

		it('leaves dotted names unquoted in complete line', () => {
			const script = generateBashCompletion(minimalSchema({ name: 'app.v2' }));

			expect(script).toMatch(/complete -F _app_v2_[0-9a-f]{8}_completions app\.v2/);
		});

		it('single-quotes names with spaces in complete line', () => {
			const script = generateBashCompletion(minimalSchema({ name: 'my cli' }));

			expect(script).toMatch(/complete -F _my_cli_[0-9a-f]{8}_completions 'my cli'/);
		});

		it('escapes single quotes in CLI name', () => {
			const script = generateBashCompletion(minimalSchema({ name: "it's" }));

			expect(script).toMatch(/complete -F _it_s_[0-9a-f]{8}_completions 'it'\\''s'/);
		});

		it('single-quotes names with backticks', () => {
			const script = generateBashCompletion(minimalSchema({ name: 'cli`whoami`' }));

			expect(script).toMatch(/complete -F _cli_whoami__+[0-9a-f]{8}_completions 'cli`whoami`'/);
		});

		it('single-quotes names with semicolons', () => {
			const script = generateBashCompletion(minimalSchema({ name: 'cli;rm -rf /' }));

			expect(script).toContain("'cli;rm -rf /'");
		});

		it('single-quotes names with dollar signs', () => {
			const script = generateBashCompletion(minimalSchema({ name: '$HOME' }));

			expect(script).toMatch(/complete -F __HOME_[0-9a-f]{8}_completions '\$HOME'/);
		});
	});

	// --- nested subcommand path detection

	describe('nested subcommand path detection', () => {
		it('generates subcmd_path variable for nested commands', () => {
			const script = generateBashCompletion(nestedSchema());

			expect(script).toContain('subcmd_path=""');
		});

		it('detects top-level commands including aliases', () => {
			const script = generateBashCompletion(nestedSchema());

			// Top-level detection should include db, database, deploy
			expect(script).toContain('db|database)');
			expect(script).toContain('deploy)');
		});

		it('generates path extension for group commands with children', () => {
			const script = generateBashCompletion(nestedSchema());

			// When subcmd_path is "db", should match child names
			expect(script).toContain('migrate)');
			expect(script).toContain('seed|s)');
		});

		it('generates case branches for nested command paths', () => {
			const script = generateBashCompletion(nestedSchema());

			// Should have case branch for "db migrate"
			expect(script).toContain('"db migrate"');
			// Should have case branch for "db seed"
			expect(script).toContain('"db seed"');
		});

		it('escapes quotes in nested subcmd_path assignments', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'db',
							commands: [commandSchema({ name: 'it"migrate' })],
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain('subcmd_path="$subcmd_path it\\"migrate"');
		});

		it('includes flags for nested leaf commands', () => {
			const script = generateBashCompletion(nestedSchema());

			// db migrate should have --dry-run
			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('"db migrate"'));
			expect(migrateIdx).toBeGreaterThan(-1);
			const migrateBlock = lines.slice(migrateIdx, migrateIdx + 10).join('\n');
			expect(migrateBlock).toContain('--dry-run');
		});

		it('includes subcommand names for group commands', () => {
			const script = generateBashCompletion(nestedSchema());

			// db command should complete its children (migrate, seed) plus its own flags
			const lines = script.split('\n');
			const dbBranchIdx = lines.findIndex(
				(l) => l.trim().startsWith('db|database)') || l.trim() === 'db|database)',
			);
			expect(dbBranchIdx).toBeGreaterThan(-1);
			const dbBlock = lines.slice(dbBranchIdx, dbBranchIdx + 15).join('\n');
			expect(dbBlock).toContain('migrate');
			expect(dbBlock).toContain('seed');
		});
	});

	// --- nested propagated flags

	describe('nested propagated flags', () => {
		it('includes propagated flags in nested leaf completions', () => {
			const script = generateBashCompletion(nestedSchema());

			// db migrate should inherit --verbose from db (propagate: true)
			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('"db migrate"'));
			expect(migrateIdx).toBeGreaterThan(-1);
			const migrateBlock = lines.slice(migrateIdx, migrateIdx + 15).join('\n');
			expect(migrateBlock).toContain('--verbose');
			expect(migrateBlock).toContain('-v');
		});

		it('propagated flags appear alongside own flags', () => {
			const script = generateBashCompletion(nestedSchema());

			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('"db migrate"'));
			expect(migrateIdx).toBeGreaterThan(-1);
			const migrateBlock = lines.slice(migrateIdx, migrateIdx + 15).join('\n');
			// Both own flag (--dry-run) and propagated flag (--verbose)
			expect(migrateBlock).toContain('--dry-run');
			expect(migrateBlock).toContain('--verbose');
		});

		it('propagated flags flow through 3 levels', () => {
			const script = generateBashCompletion(deepNestedSchema());

			// db → table → create should inherit --verbose and --host from db
			const lines = script.split('\n');
			const createIdx = lines.findIndex((l) => l.includes('"db table create"'));
			expect(createIdx).toBeGreaterThan(-1);
			const createBlock = lines.slice(createIdx, createIdx + 15).join('\n');
			expect(createBlock).toContain('--verbose');
			expect(createBlock).toContain('--host');
			expect(createBlock).toContain('--if-not-exists');
		});

		it('3-level path detection works', () => {
			const script = generateBashCompletion(deepNestedSchema());

			expect(script).toContain('"db table create"');
			expect(script).toContain('"db table list"');
			expect(script).toContain('"db table"');
		});
	});

	// --- nested hidden commands

	describe('nested hidden commands', () => {
		it('excludes hidden nested commands from completions', () => {
			const hiddenChild = commandSchema({
				name: 'hidden-cmd',
				hidden: true,
			});

			const dbCmd = commandSchema({
				name: 'db',
				description: 'Database',
				commands: [commandSchema({ name: 'migrate', description: 'Migrate' }), hiddenChild],
			});

			const schema = minimalSchema({ commands: [erased(dbCmd)] });
			const script = generateBashCompletion(schema);

			expect(script).toContain('migrate');
			expect(script).not.toContain('hidden-cmd');
		});
	});

	// --- flag operand and -- handling

	describe('flag operand and -- handling', () => {
		it('breaks on literal -- in the walker', () => {
			const script = generateBashCompletion(nestedSchema());
			const lines = script.split('\n');
			const walkerCase = lines.findIndex((l) => l.includes('--) break'));
			expect(walkerCase).toBeGreaterThan(-1);
		});

		it('skips operand after value-taking flags', () => {
			const script = generateBashCompletion(deepNestedSchema());
			// --host and --schema are string flags — their operands must be skipped
			expect(script).toContain('--host');
			expect(script).toContain('--schema');
			// Find the value-flag skip line
			const lines = script.split('\n');
			const skipLine = lines.find((l) => l.includes('((i++)); continue'));
			expect(skipLine).toBeDefined();
			expect(skipLine).toContain('--host');
			expect(skipLine).toContain('--schema');
		});

		it('does not include boolean flags in the value-flag skip pattern', () => {
			const script = generateBashCompletion(deepNestedSchema());
			const lines = script.split('\n');
			const skipLine = lines.find((l) => l.includes('((i++)); continue'));
			expect(skipLine).toBeDefined();
			// --verbose and --if-not-exists are boolean — must NOT be in the skip pattern
			expect(skipLine).not.toContain('--verbose');
			expect(skipLine).not.toContain('--if-not-exists');
		});

		it('includes short aliases for value-taking flags in skip pattern', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'run',
							flags: {
								output: flagSchema({ kind: 'string', aliases: ['o'] }),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);
			const lines = script.split('\n');
			const skipLine = lines.find((l) => l.includes('((i++)); continue'));
			expect(skipLine).toBeDefined();
			expect(skipLine).toContain('--output');
			expect(skipLine).toContain('-o');
		});

		it('keeps hidden long aliases in the value-flag skip pattern', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'run',
							flags: {
								'config-path': flagSchema({
									kind: 'string',
									aliases: [{ name: 'configPath', hidden: true }],
								}),
							},
						}),
					),
				],
			});
			const script = generateBashCompletion(schema);
			const lines = script.split('\n');
			const skipLine = lines.find((l) => l.includes('((i++)); continue'));
			expect(skipLine).toBeDefined();
			expect(skipLine).toContain('--config-path');
			expect(skipLine).toContain('--configPath');
		});

		it('omits value-flag skip line when all flags are boolean', () => {
			const script = generateBashCompletion(nestedSchema());
			// nestedSchema only has boolean flags (dry-run, verbose, force) and one number (count)
			const lines = script.split('\n');
			const skipLine = lines.find((l) => l.includes('((i++)); continue'));
			// count is a number flag, so the skip line should exist
			expect(skipLine).toBeDefined();
			expect(skipLine).toContain('--count');
		});

		it('orders -- break before value-flag skip before boolean skip', () => {
			const script = generateBashCompletion(deepNestedSchema());
			const lines = script.split('\n');
			const breakIdx = lines.findIndex((l) => l.includes('--) break'));
			const skipIdx = lines.findIndex((l) => l.includes('((i++)); continue'));
			const boolIdx = lines.findIndex((l) => l.includes('-*) continue'));
			expect(breakIdx).toBeGreaterThan(-1);
			expect(skipIdx).toBeGreaterThan(breakIdx);
			expect(boolIdx).toBeGreaterThan(skipIdx);
		});
	});

	// --- shell escaping

	describe('shell escaping', () => {
		it('escapes single quotes in subcommand names', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: "it's-cool", description: 'Has quote' }))],
			});
			const script = generateBashCompletion(schema);

			// The single quote must be escaped via '\'' idiom
			expect(script).toContain("it'\\''s-cool");
			// Must not contain a bare unescaped it's-cool inside the compgen string
			expect(script).not.toMatch(/compgen -W '[^']*it's-cool/);
		});

		it('leaves simple names unescaped', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'deploy', description: 'Deploy' }))],
			});
			const script = generateBashCompletion(schema);

			expect(script).toContain("compgen -W 'deploy --help --version'");
		});
	});
});

// === generateZshCompletion

describe('generateZshCompletion', () => {
	// --- script structure

	describe('script structure', () => {
		it('generates #compdef directive with CLI name', () => {
			const script = generateZshCompletion(minimalSchema());

			expect(script).toContain('#compdef testcli');
		});

		it('generates header comment', () => {
			const script = generateZshCompletion(minimalSchema());

			expect(script).toContain('# Zsh completion for testcli');
			expect(script).toContain('# Generated by @kjanat/dreamcli');
		});

		it('generates function named _<name>', () => {
			const script = generateZshCompletion(minimalSchema());

			expect(script).toContain('_testcli() {');
		});

		it('declares local variables for state tracking', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'deploy' }))],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain('local -a subcmds');
			expect(script).toContain('local line state');
		});

		it('ends with compdef registration', () => {
			const script = generateZshCompletion(minimalSchema());

			expect(script).toContain('compdef _testcli testcli');
		});

		it('includes --help in root _arguments', () => {
			const script = generateZshCompletion(minimalSchema());

			expect(script).toContain('--help[Show help text]');
		});

		it('includes --version when schema has version', () => {
			const script = generateZshCompletion(
				minimalSchema({
					version: '1.0.0',
					commands: [erased(commandSchema({ name: 'test' }))],
				}),
			);

			expect(script).toContain('--version[Show version]');
		});

		it('omits --version when schema has no version', () => {
			const script = generateZshCompletion(
				minimalSchema({
					version: undefined,
					commands: [erased(commandSchema({ name: 'test' }))],
				}),
			);

			expect(script).not.toContain('--version');
		});

		it('includes --version in no-commands path when version defined', () => {
			const script = generateZshCompletion(minimalSchema({ version: '2.0.0', commands: [] }));

			expect(script).toContain('--version[Show version]');
		});
	});

	// --- functionPrefix option

	describe('functionPrefix option', () => {
		it('uses functionPrefix instead of schema name for function', () => {
			const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'myapp' });

			expect(script).toContain('_myapp() {');
			expect(script).toContain('compdef _myapp testcli');
		});

		it('sanitizes non-identifier characters in prefix', () => {
			const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'my-app.v2' });

			expect(script).toMatch(/_my_app_v2_[0-9a-f]{8}\(\) \{/);
		});

		it('keeps #compdef using original CLI name, not prefix', () => {
			const script = generateZshCompletion(minimalSchema(), { functionPrefix: 'myapp' });

			expect(script).toContain('#compdef testcli');
		});
	});

	// --- subcommand completions

	describe('subcommand completions', () => {
		it('lists subcommands with _describe', () => {
			const schema = minimalSchema({
				commands: [
					erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
					erased(commandSchema({ name: 'build', description: 'Build project' })),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("_describe 'command' subcmds");
			expect(script).toContain("'deploy:Deploy app'");
			expect(script).toContain("'build:Build project'");
		});

		it('includes top-level command aliases in _describe candidates', () => {
			const schema = minimalSchema({
				commands: [
					erased(commandSchema({ name: 'deploy', aliases: ['d'], description: 'Deploy app' })),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'deploy:Deploy app'");
			expect(script).toContain("'d:Deploy app'");
		});

		it('excludes hidden commands from completions', () => {
			const schema = minimalSchema({
				commands: [
					erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
					erased(commandSchema({ name: 'secret', hidden: true })),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain('deploy');
			expect(script).not.toContain('secret');
		});

		it('includes command aliases in case pattern', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'depl*oy', aliases: ['d?', 'ship|it'] }))],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain('depl\\*oy|d\\?|ship\\|it)');
		});

		it('escapes quotes in subcommand lists and dispatch patterns', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: "it's",
							aliases: ['quo"te'],
							description: 'Deploy',
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'it'\\''s:Deploy'");
			expect(script).toContain('it\\\'s|quo\\"te)');
		});

		it('escapes metacharacters in child command dispatch patterns', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'db',
							commands: [commandSchema({ name: 'migr?te', aliases: ['move|it'] })],
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain('migr\\?te|move\\|it)');
		});

		it('uses command name as description when description is undefined', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'deploy', description: undefined }))],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'deploy:deploy'");
		});

		it('escapes colons in descriptions', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'deploy', description: 'Deploy: now' }))],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'deploy:Deploy: now'");
		});
	});

	// --- root completion policy

	describe('root completion policy', () => {
		it('keeps hybrid CLIs command-centric by default', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
					},
				}),
			);
			const status = erased(commandSchema({ name: 'status', description: 'Status' }));
			const schema = minimalSchema({
				commands: [serve, status],
				defaultCommand: serve,
			});

			const rootFunction = extractZshRootFunction(generateZshCompletion(schema), '_testcli');

			expect(rootFunction).toContain("'--help[Show help text]'");
			expect(rootFunction).toContain("'--version[Show version]'");
			expect(rootFunction).not.toContain("'--port[Port]:value:'");
			expect(rootFunction).toContain("'1: :->subcmd'");
			expect(rootFunction).toContain("'serve:serve'");
			expect(rootFunction).toContain("'status:Status'");
		});

		it('exposes default-command flags at the root in surface mode', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
						verbose: flagSchema({
							kind: 'boolean',
							propagate: true,
							description: 'Verbose',
						}),
					},
					commands: [
						commandSchema({
							name: 'inspect',
							flags: {
								childOnly: flagSchema({ kind: 'boolean', description: 'Child only' }),
							},
						}),
					],
				}),
			);
			const status = erased(commandSchema({ name: 'status' }));
			const schema = minimalSchema({
				commands: [serve, status],
				defaultCommand: serve,
			});

			const rootFunction = extractZshRootFunction(
				generateZshCompletion(schema, { rootMode: 'surface' }),
				'_testcli',
			);

			expect(rootFunction).toContain("'(-p --port)'{-p,--port}'[Port]:value:'");
			expect(rootFunction).toContain("'--verbose[Verbose]'");
			expect(rootFunction).not.toContain("'--childOnly[Child only]'");
		});

		it('exposes default-command flags for a single visible default even in subcommands mode', () => {
			const serve = erased(
				commandSchema({
					name: 'serve',
					flags: {
						port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
					},
				}),
			);
			const schema = minimalSchema({
				commands: [serve],
				defaultCommand: serve,
			});

			const rootFunction = extractZshRootFunction(generateZshCompletion(schema), '_testcli');

			expect(rootFunction).toContain("'(-p --port)'{-p,--port}'[Port]:value:'");
		});
	});

	describe('extractZshRootFunction — boundary', () => {
		it('includes the closing brace', () => {
			const schema = minimalSchema({
				commands: [erased(commandSchema({ name: 'run' }))],
			});
			const body = extractZshRootFunction(generateZshCompletion(schema), '_testcli');
			expect(body).toMatch(/\}$/);
		});
	});

	// --- flag completions

	describe('flag completions', () => {
		it('generates _arguments specs for command flags', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({ kind: 'string', description: 'AWS region' }),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain('_arguments');
			expect(script).toContain('--region[AWS region]');
		});

		it('generates mutual exclusion group for short aliases', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({
									kind: 'boolean',
									aliases: ['f'],
									description: 'Force',
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("(-f --force)'{-f,--force}'[Force]");
		});

		it('includes visible long aliases and excludes hidden aliases in zsh specs', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								'skip-pass': flagSchema({
									kind: 'boolean',
									description: 'Skip pass update',
									aliases: [
										{ name: 'x', hidden: false },
										{ name: 'skipPass', hidden: false },
										{ name: 'legacySkipPass', hidden: true },
									],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(
				"(-x --skip-pass --skipPass)'{-x,--skip-pass,--skipPass}'[Skip pass update]",
			);
			expect(script).not.toContain('--legacySkipPass');
		});

		it('escapes quotes in flag spec names', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								"we'ird": flagSchema({
									kind: 'boolean',
									description: 'Has quote',
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("--we'\\''ird[Has quote]");
		});

		it('omits value part for boolean flags', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({
									kind: 'boolean',
									description: 'Force deploy',
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			// Boolean flag should end at the description, no :value: part
			expect(script).toContain("'--force[Force deploy]'");
		});

		it('adds :value: for string flags', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								name: flagSchema({ kind: 'string', description: 'Name' }),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'--name[Name]:value:'");
		});

		it('escapes closing brackets in flag descriptions', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								name: flagSchema({ kind: 'string', description: 'A]B' }),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'--name[A\\]B]:value:'");
		});

		it('adds enum values for enum flags', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({
									kind: 'enum',
									description: 'Region',
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'--region[Region]:value:(us-east-1 eu-west-1)'");
		});

		it('uses flag name as description when description is undefined', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								verbose: flagSchema({
									kind: 'boolean',
									description: undefined,
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("'--verbose[verbose]'");
		});
	});

	// --- enum value escaping

	describe('enum value escaping', () => {
		it('passes simple values through unescaped', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								region: flagSchema({
									kind: 'enum',
									description: 'Region',
									enumValues: ['us-east-1', 'eu-west-1'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(':value:(us-east-1 eu-west-1)');
		});

		it('escapes spaces in enum values with backslash', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								env: flagSchema({
									kind: 'enum',
									description: 'Environment',
									enumValues: ['hello world', 'foo'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(':value:(hello\\ world foo)');
		});

		it('escapes single quotes in enum values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								msg: flagSchema({
									kind: 'enum',
									description: 'Message',
									enumValues: ["it's", 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(":value:(it'\\''s normal)");
		});

		it('escapes backslashes in enum values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								path: flagSchema({
									kind: 'enum',
									description: 'Path',
									enumValues: ['C:\\Users', 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(':value:(C:\\\\Users normal)');
		});

		it('escapes parentheses in enum values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								expr: flagSchema({
									kind: 'enum',
									description: 'Expr',
									enumValues: ['(a)', 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain(':value:(\\(a\\) normal)');
		});

		it('handles mixed pathological values', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								weird: flagSchema({
									kind: 'enum',
									description: 'Weird',
									enumValues: ["it's here", 'C:\\path', 'normal'],
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("it'\\''s\\ here");
			expect(script).toContain('C:\\\\path');
			expect(script).toContain('normal');
		});
	});

	// --- no commands

	describe('no commands', () => {
		it('generates script with only --help when no commands', () => {
			const script = generateZshCompletion(minimalSchema({ version: undefined }));

			expect(script).toContain('_arguments');
			expect(script).toContain("'--help[Show help text]'");
			expect(script).not.toContain('subcmds');
			expect(script).not.toContain('_describe');
		});
	});

	// --- name sanitization

	describe('name sanitization', () => {
		it('replaces hyphens in CLI name for function identifier', () => {
			const schema = minimalSchema({ name: 'my-cli-tool' });
			const script = generateZshCompletion(schema);

			expect(script).toMatch(/_my_cli_tool_[0-9a-f]{8}\(\) \{/);
			// compdef still uses original name
			expect(script).toContain('#compdef my-cli-tool');
		});

		it('replaces dots in CLI name for function identifier', () => {
			const schema = minimalSchema({ name: 'app.cli' });
			const script = generateZshCompletion(schema);

			expect(script).toMatch(/_app_cli_[0-9a-f]{8}\(\) \{/);
		});
	});

	// --- name escaping

	describe('name escaping', () => {
		it('leaves shell-safe names unquoted in #compdef', () => {
			const script = generateZshCompletion(minimalSchema({ name: 'my-cli' }));

			expect(script).toContain('#compdef my-cli');
		});

		it('single-quotes names with spaces in #compdef', () => {
			const script = generateZshCompletion(minimalSchema({ name: 'my cli' }));

			expect(script).toContain("#compdef 'my cli'");
		});

		it('escapes single quotes in CLI name for #compdef', () => {
			const script = generateZshCompletion(minimalSchema({ name: "it's" }));

			expect(script).toContain("#compdef 'it'\\''s'");
		});

		it('single-quotes names with backticks in #compdef', () => {
			const script = generateZshCompletion(minimalSchema({ name: 'cli`whoami`' }));

			expect(script).toContain("#compdef 'cli`whoami`'");
		});

		it('single-quotes names with dollar signs in #compdef', () => {
			const script = generateZshCompletion(minimalSchema({ name: '$HOME' }));

			expect(script).toContain("#compdef '$HOME'");
		});
	});

	// --- nested helper functions

	describe('nested helper functions', () => {
		it('generates helper function for group commands', () => {
			const script = generateZshCompletion(nestedSchema());

			// Should have a _testcli_db() helper function
			expect(script).toContain('_testcli_db() {');
		});

		it('helper function uses _arguments -C for group with children', () => {
			const script = generateZshCompletion(nestedSchema());

			// _testcli_db should use _arguments -C (it has subcommands)
			const lines = script.split('\n');
			const dbFuncIdx = lines.findIndex((l) => l.includes('_testcli_db() {'));
			expect(dbFuncIdx).toBeGreaterThan(-1);
			const dbFunc = lines.slice(dbFuncIdx, dbFuncIdx + 30).join('\n');
			expect(dbFunc).toContain('_arguments -C');
		});

		it('helper function lists subcommands via _describe', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const dbFuncIdx = lines.findIndex((l) => l.includes('_testcli_db() {'));
			const dbFunc = lines.slice(dbFuncIdx, dbFuncIdx + 30).join('\n');
			expect(dbFunc).toContain("'migrate:Run migrations'");
			expect(dbFunc).toContain("'seed:Seed database'");
			expect(dbFunc).toContain("_describe 'command' subcmds");
		});

		it('helper function includes child aliases in _describe candidates', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const dbFuncIdx = lines.findIndex((l) => l.includes('_testcli_db() {'));
			const dbFunc = lines.slice(dbFuncIdx, dbFuncIdx + 30).join('\n');
			expect(dbFunc).toContain("'s:Seed database'");
		});

		it('delegates to leaf helper for nested commands', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const dbFuncIdx = lines.findIndex((l) => l.includes('_testcli_db() {'));
			const dbFunc = lines.slice(dbFuncIdx, dbFuncIdx + 40).join('\n');
			expect(dbFunc).toContain('_testcli_db_migrate');
			expect(dbFunc).toContain('_testcli_db_seed');
		});

		it('generates leaf helper functions for nested commands', () => {
			const script = generateZshCompletion(nestedSchema());

			expect(script).toContain('_testcli_db_migrate() {');
			expect(script).toContain('_testcli_db_seed() {');
		});

		it('leaf helper includes own flags', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('_testcli_db_migrate() {'));
			const migrateFunc = lines.slice(migrateIdx, migrateIdx + 10).join('\n');
			expect(migrateFunc).toContain('--dry-run');
		});

		it('root function dispatches to group helper', () => {
			const script = generateZshCompletion(nestedSchema());

			// In the main function's args case, db should dispatch to _testcli_db
			const lines = script.split('\n');
			const mainFuncIdx = lines.findIndex((l) => l.includes('_testcli() {'));
			const mainFunc = lines.slice(mainFuncIdx).join('\n');
			expect(mainFunc).toContain('_testcli_db');
		});
	});

	// --- nested propagated flags

	describe('nested propagated flags', () => {
		it('includes propagated flags in leaf helper functions', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('_testcli_db_migrate() {'));
			expect(migrateIdx).toBeGreaterThan(-1);
			const migrateFunc = lines.slice(migrateIdx, migrateIdx + 10).join('\n');
			// Should have both own flag (--dry-run) and propagated (--verbose/-v)
			expect(migrateFunc).toContain('--dry-run');
			expect(migrateFunc).toContain('--verbose');
		});

		it('propagated flags use proper zsh spec format', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const migrateIdx = lines.findIndex((l) => l.includes('_testcli_db_migrate() {'));
			const migrateFunc = lines.slice(migrateIdx, migrateIdx + 10).join('\n');
			// --verbose has short alias -v, so should have mutual exclusion group
			expect(migrateFunc).toMatch(/\(-v --verbose\)/);
		});

		it('propagated flags flow through 3 levels in zsh', () => {
			const script = generateZshCompletion(deepNestedSchema());

			// db table create should have: --if-not-exists (own) + --verbose, --host (propagated)
			const lines = script.split('\n');
			const createIdx = lines.findIndex((l) => l.includes('_testcli_db_table_create() {'));
			expect(createIdx).toBeGreaterThan(-1);
			const createFunc = lines.slice(createIdx, createIdx + 10).join('\n');
			expect(createFunc).toContain('--if-not-exists');
			expect(createFunc).toContain('--verbose');
			expect(createFunc).toContain('--host');
		});

		it('generates chained helper functions for 3-level nesting', () => {
			const script = generateZshCompletion(deepNestedSchema());

			expect(script).toContain('_testcli_db() {');
			expect(script).toContain('_testcli_db_table() {');
			expect(script).toContain('_testcli_db_table_create() {');
			expect(script).toContain('_testcli_db_table_list() {');
		});

		it('intermediate group helper dispatches to child helpers', () => {
			const script = generateZshCompletion(deepNestedSchema());

			const lines = script.split('\n');
			const tableIdx = lines.findIndex((l) => l.includes('_testcli_db_table() {'));
			const tableFunc = lines.slice(tableIdx, tableIdx + 30).join('\n');
			expect(tableFunc).toContain('_testcli_db_table_create');
			expect(tableFunc).toContain('_testcli_db_table_list');
		});
	});

	// --- multi-short-alias exclusion groups

	describe('multi-short-alias exclusion groups', () => {
		it('includes all short aliases in exclusion group', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								verbose: flagSchema({
									kind: 'boolean',
									aliases: ['v', 'V'],
									description: 'Verbose',
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			// Both -v and -V must appear in the exclusion group and comma list
			expect(script).toContain("(-v -V --verbose)'{-v,-V,--verbose}'[Verbose]");
		});

		it('single short alias still works', () => {
			const schema = minimalSchema({
				commands: [
					erased(
						commandSchema({
							name: 'deploy',
							flags: {
								force: flagSchema({
									kind: 'boolean',
									aliases: ['f'],
									description: 'Force',
								}),
							},
						}),
					),
				],
			});
			const script = generateZshCompletion(schema);

			expect(script).toContain("(-f --force)'{-f,--force}'[Force]");
		});
	});

	// --- nested hidden commands

	describe('nested hidden commands', () => {
		it('excludes hidden nested commands from zsh completions', () => {
			const hiddenChild = commandSchema({
				name: 'hidden-cmd',
				hidden: true,
			});

			const dbCmd = commandSchema({
				name: 'db',
				description: 'Database',
				commands: [commandSchema({ name: 'migrate', description: 'Migrate' }), hiddenChild],
			});

			const schema = minimalSchema({ commands: [erased(dbCmd)] });
			const script = generateZshCompletion(schema);

			expect(script).toContain('migrate');
			expect(script).not.toContain('hidden-cmd');
		});
	});

	// --- nested aliases

	describe('nested aliases', () => {
		it('includes aliases in child command dispatch patterns', () => {
			const script = generateZshCompletion(nestedSchema());

			const lines = script.split('\n');
			const dbFuncIdx = lines.findIndex((l) => l.includes('_testcli_db() {'));
			const dbFunc = lines.slice(dbFuncIdx, dbFuncIdx + 40).join('\n');
			// seed has alias 's'
			expect(dbFunc).toContain('seed|s)');
		});
	});
});

// === generateCompletion — dispatcher

describe('generateCompletion — dispatcher', () => {
	it('delegates bash to generateBashCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'bash');

		expect(script).toContain('_testcli_completions() {');
		expect(script).toContain('complete -F _testcli_completions testcli');
	});

	it('delegates zsh to generateZshCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'zsh');

		expect(script).toContain('#compdef testcli');
		expect(script).toContain('_testcli() {');
	});

	it('passes completion options through to shell generators', () => {
		const serve = erased(
			commandSchema({
				name: 'serve',
				flags: {
					port: flagSchema({ kind: 'string', aliases: ['p'], description: 'Port' }),
				},
			}),
		);
		const status = erased(commandSchema({ name: 'status' }));
		const schema = minimalSchema({
			commands: [serve, status],
			defaultCommand: serve,
		});

		const script = generateCompletion(schema, 'bash', { rootMode: 'surface' });
		const rootWords = extractBashRootWords(script);

		expect(rootWords).toContain('--port');
		expect(rootWords).toContain('-p');
	});

	it('delegates fish to generateFishCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'fish');

		expect(script).toContain('# Fish completion for testcli');
		expect(script).toContain('function __testcli_completions_path');
	});

	it('delegates powershell to generatePowerShellCompletion', () => {
		const schema = minimalSchema();
		const script = generateCompletion(schema, 'powershell');

		expect(script).toContain('# PowerShell completion for testcli');
		expect(script).toContain('Register-ArgumentCompleter -Native -CommandName');
	});

	it('passes options through to bash generator', () => {
		const schema = minimalSchema();
		const options: CompletionOptions = { functionPrefix: '_custom' };
		const script = generateCompletion(schema, 'bash', options);

		expect(script).toContain('__custom_completions() {');
	});
});

// === Nested command completion helpers

/** Build a nested command tree for testing. */
function nestedSchema(overrides: MinimalSchemaOverrides = {}): CLISchema {
	const migrateCmd = commandSchema({
		name: 'migrate',
		description: 'Run migrations',
		flags: {
			'dry-run': flagSchema({ kind: 'boolean', description: 'Dry run mode' }),
		},
	});

	const seedCmd = commandSchema({
		name: 'seed',
		description: 'Seed database',
		aliases: ['s'],
		flags: {
			count: flagSchema({ kind: 'number', description: 'Number of records' }),
		},
	});

	const dbCmd = commandSchema({
		name: 'db',
		description: 'Database operations',
		aliases: ['database'],
		flags: {
			verbose: flagSchema({
				kind: 'boolean',
				description: 'Verbose output',
				aliases: ['v'],
				propagate: true,
			}),
		},
		commands: [migrateCmd, seedCmd],
	});

	const deployCmd = commandSchema({
		name: 'deploy',
		description: 'Deploy app',
		flags: {
			force: flagSchema({ kind: 'boolean', description: 'Force deploy' }),
		},
	});

	return minimalSchema({
		commands: [erased(dbCmd), erased(deployCmd)],
		...overrides,
	});
}

/** 3-level deep nested schema: root → db → table → create */
function deepNestedSchema(): CLISchema {
	const createCmd = commandSchema({
		name: 'create',
		description: 'Create table',
		flags: {
			'if-not-exists': flagSchema({ kind: 'boolean', description: 'Skip if exists' }),
		},
	});

	const listCmd = commandSchema({
		name: 'list',
		description: 'List tables',
	});

	const tableCmd = commandSchema({
		name: 'table',
		description: 'Table operations',
		flags: {
			schema: flagSchema({ kind: 'string', description: 'Schema name' }),
		},
		commands: [createCmd, listCmd],
	});

	const dbCmd = commandSchema({
		name: 'db',
		description: 'Database operations',
		flags: {
			verbose: flagSchema({
				kind: 'boolean',
				description: 'Verbose',
				aliases: ['v'],
				propagate: true,
			}),
			host: flagSchema({
				kind: 'string',
				description: 'Database host',
				propagate: true,
			}),
		},
		commands: [tableCmd],
	});

	return minimalSchema({ commands: [erased(dbCmd)] });
}

// === generateFishCompletion — script structure

describe('generateFishCompletion — script structure', () => {
	it('generates header, helper functions, and install instructions', () => {
		const script = generateFishCompletion(minimalSchema());

		expect(script).toContain('# Fish completion for testcli');
		expect(script).toContain('source (testcli completions fish | psub)');
		expect(script).toContain('~/.config/fish/completions/testcli.fish');
		expect(script).toContain('function __testcli_completions_path');
		expect(script).toContain('complete -c testcli -f');
	});

	it('includes root commands and root flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
				erased(commandSchema({ name: 'build', description: 'Build app' })),
			],
		});
		const script = generateFishCompletion(schema);
		const rootLines = extractFishCompletionLines(script, '__testcli_completions_path_is', '').join(
			'\n',
		);

		expect(rootLines).toContain("-a deploy -d 'Deploy app'");
		expect(rootLines).toContain("-a build -d 'Build app'");
		expect(rootLines).toContain("-l help -d 'Show help text'");
		expect(rootLines).toContain("-l version -d 'Show version'");
	});

	it('includes nested propagated flags and child commands', () => {
		const script = generateFishCompletion(nestedSchema());
		const dbLines = extractFishCompletionLines(script, '__testcli_completions_path_is', 'db');
		const migrateLines = extractFishCompletionLines(
			script,
			'__testcli_completions_path_is',
			'db migrate',
		);

		expect(dbLines.join('\n')).toContain("-a migrate -d 'Run migrations'");
		expect(dbLines.join('\n')).toContain("-a s -d 'Seed database'");
		expect(dbLines.join('\n')).toContain('-l verbose');
		expect(migrateLines.join('\n')).toContain('-l verbose');
		expect(migrateLines.join('\n')).toContain('-s v');
		expect(migrateLines.join('\n')).toContain('-l dry-run');
	});

	it('surfaces default-command flags at the root in surface mode', () => {
		const serve = erased(
			commandSchema({
				name: 'serve',
				description: 'Start server',
				flags: {
					port: flagSchema({ kind: 'number', aliases: ['p'], description: 'Port' }),
					verbose: flagSchema({ kind: 'boolean', description: 'Verbose logging' }),
				},
			}),
		);
		const status = erased(commandSchema({ name: 'status', description: 'Show status' }));
		const script = generateFishCompletion(
			minimalSchema({ commands: [serve, status], defaultCommand: serve }),
			{ rootMode: 'surface' },
		);
		const rootLines = extractFishCompletionLines(script, '__testcli_completions_path_is', '');

		expect(rootLines.join('\n')).toContain('-l port');
		expect(rootLines.join('\n')).toContain('-s p');
		expect(rootLines.join('\n')).toContain('-l verbose');
	});
});

// === generatePowerShellCompletion — script structure

describe('generatePowerShellCompletion — script structure', () => {
	it('generates header, registration, and install instructions', () => {
		const script = generatePowerShellCompletion(minimalSchema());

		expect(script).toContain('# PowerShell completion for testcli');
		expect(script).toContain('testcli completions powershell | Invoke-Expression');
		expect(script).toContain('$PROFILE.CurrentUserCurrentHost');
		expect(script).toContain('Register-ArgumentCompleter -Native -CommandName');
		expect(script).toContain('$script:__testcli_completions_paths = @{');
	});

	it('includes root commands and root flags', () => {
		const schema = minimalSchema({
			commands: [
				erased(commandSchema({ name: 'deploy', description: 'Deploy app' })),
				erased(commandSchema({ name: 'build', description: 'Build app' })),
			],
		});
		const script = generatePowerShellCompletion(schema);

		expect(script).toContain("'' = @{");
		expect(script).toContain("CanonicalName = 'deploy'");
		expect(script).toContain("CanonicalName = 'build'");
		expect(script).toContain("Forms = @('--help')");
		expect(script).toContain("Forms = @('--version')");
	});

	it('includes nested propagated flags and child commands', () => {
		const script = generatePowerShellCompletion(nestedSchema());

		expect(script).toMatch(
			/'db' = @\{[\s\S]*CanonicalName = 'migrate'[\s\S]*CanonicalName = 'seed'/,
		);
		expect(script).toMatch(
			/'db migrate' = @\{[\s\S]*Forms = @\('--verbose', '-v'\)[\s\S]*Forms = @\('--dry-run'\)/,
		);
	});

	it('surfaces default-command flags at the root in surface mode', () => {
		const serve = erased(
			commandSchema({
				name: 'serve',
				description: 'Start server',
				flags: {
					port: flagSchema({ kind: 'number', aliases: ['p'], description: 'Port' }),
					verbose: flagSchema({ kind: 'boolean', description: 'Verbose logging' }),
				},
			}),
		);
		const status = erased(commandSchema({ name: 'status', description: 'Show status' }));
		const script = generatePowerShellCompletion(
			minimalSchema({ commands: [serve, status], defaultCommand: serve }),
			{ rootMode: 'surface' },
		);

		expect(script).toMatch(
			/'' = @\{[\s\S]*Forms = @\('--port', '-p'\)[\s\S]*Forms = @\('--verbose'\)/,
		);
	});

	it('includes enum values in the generated flag metadata', () => {
		const schema = minimalSchema({
			commands: [
				erased(
					commandSchema({
						name: 'deploy',
						flags: {
							env: flagSchema({
								kind: 'enum',
								description: 'Environment',
								enumValues: ['dev', 'prod'],
							}),
						},
					}),
				),
			],
		});
		const script = generatePowerShellCompletion(schema);

		expect(script).toContain("EnumValues = @('dev', 'prod')");
		expect(script).toContain('_AddInlineEnumResults');
	});
});
