/**
 * Shell completion script generation from command schemas.
 *
 * Each shell has a dedicated generator that takes a {@link CLISchema} and
 * returns a complete shell-specific completion script as a string.
 *
 * @module dreamcli/core/completion
 */

import type { CLISchema } from '../cli/index.js';
import { CLIError } from '../errors/index.js';
import type { CommandSchema, FlagSchema } from '../schema/index.js';

// ---------------------------------------------------------------------------
// Shell type — supported completion targets
// ---------------------------------------------------------------------------

/**
 * Supported shell targets for completion script generation.
 *
 * `bash` and `zsh` are implemented first; `fish` and `powershell` are
 * declared for forward compatibility but throw on generation.
 */
type Shell = 'bash' | 'zsh' | 'fish' | 'powershell';

/** All shell values as a readonly tuple (useful for validation). */
const SHELLS: readonly Shell[] = ['bash', 'zsh', 'fish', 'powershell'] as const;

// ---------------------------------------------------------------------------
// CompletionOptions — generator configuration
// ---------------------------------------------------------------------------

/**
 * Options for completion script generation.
 *
 * Passed to individual shell generators alongside the CLI schema.
 * Currently a placeholder — future options may include custom function
 * name prefixes, output style tweaks, etc.
 */
interface CompletionOptions {
	/**
	 * Override the function name prefix in generated scripts.
	 * Defaults to the CLI name from the schema.
	 */
	readonly functionPrefix?: string;
}

// ---------------------------------------------------------------------------
// Generator function signatures
// ---------------------------------------------------------------------------

/**
 * Generates a completion script for the given shell.
 *
 * @param schema - The CLI schema describing commands, flags, and args.
 * @param shell - Target shell.
 * @param options - Optional generator configuration.
 * @returns A complete shell completion script as a string.
 * @throws {CLIError} If the shell is not yet supported.
 */
function generateCompletion(schema: CLISchema, shell: Shell, options?: CompletionOptions): string {
	switch (shell) {
		case 'bash':
			return generateBashCompletion(schema, options);
		case 'zsh':
			return generateZshCompletion(schema, options);
		case 'fish':
		case 'powershell':
			throw new CLIError(`Shell completion for '${shell}' is not yet supported`, {
				code: 'UNSUPPORTED_OPERATION',
			});
	}
}

/**
 * Generates a bash completion script for the CLI.
 *
 * Produces a self-contained bash script with:
 * - A main `_<name>_completions` function using `COMP_WORDS`/`COMP_CWORD`
 * - Per-command case branches with flag and subcommand completions
 * - Enum value completions for `--flag=<value>` patterns
 * - A `complete -F` registration line
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete bash completion script.
 */
function generateBashCompletion(schema: CLISchema, options?: CompletionOptions): string {
	const prefix = options?.functionPrefix ?? schema.name;
	const funcName = `_${sanitizeBashIdentifier(prefix)}_completions`;
	const visibleCommands = schema.commands.map((c) => c.schema).filter((s) => !s.hidden);

	const lines: string[] = [];

	lines.push('#!/usr/bin/env bash');
	lines.push(`# Bash completion for ${schema.name}`);
	lines.push(`# Generated by dreamcli`);
	lines.push('');
	lines.push(`${funcName}() {`);
	lines.push(`\tlocal cur prev words cword`);
	lines.push(`\t_init_completion || return`);
	lines.push('');

	// --- Enum value completions for previous flag ---
	const enumCases = collectEnumCases(visibleCommands);
	if (enumCases.length > 0) {
		lines.push('\t# Complete enum values for flags');
		lines.push('\tcase "$prev" in');
		for (const ec of enumCases) {
			lines.push(`\t\t${ec.flags})`);
			lines.push(`\t\t\tCOMPREPLY=($(compgen -W '${ec.values}' -- "$cur"))`);
			lines.push('\t\t\treturn');
			lines.push('\t\t\t;;');
		}
		lines.push('\t\t*)');
		lines.push('\t\t\t;;');
		lines.push('\tesac');
		lines.push('');
	}

	// --- Subcommand dispatch ---
	if (visibleCommands.length > 0) {
		const subcommandNames = visibleCommands.flatMap((s) => [s.name, ...s.aliases]);

		lines.push('\t# Determine current subcommand');
		lines.push('\tlocal subcmd=""');
		lines.push('\tlocal i');
		lines.push('\tfor ((i = 1; i < cword; i++)); do');
		// biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax, not JS template
		lines.push('\t\tcase "${words[i]}" in');
		lines.push(`\t\t\t${subcommandNames.join('|')})`);
		// biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax, not JS template
		lines.push('\t\t\t\tsubcmd="${words[i]}"');
		lines.push('\t\t\t\tbreak');
		lines.push('\t\t\t\t;;');
		lines.push('\t\tesac');
		lines.push('\tdone');
		lines.push('');

		// --- Per-command flag completions ---
		lines.push('\t# Complete flags for the active subcommand');
		lines.push('\tcase "$subcmd" in');
		for (const cmd of visibleCommands) {
			const allNames = [cmd.name, ...cmd.aliases];
			const flagWords = collectFlagWords(cmd.flags);
			lines.push(`\t\t${allNames.join('|')})`);
			lines.push(`\t\t\tCOMPREPLY=($(compgen -W '${flagWords}' -- "$cur"))`);
			lines.push('\t\t\treturn');
			lines.push('\t\t\t;;');
		}
		lines.push('\t\t*)');
		lines.push('\t\t\t;;');
		lines.push('\tesac');
		lines.push('');

		// --- Root-level: subcommands + global flags ---
		const rootFlags = '--help --version';
		const subNames = visibleCommands.map((s) => s.name).join(' ');
		lines.push(`\t# Root-level completions: subcommands and global flags`);
		lines.push(`\tCOMPREPLY=($(compgen -W '${subNames} ${rootFlags}' -- "$cur"))`);
	} else {
		lines.push(`\tCOMPREPLY=($(compgen -W '--help --version' -- "$cur"))`);
	}

	lines.push('}');
	lines.push('');
	lines.push(`complete -F ${funcName} ${schema.name}`);
	lines.push('');

	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Bash helpers — internal
// ---------------------------------------------------------------------------

/**
 * Sanitize a string for use as a bash function identifier.
 * Replaces non-alphanumeric/underscore characters with underscores.
 *
 * @internal
 */
function sanitizeBashIdentifier(name: string): string {
	return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

/**
 * Collect all `--flag` words (long + short aliases) for a command's flags.
 *
 * @internal
 */
function collectFlagWords(flags: Readonly<Record<string, FlagSchema>>): string {
	const words: string[] = [];
	for (const [name, schema] of Object.entries(flags)) {
		words.push(`--${name}`);
		for (const alias of schema.aliases) {
			words.push(alias.length === 1 ? `-${alias}` : `--${alias}`);
		}
	}
	return words.join(' ');
}

/**
 * A consolidated enum-value case: the flag forms that trigger it and the values.
 *
 * @internal
 */
interface EnumCase {
	readonly flags: string;
	readonly values: string;
}

/**
 * Collect enum flag cases across all visible commands for `case "$prev"` matching.
 *
 * @internal
 */
function collectEnumCases(commands: readonly CommandSchema[]): readonly EnumCase[] {
	const seen = new Map<string, EnumCase>();
	for (const cmd of commands) {
		for (const [name, schema] of Object.entries(cmd.flags)) {
			if (schema.kind !== 'enum' || schema.enumValues === undefined) continue;
			const flagForms = [
				`--${name}`,
				...schema.aliases.map((a) => (a.length === 1 ? `-${a}` : `--${a}`)),
			];
			const key = flagForms.join('|');
			if (!seen.has(key)) {
				seen.set(key, { flags: key, values: schema.enumValues.join(' ') });
			}
		}
	}
	return [...seen.values()];
}

/**
 * Generates a zsh completion script for the CLI.
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete zsh completion script.
 */
function generateZshCompletion(schema: CLISchema, options?: CompletionOptions): string {
	void schema;
	void options;
	throw new CLIError('Zsh completion generation is not yet implemented', {
		code: 'UNSUPPORTED_OPERATION',
	});
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export { generateBashCompletion, generateCompletion, generateZshCompletion, SHELLS };
export type { CompletionOptions, Shell };
