/**
 * Shell completion script generation from command schemas.
 *
 * Each shell has a dedicated generator that takes a {@link CLISchema} and
 * returns a complete shell-specific completion script as a string.
 *
 * @module dreamcli/core/completion
 */

import type { CLISchema } from '../cli/index.js';
import { CLIError } from '../errors/index.js';
import type { CommandSchema, FlagSchema } from '../schema/index.js';

// ---------------------------------------------------------------------------
// Shell type — supported completion targets
// ---------------------------------------------------------------------------

/**
 * Supported shell targets for completion script generation.
 *
 * `bash` and `zsh` are implemented first; `fish` and `powershell` are
 * declared for forward compatibility but throw on generation.
 */
type Shell = 'bash' | 'zsh' | 'fish' | 'powershell';

/** All shell values as a readonly tuple (useful for validation). */
const SHELLS: readonly Shell[] = ['bash', 'zsh', 'fish', 'powershell'] as const;

// ---------------------------------------------------------------------------
// CompletionOptions — generator configuration
// ---------------------------------------------------------------------------

/**
 * Options for completion script generation.
 *
 * Passed to individual shell generators alongside the CLI schema.
 * Currently a placeholder — future options may include custom function
 * name prefixes, output style tweaks, etc.
 */
interface CompletionOptions {
	/**
	 * Override the function name prefix in generated scripts.
	 * Defaults to the CLI name from the schema.
	 */
	readonly functionPrefix?: string;
}

// ---------------------------------------------------------------------------
// Generator function signatures
// ---------------------------------------------------------------------------

/**
 * Generates a completion script for the given shell.
 *
 * @param schema - The CLI schema describing commands, flags, and args.
 * @param shell - Target shell.
 * @param options - Optional generator configuration.
 * @returns A complete shell completion script as a string.
 * @throws {CLIError} If the shell is not yet supported.
 */
function generateCompletion(schema: CLISchema, shell: Shell, options?: CompletionOptions): string {
	switch (shell) {
		case 'bash':
			return generateBashCompletion(schema, options);
		case 'zsh':
			return generateZshCompletion(schema, options);
		case 'fish':
		case 'powershell':
			throw new CLIError(`Shell completion for '${shell}' is not yet supported`, {
				code: 'UNSUPPORTED_OPERATION',
			});
	}
}

/**
 * Generates a bash completion script for the CLI.
 *
 * Produces a self-contained bash script with:
 * - A main `_<name>_completions` function using `COMP_WORDS`/`COMP_CWORD`
 * - Per-command case branches with flag and subcommand completions
 * - Enum value completions for `--flag=<value>` patterns
 * - A `complete -F` registration line
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete bash completion script.
 */
function generateBashCompletion(schema: CLISchema, options?: CompletionOptions): string {
	const prefix = options?.functionPrefix ?? schema.name;
	const funcName = `_${sanitizeShellIdentifier(prefix)}_completions`;
	const visibleCommands = schema.commands.map((c) => c.schema).filter((s) => !s.hidden);

	const lines: string[] = [];

	lines.push('#!/usr/bin/env bash');
	lines.push(`# Bash completion for ${schema.name}`);
	lines.push(`# Generated by dreamcli`);
	lines.push('');
	lines.push(`${funcName}() {`);
	lines.push(`\tlocal cur prev words cword`);
	lines.push(`\t_init_completion || return`);
	lines.push('');

	// --- Subcommand dispatch ---
	if (visibleCommands.length > 0) {
		const subcommandNames = visibleCommands.flatMap((s) => [s.name, ...s.aliases]);

		lines.push('\t# Determine current subcommand');
		lines.push('\tlocal subcmd=""');
		lines.push('\tlocal i');
		lines.push('\tfor ((i = 1; i < cword; i++)); do');
		// biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax, not JS template
		lines.push('\t\tcase "${words[i]}" in');
		lines.push(`\t\t\t${subcommandNames.join('|')})`);
		// biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax, not JS template
		lines.push('\t\t\t\tsubcmd="${words[i]}"');
		lines.push('\t\t\t\tbreak');
		lines.push('\t\t\t\t;;');
		lines.push('\t\tesac');
		lines.push('\tdone');
		lines.push('');

		// --- Per-command: enum value + flag completions ---
		lines.push('\t# Complete flags for the active subcommand');
		lines.push('\tcase "$subcmd" in');
		for (const cmd of visibleCommands) {
			const allNames = [cmd.name, ...cmd.aliases];
			const flagWords = collectFlagWords(cmd.flags);
			const enumCases = collectEnumCases(cmd);
			lines.push(`\t\t${allNames.join('|')})`);
			if (enumCases.length > 0) {
				lines.push('\t\t\tcase "$prev" in');
				for (const ec of enumCases) {
					lines.push(`\t\t\t\t${ec.flags})`);
					lines.push(`\t\t\t\t\tCOMPREPLY=($(compgen -W '${ec.values}' -- "$cur"))`);
					lines.push('\t\t\t\t\treturn');
					lines.push('\t\t\t\t\t;;');
				}
				lines.push('\t\t\t\t*)');
				lines.push('\t\t\t\t\t;;');
				lines.push('\t\t\tesac');
			}
			lines.push(`\t\t\tCOMPREPLY=($(compgen -W '${flagWords}' -- "$cur"))`);
			lines.push('\t\t\treturn');
			lines.push('\t\t\t;;');
		}
		lines.push('\t\t*)');
		lines.push('\t\t\t;;');
		lines.push('\tesac');
		lines.push('');

		// --- Root-level: subcommands + global flags ---
		const rootFlags = schema.version !== undefined ? '--help --version' : '--help';
		const subNames = visibleCommands.map((s) => s.name).join(' ');
		lines.push(`\t# Root-level completions: subcommands and global flags`);
		lines.push(`\tCOMPREPLY=($(compgen -W '${subNames} ${rootFlags}' -- "$cur"))`);
	} else {
		const globalFlags = schema.version !== undefined ? '--help --version' : '--help';
		lines.push(`\tCOMPREPLY=($(compgen -W '${globalFlags}' -- "$cur"))`);
	}

	lines.push('}');
	lines.push('');
	lines.push(`complete -F ${funcName} ${schema.name}`);
	lines.push('');

	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Shared helpers — internal
// ---------------------------------------------------------------------------

/**
 * Sanitize a string for use as a shell function identifier.
 * Replaces non-alphanumeric/underscore characters with underscores.
 * Used by both bash and zsh generators.
 *
 * @internal
 */
function sanitizeShellIdentifier(name: string): string {
	return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// ---------------------------------------------------------------------------
// Bash helpers — internal
// ---------------------------------------------------------------------------

/**
 * Collect all `--flag` words (long + short aliases) for a command's flags.
 *
 * @internal
 */
function collectFlagWords(flags: Readonly<Record<string, FlagSchema>>): string {
	const words: string[] = [];
	for (const [name, schema] of Object.entries(flags)) {
		words.push(`--${name}`);
		for (const alias of schema.aliases) {
			words.push(alias.length === 1 ? `-${alias}` : `--${alias}`);
		}
	}
	return words.join(' ');
}

/**
 * A consolidated enum-value case: the flag forms that trigger it and the values.
 *
 * @internal
 */
interface EnumCase {
	readonly flags: string;
	readonly values: string;
}

/**
 * Collect enum flag cases for a single command's `case "$prev"` matching.
 *
 * Each enum flag produces one case entry with its long/short flag forms
 * as the pattern and enum values as the completions.
 *
 * @internal
 */
function collectEnumCases(cmd: CommandSchema): readonly EnumCase[] {
	const cases: EnumCase[] = [];
	for (const [name, schema] of Object.entries(cmd.flags)) {
		if (schema.kind !== 'enum' || schema.enumValues === undefined) continue;
		const flagForms = [
			`--${name}`,
			...schema.aliases.map((a) => (a.length === 1 ? `-${a}` : `--${a}`)),
		];
		cases.push({ flags: flagForms.join('|'), values: schema.enumValues.join(' ') });
	}
	return cases;
}

// ---------------------------------------------------------------------------
// Zsh completion generator
// ---------------------------------------------------------------------------

/**
 * Generates a zsh completion script for the CLI.
 *
 * Produces a self-contained zsh script with:
 * - A `#compdef` directive for auto-loading
 * - A main `_<name>` function
 * - `_arguments` calls for flags with descriptions
 * - `_describe` for subcommand dispatch
 * - Enum value completions via `->state` dispatch
 *
 * @param schema - The CLI schema.
 * @param options - Optional generator configuration.
 * @returns A complete zsh completion script.
 */
function generateZshCompletion(schema: CLISchema, options?: CompletionOptions): string {
	const prefix = options?.functionPrefix ?? schema.name;
	const funcName = `_${sanitizeShellIdentifier(prefix)}`;
	const visibleCommands = schema.commands.map((c) => c.schema).filter((s) => !s.hidden);

	const lines: string[] = [];

	lines.push(`#compdef ${schema.name}`);
	lines.push(`# Zsh completion for ${schema.name}`);
	lines.push(`# Generated by dreamcli`);
	lines.push('');
	lines.push(`${funcName}() {`);

	if (visibleCommands.length > 0) {
		lines.push('\tlocal -a subcmds');
		lines.push('\tlocal line state');
		lines.push('');

		// --- Root-level: global flags + subcommand argument ---
		lines.push('\t_arguments -C \\');
		lines.push("\t\t'--help[Show help text]' \\");
		if (schema.version !== undefined) {
			lines.push("\t\t'--version[Show version]' \\");
		}
		lines.push("\t\t'1: :->subcmd' \\");
		lines.push("\t\t'*::arg:->args'");
		lines.push('');

		// --- Subcommand list ---
		lines.push('\tcase "$state" in');
		lines.push('\t\tsubcmd)');
		lines.push('\t\t\tsubcmds=(');
		for (const cmd of visibleCommands) {
			const desc = escapeZshDescription(cmd.description ?? cmd.name);
			lines.push(`\t\t\t\t'${cmd.name}:${desc}'`);
		}
		lines.push('\t\t\t)');
		lines.push("\t\t\t_describe 'command' subcmds");
		lines.push('\t\t\t;;');

		// --- Per-command arguments ---
		lines.push('\t\targs)');
		lines.push('\t\t\tcase "$line[1]" in');
		for (const cmd of visibleCommands) {
			const allNames = [cmd.name, ...cmd.aliases];
			lines.push(`\t\t\t\t${allNames.join('|')})`);
			const flagSpecs = buildZshFlagSpecs(cmd);
			if (flagSpecs.length > 0) {
				lines.push('\t\t\t\t\t_arguments \\');
				for (let i = 0; i < flagSpecs.length; i++) {
					const trailing = i < flagSpecs.length - 1 ? ' \\' : '';
					lines.push(`\t\t\t\t\t\t${flagSpecs[i]}${trailing}`);
				}
			}
			lines.push('\t\t\t\t\t;;');
		}
		lines.push('\t\t\tesac');
		lines.push('\t\t\t;;');
		lines.push('\tesac');
	} else {
		// --- No subcommands: just global flags ---
		const globalFlags: string[] = ["'--help[Show help text]'"];
		if (schema.version !== undefined) {
			globalFlags.push("'--version[Show version]'");
		}
		lines.push('\t_arguments \\');
		for (let i = 0; i < globalFlags.length; i++) {
			const trailing = i < globalFlags.length - 1 ? ' \\' : '';
			lines.push(`\t\t${globalFlags[i]}${trailing}`);
		}
	}

	lines.push('}');
	lines.push('');
	lines.push(`${funcName} "$@"`);
	lines.push('');

	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Zsh helpers — internal
// ---------------------------------------------------------------------------

/**
 * Escape single quotes and colons in descriptions for zsh `_describe` format.
 * Zsh uses `'name:description'` syntax — colons in descriptions must be escaped
 * with backslash, and single quotes must be handled.
 *
 * @internal
 */
function escapeZshDescription(text: string): string {
	return text.replace(/\\/g, '\\\\').replace(/'/g, "'\\''").replace(/:/g, '\\:');
}

/**
 * Build `_arguments` flag spec strings for a command.
 *
 * Each flag produces one or more spec strings in zsh `_arguments` format:
 * - `'--name[description]'` for simple flags
 * - `'--name[description]:value:(v1 v2 v3)'` for enum flags
 * - `'(-s --name)'{-s,--name}'[description]'` for flags with short aliases
 *
 * @internal
 */
function buildZshFlagSpecs(cmd: CommandSchema): readonly string[] {
	const specs: string[] = [];
	for (const [name, schema] of Object.entries(cmd.flags)) {
		const desc = escapeZshDescription(schema.description ?? name);
		const longFlag = `--${name}`;
		const shortAliases = schema.aliases.filter((a) => a.length === 1);
		const shortFlag = shortAliases.length > 0 ? `-${shortAliases[0]}` : undefined;

		let valuePart = '';
		if (schema.kind === 'boolean') {
			// Boolean flags take no argument value
		} else if (schema.kind === 'enum' && schema.enumValues !== undefined) {
			valuePart = `:value:(${schema.enumValues.join(' ')})`;
		} else {
			valuePart = ':value:';
		}

		if (shortFlag !== undefined) {
			// Mutual exclusion group: (-s --long)'{-s,--long}'[desc]:value
			const excl = `(${shortFlag} ${longFlag})`;
			specs.push(`'${excl}'{${shortFlag},${longFlag}}'[${desc}]${valuePart}'`);
		} else {
			specs.push(`'${longFlag}[${desc}]${valuePart}'`);
		}
	}
	return specs;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export { generateBashCompletion, generateCompletion, generateZshCompletion, SHELLS };
export type { CompletionOptions, Shell };
