/**
 * Command, flag, and arg schema builders with full type inference.
 *
 * @module dreamcli/core/schema
 */

export type {
	ActivityEvent,
	Fallback,
	ProgressHandle,
	ProgressOptions,
	SpinnerHandle,
	SpinnerOptions,
	TableColumn,
	TableFormat,
	TableOptions,
	TableStream,
} from './activity.ts';
export type {
	AllowedArgPromptConfig,
	ArgConfig,
	ArgDefaultValue,
	ArgDefinition,
	ArgDefinitionBase,
	ArgDefinitionByKind,
	ArgDefinitionOverrides,
	ArgFactory,
	ArgKind,
	ArgParseFn,
	ArgPresence,
	ArgSchema,
	BooleanArgDefinition,
	CustomArgDefinition,
	EnumArgDefinition,
	InferArg,
	InferArgs,
	KeyValueArgDefinition,
	NumberArgDefinition,
	PromptConfigByArgKind,
	ResolvedArgValue,
	StringArgDefinition,
	StringArgElementConfig,
	WithArgPresence,
	WithoutArgElementEligibility,
	WithVariadic,
} from './arg.ts';
export { ARG_KINDS, ARG_PRESENCES, ArgBuilder, arg, createArgSchema } from './arg.ts';
export type {
	ActionHandler,
	ActionParams,
	AnyCommandBuilder,
	CommandArgEntry,
	CommandArgEntryDefinition,
	CommandDefinition,
	CommandExample,
	CommandMeta,
	CommandSchema,
	DeriveHandler,
	DeriveParams,
	ErasedDeriveHandler,
	ErasedInputSources,
	ErasedInteractiveResolver,
	ExampleCommand,
	ExampleMeta,
	InteractiveParams,
	InteractiveResolver,
	InteractiveResult,
	Out,
} from './command.ts';
export {
	CommandBuilder,
	command,
	createCommandSchema,
	group,
	resolveExampleCommand,
} from './command.ts';
export type {
	ArrayFlagDefinition,
	BooleanFlagDefinition,
	ConfirmPromptConfig,
	CountFlagDefinition,
	CustomFlagDefinition,
	DateFlagOptions,
	DuplicateKeys,
	DuplicatePolicy,
	EnumFlagDefinition,
	FlagAlias,
	FlagConfig,
	FlagDefinition,
	FlagDefinitionBase,
	FlagDefinitionByKind,
	FlagDefinitionOverrides,
	FlagFactory,
	FlagKind,
	FlagNegation,
	FlagParseFn,
	FlagPresence,
	FlagSchema,
	InferFlag,
	InferFlags,
	InputPromptConfig,
	KeyValueFlagDefinition,
	MultiselectPromptConfig,
	NumberFlagDefinition,
	PathChecks,
	PathFlagOptions,
	PromptConfig,
	PromptConfigBase,
	PromptKind,
	PromptResult,
	ResolvedValue,
	SelectChoice,
	SelectPromptConfig,
	SourceSplitBinding,
	SplitBinding,
	SplitFormat,
	SplitOptions,
	SplitPolicy,
	SplitSetting,
	StdinBinding,
	StdinConsume,
	StdinOptions,
	StdinWhen,
	StringElementConfig,
	StringFlagDefinition,
	UrlFlagOptions,
	WithoutElementEligibility,
	WithPresence,
} from './flag.ts';
export {
	createFlagSchema,
	DUPLICATE_KEYS,
	FLAG_KINDS,
	FLAG_PRESENCES,
	FlagBuilder,
	flag,
	getFlagNegatedName,
	PROMPT_KINDS,
	SPLIT_FORMATS,
	STDIN_CONSUMES,
	STDIN_WHENS,
} from './flag.ts';
export type {
	ErasedMiddlewareHandler,
	Middleware,
	MiddlewareHandler,
	MiddlewareParams,
} from './middleware.ts';
export { middleware } from './middleware.ts';
export type { NumberConstraints, NumberConstraintViolation } from './number-constraints.ts';
export {
	describeNumberConstraintViolation,
	validateNumberConstraints,
} from './number-constraints.ts';
export type { InputSources, ResolutionProvenance, SourcesOf } from './provenance.ts';
export { wasExplicit } from './provenance.ts';
export type { InternalRunOptions, RunOptions, RunResult } from './run.ts';
export type {
	InferStandardInput,
	InferStandardOutput,
	StandardSchemaV1,
	StandardSchemaV1FailureResult,
	StandardSchemaV1Issue,
	StandardSchemaV1Options,
	StandardSchemaV1PathSegment,
	StandardSchemaV1Props,
	StandardSchemaV1Result,
	StandardSchemaV1SuccessResult,
	StandardSchemaV1Types,
} from './standard.ts';
export type { StringConstraints, StringConstraintViolation } from './string-constraints.ts';
export {
	describeStringConstraintViolation,
	stringConstraintDetails,
	validateStringConstraints,
} from './string-constraints.ts';
