name: autofix.ci
on:
  push: { branches: [master] }
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions: { contents: read }
concurrency: { group: "autofix-${{ github.ref }}", cancel-in-progress: true }
jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env: { RUNNER_PM: bun }
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: denoland/setup-deno@v2
      - uses: kjanat/runner@master
      - run: runner install fmt:autofix lint:autofix
      - run: run fmt:update
        if: github.ref_name == 'master'
      - uses: autofix-ci/action@v1
